# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import enum
from nautilus_trader import model
import typing
__all__ = [
    "KrakenApiResult",
    "KrakenAssetClass",
    "KrakenDataClientConfig",
    "KrakenDataClientFactory",
    "KrakenEnvironment",
    "KrakenExecClientConfig",
    "KrakenExecutionClientFactory",
    "KrakenFillType",
    "KrakenFuturesHttpClient",
    "KrakenFuturesOrderStatus",
    "KrakenFuturesOrderType",
    "KrakenFuturesWebSocketClient",
    "KrakenInstrumentType",
    "KrakenOrderSide",
    "KrakenOrderStatus",
    "KrakenOrderType",
    "KrakenPairStatus",
    "KrakenPositionSide",
    "KrakenProductType",
    "KrakenSendStatus",
    "KrakenSpotHttpClient",
    "KrakenSpotTrigger",
    "KrakenSpotWebSocketClient",
    "KrakenSystemStatus",
    "KrakenTimeInForce",
    "KrakenTriggerSide",
    "KrakenTriggerSignal",
    "KrakenWsChannel",
    "KrakenWsMessageType",
    "KrakenWsMethod",
    "py_kraken_product_type_from_symbol",
]

@typing.final
class KrakenDataClientConfig:
    r"""
    Configuration for the Kraken data client.
    """
    def py_new(self, product_type: typing.Optional[KrakenProductType], environment: typing.Optional[KrakenEnvironment], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], ws_public_url: typing.Optional[builtins.str], ws_private_url: typing.Optional[builtins.str], ws_l3_url: typing.Optional[builtins.str], validate_l3_checksum: typing.Optional[builtins.bool], proxy_url: typing.Optional[builtins.str], timeout_secs: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], max_requests_per_second: typing.Optional[builtins.int]) -> KrakenDataClientConfig:
        r"""
        Configuration for the Kraken data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class KrakenDataClientFactory:
    r"""
    Factory for creating Kraken data clients.
    """
    def py_new(self) -> KrakenDataClientFactory:
        r"""
        Factory for creating Kraken data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class KrakenExecClientConfig:
    r"""
    Configuration for the Kraken execution client.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, api_key: builtins.str, api_secret: builtins.str, product_type: typing.Optional[KrakenProductType], environment: typing.Optional[KrakenEnvironment], base_url: typing.Optional[builtins.str], ws_url: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], timeout_secs: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], max_requests_per_second: typing.Optional[builtins.int], spot_account_type: typing.Optional[model.AccountType], default_leverage: typing.Optional[builtins.int], use_spot_position_reports: typing.Optional[builtins.bool], spot_positions_quote_currency: typing.Optional[builtins.str], margin_balance_asset: typing.Optional[builtins.str], use_ws_trade: typing.Optional[builtins.bool], ws_request_timeout_secs: typing.Optional[builtins.int]) -> KrakenExecClientConfig:
        r"""
        Configuration for the Kraken execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class KrakenExecutionClientFactory:
    r"""
    Factory for creating Kraken execution clients.
    """
    def py_new(self) -> KrakenExecutionClientFactory:
        r"""
        Factory for creating Kraken execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class KrakenFuturesHttpClient:
    r"""
    High-level HTTP client for the Kraken Futures REST API.
    
    This client wraps the raw client and provides Nautilus domain types.
    It maintains an instrument cache and uses it to parse venue responses
    into Nautilus domain objects.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], demo: builtins.bool, timeout_secs: builtins.int, max_retries: typing.Optional[builtins.int], retry_delay_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str], max_requests_per_second: builtins.int) -> KrakenFuturesHttpClient:
        r"""
        High-level HTTP client for the Kraken Futures REST API.
        
        This client wraps the raw client and provides Nautilus domain types.
        It maintains an instrument cache and uses it to parse venue responses
        into Nautilus domain objects.
        """
    def py_base_url(self) -> builtins.str: ...
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument for symbol lookup.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancels all pending HTTP requests.
        """
    def py_request_instruments(self) -> typing.Any:
        r"""
        Requests tradable instruments from Kraken Futures.
        """
    def py_request_instrument_statuses(self) -> typing.Any:
        r"""
        Requests the current market status for Kraken Futures instruments.
        """
    def py_request_trades(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_request_mark_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Requests the mark price for an instrument.
        """
    def py_request_index_price(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_request_book_snapshot(self, instrument_id: model.InstrumentId, depth: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests an order book snapshot for a futures instrument.
        """
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_request_account_state(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests account state from the Kraken Futures exchange.
        
        This queries the accounts endpoint and converts the response into a
        Nautilus `AccountState` event containing balances and margin info.
        """
    def py_request_order_status_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], open_only: builtins.bool) -> typing.Any: ...
    def py_request_fill_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime]) -> typing.Any: ...
    def py_request_position_status_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any: ...
    def py_submit_order(self, account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], reduce_only: builtins.bool, post_only: builtins.bool) -> typing.Any:
        r"""
        Submits a new order to the Kraken Futures exchange.
        """
    def py_modify_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Modifies an existing order on the Kraken Futures exchange.
        
        Returns the new venue order ID assigned to the modified order.
        """
    def py_cancel_order(self, account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels an order on the Kraken Futures exchange.
        """
    def py_cancel_all_orders(self, instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any: ...
    def py_cancel_orders_batch(self, venue_order_ids: typing.Sequence[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels multiple orders on the Kraken Futures exchange.
        
        Automatically chunks requests into batches of 50 orders.
        
        # Parameters
        - `venue_order_ids` - List of venue order IDs to cancel.
        
        # Returns
        The total number of successfully cancelled orders.
        """

@typing.final
class KrakenFuturesWebSocketClient:
    r"""
    WebSocket client for the Kraken Futures v1 streaming API.
    """
    def py_new(self, environment: typing.Optional[KrakenEnvironment], base_url: typing.Optional[builtins.str], heartbeat_secs: builtins.int, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str]) -> KrakenFuturesWebSocketClient:
        r"""
        WebSocket client for the Kraken Futures v1 streaming API.
        """
    def py_has_credentials(self) -> builtins.bool:
        r"""
        Returns true if the client has API credentials set.
        """
    def py_url(self) -> builtins.str:
        r"""
        Returns the WebSocket URL.
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Returns true if the connection is closed.
        """
    def py_is_active(self) -> builtins.bool:
        r"""
        Returns true if the connection is active.
        """
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any:
        r"""
        Waits until the WebSocket connection is active or timeout.
        """
    def py_is_authenticated(self) -> builtins.bool:
        r"""
        Returns true if the WebSocket is authenticated for private feeds.
        """
    def py_wait_until_authenticated(self, timeout_secs: builtins.float) -> typing.Any:
        r"""
        Waits until the WebSocket is authenticated or the timeout elapses.
        
        Returns an error on timeout or explicit auth failure.
        """
    def py_authenticate(self) -> typing.Any:
        r"""
        Authenticates the WebSocket connection for private feeds.
        
        Sends a challenge request and waits for the handler to parse the response,
        sign it, and mark the `AuthTracker` successful. Private subscriptions gate
        on the stored challenge / signed-challenge pair.
        """
    def py_connect(self, loop_: typing.Any, instruments: typing.Sequence[typing.Any], callback: typing.Any) -> typing.Any:
        r"""
        Connects to the WebSocket server.
        """
    def py_set_account_id(self, account_id: model.AccountId) -> None:
        r"""
        Sets the account ID for execution report parsing.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument for execution report parsing.
        """
    def py_cache_instruments(self, instruments: typing.Sequence[typing.Any]) -> None:
        r"""
        Caches multiple instruments for execution report parsing.
        """
    def py_cache_client_order(self, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId], instrument_id: model.InstrumentId, trader_id: model.TraderId, strategy_id: model.StrategyId) -> None:
        r"""
        Caches a client order for truncated ID resolution and instrument lookup.
        
        Kraken Futures limits client order IDs to 18 characters, so orders with
        longer IDs are truncated. This method stores the mapping from truncated
        to full ID, and from venue order ID to instrument ID for cancel messages.
        """
    def py_disconnect(self) -> typing.Any:
        r"""
        Disconnects from the WebSocket server.
        """
    def py_close(self) -> typing.Any:
        r"""
        Closes the WebSocket connection.
        """
    def py_subscribe_book(self, instrument_id: model.InstrumentId, depth: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Subscribes to order book updates for the given instrument.
        
        Note: The `depth` parameter is accepted for API compatibility with spot client but is
        not used by Kraken Futures (full book is always returned).
        """
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to quote updates for the given instrument.
        
        Uses the order book channel for low-latency top-of-book quotes.
        """
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to trade updates for the given instrument.
        """
    def py_subscribe_mark_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to mark price updates for the given instrument.
        """
    def py_subscribe_index_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to index price updates for the given instrument.
        """
    def py_subscribe_funding_rate(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to funding rate updates for the given instrument.
        """
    def py_unsubscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from order book updates for the given instrument.
        """
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from quote updates for the given instrument.
        """
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from trade updates for the given instrument.
        """
    def py_unsubscribe_mark_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from mark price updates for the given instrument.
        """
    def py_unsubscribe_index_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from index price updates for the given instrument.
        """
    def py_unsubscribe_funding_rate(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from funding rate updates for the given instrument.
        """
    def py_sign_challenge(self, challenge: builtins.str) -> builtins.str:
        r"""
        Sign a challenge with the API credentials.
        
        Returns the signed challenge on success.
        """
    def py_authenticate_with_challenge(self, challenge: builtins.str) -> typing.Any:
        r"""
        Complete authentication with a received challenge.
        """
    def py_set_auth_credentials(self, original_challenge: builtins.str, signed_challenge: builtins.str) -> typing.Any:
        r"""
        Set authentication credentials directly (for when challenge is obtained externally).
        """
    def py_subscribe_open_orders(self) -> typing.Any:
        r"""
        Subscribes to open orders feed (private, requires authentication).
        """
    def py_subscribe_fills(self) -> typing.Any:
        r"""
        Subscribes to fills feed (private, requires authentication).
        """
    def py_subscribe_executions(self) -> typing.Any:
        r"""
        Subscribes to both open orders and fills (convenience method).
        """

@typing.final
class KrakenSpotHttpClient:
    r"""
    High-level HTTP client for the Kraken Spot REST API.
    
    This client wraps the raw client and provides Nautilus domain types.
    It maintains an instrument cache and uses it to parse venue responses
    into Nautilus domain objects.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], timeout_secs: builtins.int, max_retries: typing.Optional[builtins.int], retry_delay_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str], max_requests_per_second: builtins.int) -> KrakenSpotHttpClient:
        r"""
        High-level HTTP client for the Kraken Spot REST API.
        
        This client wraps the raw client and provides Nautilus domain types.
        It maintains an instrument cache and uses it to parse venue responses
        into Nautilus domain objects.
        """
    def py_base_url(self) -> builtins.str: ...
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument for symbol lookup.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancels all pending HTTP requests.
        """
    def py_get_server_time(self) -> typing.Any: ...
    def py_request_instruments(self, pairs: typing.Optional[typing.Sequence[builtins.str]]) -> typing.Any:
        r"""
        Requests tradable instruments from Kraken.
        
        When `pairs` is `None` (loading all), also fetches tokenized asset pairs
        (xStocks) and merges them with the default currency pairs.
        """
    def py_request_instrument_statuses(self, pairs: typing.Optional[typing.Sequence[builtins.str]]) -> typing.Any:
        r"""
        Requests the current market status for Kraken Spot instruments.
        
        Fetches both regular and tokenized asset pairs. The call returns an error if
        either fetch fails so callers can avoid emitting partial snapshots that would
        otherwise cause the missing tokenized symbols to be diffed as removed.
        """
    def py_request_trades(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests historical trades for an instrument.
        """
    def py_request_book_snapshot(self, instrument_id: model.InstrumentId, depth: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests an order book snapshot for an instrument.
        """
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests historical bars/OHLC data for an instrument.
        """
    def py_request_account_state(self, account_id: model.AccountId, account_type: model.AccountType, margin_balance_asset: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests account state (balances) from Kraken.
        
        In cash mode returns wallet balances only.
        In margin mode additionally calls `TradeBalance` to build `MarginBalance` entries.
        `margin_balance_asset` selects the summary-display denomination for `TradeBalance`
        (e.g. `"ZUSD"`, `"ZGBP"`); `None` lets Kraken default to `ZUSD`.
        
        Callers that also need the `TradeBalance` metrics dictionary should use
        `Self.request_account_state_with_metrics` to avoid issuing two `TradeBalance`
        HTTP requests per account update.
        """
    def py_request_margin_metrics(self, asset: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Returns a flattened snapshot of Kraken's `TradeBalance` margin metrics.
        
        Caller is expected to invoke this only when operating in margin mode; consumers
        surface the values via `AccountState.info` (Python-side) for strategy access.
        Strings preserve venue precision exactly. Keys: `equivalent_balance`,
        `trade_balance`, `used_margin`, `unexecuted_value`, `unrealized_pnl`,
        `cost_basis`, `valuation`, `equity`, `free_margin`, `margin_level` (omitted
        when Kraken returns no value, i.e. no open positions), `asset`.
        
        When the metrics are needed alongside the `AccountState`, prefer
        `Self.request_account_state_with_metrics` to share a single `TradeBalance`
        HTTP request between both.
        """
    def py_request_account_state_with_metrics(self, account_id: model.AccountId, account_type: model.AccountType, margin_balance_asset: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests the full margin account snapshot in a single round-trip.
        
        Returns the `AccountState` (including `MarginBalance` entries when
        `account_type` is `Margin`) and the `TradeBalance` metrics dictionary that
        callers attach to `AccountState.info`. In cash mode the metrics map is empty
        and `TradeBalance` is not called.
        
        In margin mode, replaces the raw `margin_balance_asset` wallet with a
        synthetic `AccountBalance` using `total = e` and `free = mf` from
        `TradeBalance`. Kraken reports these values across all collateral, which
        avoids clamping free margin to one wallet bucket in multi-asset accounts.
        
        The single shared fetch keeps Kraken rate-limit usage symmetric with `Balance`
        (one request per account update), instead of two as if `request_account_state`
        and `request_margin_metrics` were called in sequence.
        """
    def py_request_order_status_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], open_only: builtins.bool) -> typing.Any:
        r"""
        Requests order status reports from Kraken.
        """
    def py_request_fill_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime]) -> typing.Any:
        r"""
        Requests fill/trade reports from Kraken.
        """
    def py_request_position_status_reports(self, account_id: model.AccountId, instrument_id: typing.Optional[model.InstrumentId], account_type: model.AccountType, use_spot_position_reports: builtins.bool, quote_currency: builtins.str) -> typing.Any:
        r"""
        Requests position status reports for SPOT instruments.
        
        In margin mode: calls `OpenPositions` and returns reports for each open leveraged position.
        When `use_spot_position_reports` is enabled (cash mode): derives reports from wallet balances.
        Otherwise returns an empty vector.
        """
    def py_submit_order(self, account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, expire_time: typing.Optional[builtins.int], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], trailing_offset: typing.Optional[builtins.str], limit_offset: typing.Optional[builtins.str], reduce_only: builtins.bool, post_only: builtins.bool, quote_quantity: builtins.bool, display_qty: typing.Optional[model.Quantity], leverage: typing.Optional[builtins.int], account_type: model.AccountType) -> typing.Any:
        r"""
        Submits a new order to the Kraken Spot exchange.
        
        Returns the venue order ID on success. WebSocket handles all execution events.
        """
    def py_cancel_order(self, account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels an order on the Kraken Spot exchange.
        """
    def py_cancel_all_orders(self) -> typing.Any: ...
    def py_cancel_orders_batch(self, venue_order_ids: typing.Sequence[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels multiple orders on the Kraken Spot exchange (batched, max 50 per request).
        """
    def py_modify_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Modifies an existing order on the Kraken Spot exchange using atomic amend.
        
        Uses the AmendOrder endpoint which modifies the order in-place,
        keeping the same order ID and queue position.
        """

@typing.final
class KrakenSpotWebSocketClient:
    r"""
    WebSocket client for the Kraken Spot v2 streaming API.
    """
    def py_new(self, environment: typing.Optional[KrakenEnvironment], private: builtins.bool, base_url: typing.Optional[builtins.str], heartbeat_secs: typing.Optional[builtins.int], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], l3: builtins.bool, validate_l3_checksum: builtins.bool, base_url_http: typing.Optional[builtins.str]) -> KrakenSpotWebSocketClient:
        r"""
        WebSocket client for the Kraken Spot v2 streaming API.
        """
    def py_url(self) -> builtins.str:
        r"""
        Returns the WebSocket URL.
        """
    def py_has_credentials(self) -> builtins.bool:
        r"""
        Returns `true` if the client has API credentials configured
        (post-environment-variable resolution).
        """
    def py_is_connected(self) -> builtins.bool:
        r"""
        Returns true if connected (not closed).
        """
    def py_is_active(self) -> builtins.bool:
        r"""
        Returns true if the connection is active.
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Returns true if the connection is closed.
        """
    def py_get_subscriptions(self) -> builtins.list[builtins.str]:
        r"""
        Returns all active subscriptions.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancels all pending requests.
        """
    def py_connect(self, loop_: typing.Any, instruments: typing.Sequence[typing.Any], callback: typing.Any) -> typing.Any:
        r"""
        Connects to the WebSocket server.
        """
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any:
        r"""
        Waits until the connection is active or timeout.
        """
    def py_authenticate(self) -> typing.Any:
        r"""
        Authenticates with the Kraken API to enable private subscriptions.
        """
    def py_is_authenticated(self) -> builtins.bool:
        r"""
        Returns true if the WebSocket is authenticated for private subscriptions.
        """
    def py_wait_until_authenticated(self, timeout_secs: builtins.float) -> typing.Any:
        r"""
        Waits until the WebSocket is authenticated or the timeout elapses.
        
        Returns an error on timeout or explicit auth failure.
        """
    def py_disconnect(self) -> typing.Any:
        r"""
        Disconnects from the WebSocket server.
        """
    def py_send_ping(self) -> typing.Any:
        r"""
        Sends a ping message to keep the connection alive.
        """
    def py_close(self) -> typing.Any:
        r"""
        Closes the WebSocket connection.
        """
    def py_set_account_id(self, account_id: model.AccountId) -> None:
        r"""
        Sets the account ID for execution report parsing.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument for execution report parsing.
        """
    def py_cache_client_order(self, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId], instrument_id: model.InstrumentId, trader_id: model.TraderId, strategy_id: model.StrategyId) -> None:
        r"""
        Caches a client order for truncated ID resolution.
        """
    def py_subscribe_book(self, instrument_id: model.InstrumentId, depth: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Subscribes to order book updates for the given instrument.
        """
    def py_subscribe_l3_book(self, symbol: builtins.str, depth: builtins.int) -> typing.Any:
        r"""
        Subscribes to the Kraken `level3` channel for the given symbol.
        
        `depth` must be 10, 100, or 1000.
        
        # Errors
        
        Returns an error if the auth token is not cached (call `authenticate()` first)
        or the subscribe message cannot be sent.
        """
    def py_unsubscribe_l3_book(self, symbol: builtins.str) -> typing.Any:
        r"""
        Unsubscribes from the Kraken `level3` channel for the given symbol.
        """
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to quote updates for the given instrument.
        
        Uses the Ticker channel with `event_trigger: "bbo"` for updates only on
        best bid/offer changes.
        """
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to trade updates for the given instrument.
        """
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Subscribes to bar/OHLC updates for the given bar type.
        """
    def py_subscribe_executions(self, snap_orders: builtins.bool, snap_trades: builtins.bool) -> typing.Any:
        r"""
        Subscribes to execution updates (order and fill events).
        
        Requires authentication - call `authenticate()` first.
        """
    def py_unsubscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from order book updates for the given instrument.
        """
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from quote updates for the given instrument.
        """
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from trade updates for the given instrument.
        """
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Unsubscribes from bar/OHLC updates for the given bar type.
        """

@typing.final
class KrakenApiResult(enum.Enum):
    r"""
    Kraken API result status.
    """
    Success = ...
    Error = ...

@typing.final
class KrakenAssetClass(enum.Enum):
    r"""
    Kraken asset class.
    """
    Currency = ...
    TokenizedAsset = ...

@typing.final
class KrakenEnvironment(enum.Enum):
    r"""
    Kraken API environment (live or demo).
    """
    Live = ...
    Demo = ...

@typing.final
class KrakenFillType(enum.Enum):
    r"""
    Kraken fill type (maker or taker).
    """
    Maker = ...
    Taker = ...

@typing.final
class KrakenFuturesOrderStatus(enum.Enum):
    r"""
    Kraken futures order status.
    """
    Untouched = ...
    PartiallyFilled = ...
    Filled = ...
    Cancelled = ...
    Expired = ...

@typing.final
class KrakenFuturesOrderType(enum.Enum):
    r"""
    Kraken futures order type.
    """
    Limit = ...
    Ioc = ...
    Post = ...
    Market = ...
    Stop = ...
    StopLower = ...
    TakeProfit = ...
    StopLoss = ...
    Unknown = ...

@typing.final
class KrakenInstrumentType(enum.Enum):
    r"""
    Kraken futures instrument type.
    """
    FuturesInverse = ...
    r"""
    Inverse perpetual futures (e.g., PI_XBTUSD).
    """
    FlexibleFutures = ...
    r"""
    Flexible/linear perpetual futures (e.g., PF_XBTUSD).
    """

@typing.final
class KrakenOrderSide(enum.Enum):
    r"""
    Kraken order side (buy or sell).
    """
    Buy = ...
    Sell = ...

@typing.final
class KrakenOrderStatus(enum.Enum):
    r"""
    Kraken order status.
    """
    Pending = ...
    Open = ...
    Closed = ...
    Canceled = ...
    Expired = ...

@typing.final
class KrakenOrderType(enum.Enum):
    r"""
    Kraken spot order type.
    """
    Market = ...
    Limit = ...
    StopLoss = ...
    TakeProfit = ...
    StopLossLimit = ...
    TakeProfitLimit = ...
    TrailingStop = ...
    TrailingStopLimit = ...
    SettlePosition = ...

@typing.final
class KrakenPairStatus(enum.Enum):
    r"""
    Kraken trading pair status.
    """
    Online = ...
    CancelOnly = ...
    PostOnly = ...
    LimitOnly = ...
    ReduceOnly = ...

@typing.final
class KrakenPositionSide(enum.Enum):
    r"""
    Kraken position side (long or short).
    """
    Long = ...
    Short = ...

@typing.final
class KrakenProductType(enum.Enum):
    r"""
    Kraken product type (spot or futures).
    """
    Spot = ...
    Futures = ...

@typing.final
class KrakenSendStatus(enum.Enum):
    r"""
    Kraken futures send order status.
    """
    Placed = ...
    r"""
    Order was successfully placed.
    """
    Cancelled = ...
    r"""
    Order was cancelled.
    """
    Edited = ...
    r"""
    Order was edited.
    """
    NotFound = ...
    r"""
    Order not found.
    """
    NoOrdersToCancel = ...
    r"""
    No orders matched the cancel-all request.
    
    Returned by the Kraken Futures `cancelallorders` endpoint as the
    `cancelStatus.status` field. The accompanying `cancelledOrders` array
    may still be populated for orders that were canceled in the same call,
    so callers must inspect that array rather than treating this status
    as an error.
    """
    InsufficientAvailableFunds = ...
    r"""
    Insufficient available funds.
    """
    InvalidOrderType = ...
    r"""
    Invalid order type.
    """
    InvalidSize = ...
    r"""
    Invalid size.
    """
    WouldCauseLiquidation = ...
    r"""
    Would cause liquidation.
    """
    PostWouldExecute = ...
    r"""
    Post-only order would have crossed.
    """
    ReduceOnlyWouldIncreasePosition = ...
    r"""
    Reduce-only order would increase position.
    """

@typing.final
class KrakenSpotTrigger(enum.Enum):
    r"""
    Trigger reference price for Kraken spot conditional orders.
    """
    Last = ...
    r"""
    Last traded price in the order book.
    """
    Index = ...
    r"""
    Index price for the broader market.
    """

@typing.final
class KrakenSystemStatus(enum.Enum):
    r"""
    Kraken system status.
    """
    Online = ...
    Maintenance = ...
    CancelOnly = ...
    PostOnly = ...

@typing.final
class KrakenTimeInForce(enum.Enum):
    r"""
    Kraken time-in-force for orders.
    """
    ImmediateOrCancel = ...
    FillOrKill = ...
    GoodTilCancelled = ...
    GoodTilDate = ...

@typing.final
class KrakenTriggerSide(enum.Enum):
    r"""
    Kraken futures trigger side for conditional orders.
    """
    TriggerAbove = ...
    r"""
    Trigger when price goes above the trigger price.
    """
    TriggerBelow = ...
    r"""
    Trigger when price goes below the trigger price.
    """
    Unknown = ...
    r"""
    The venue's `"unknown"` sentinel, carrying no directional intent.
    """

@typing.final
class KrakenTriggerSignal(enum.Enum):
    r"""
    Kraken futures trigger signal type.
    """
    Last = ...
    Mark = ...
    Index = ...
    Unknown = ...

@typing.final
class KrakenWsChannel(enum.Enum):
    Ticker = ...
    Trade = ...
    Book = ...
    Ohlc = ...
    Spread = ...
    Executions = ...
    Balances = ...
    Level3 = ...

@typing.final
class KrakenWsMessageType(enum.Enum):
    Heartbeat = ...
    Status = ...
    Subscribe = ...
    Unsubscribe = ...
    Update = ...
    Snapshot = ...
    Error = ...

@typing.final
class KrakenWsMethod(enum.Enum):
    Subscribe = ...
    Unsubscribe = ...
    Ping = ...
    Pong = ...
    AddOrder = ...
    AmendOrder = ...
    CancelOrder = ...
    BatchAdd = ...

def py_kraken_product_type_from_symbol(symbol: builtins.str) -> KrakenProductType:
    r"""
    Determines the product type from a Kraken symbol.
    
    Futures symbols have the following prefixes:
    - `PI_` - Perpetual Inverse futures (e.g., `PI_XBTUSD`)
    - `PF_` - Perpetual Fixed-margin futures (e.g., `PF_XBTUSD`)
    - `FI_` - Fixed maturity Inverse futures (e.g., `FI_XBTUSD_230929`)
    - `FF_` - Flex futures
    
    All other symbols are considered spot.
    """

