# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from nautilus_trader import model
import typing
__all__ = [
    "get_arrow_schema_map",
    "py_bars_to_arrow_record_batch_bytes",
    "py_book_deltas_to_arrow_record_batch_bytes",
    "py_book_depth10_to_arrow_record_batch_bytes",
    "py_index_prices_to_arrow_record_batch_bytes",
    "py_instrument_closes_to_arrow_record_batch_bytes",
    "py_instrument_status_from_arrow_record_batch_bytes",
    "py_instrument_status_to_arrow_record_batch_bytes",
    "py_mark_prices_to_arrow_record_batch_bytes",
    "py_option_greeks_from_arrow_record_batch_bytes",
    "py_option_greeks_to_arrow_record_batch_bytes",
    "py_quotes_to_arrow_record_batch_bytes",
    "py_trades_to_arrow_record_batch_bytes",
    "pyobjects_to_arrow_record_batch_bytes",
]

def get_arrow_schema_map(cls: type) -> typing.Any:
    r"""
    Returns a mapping from field names to Arrow data types for the given Rust data class.
    
    # Errors
    
    Returns a `PyErr` if the class name is not recognized or schema extraction fails.
    """

def py_bars_to_arrow_record_batch_bytes(data: typing.Sequence[model.Bar]) -> bytes:
    r"""
    Converts a list of `Bar` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_book_deltas_to_arrow_record_batch_bytes(data: typing.Sequence[model.OrderBookDelta]) -> bytes:
    r"""
    Converts a list of `OrderBookDelta` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_book_depth10_to_arrow_record_batch_bytes(data: typing.Sequence[model.OrderBookDepth10]) -> bytes:
    r"""
    Converts a list of `OrderBookDepth10` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_index_prices_to_arrow_record_batch_bytes(data: typing.Sequence[model.IndexPriceUpdate]) -> bytes:
    r"""
    Converts a list of `IndexPriceUpdate` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_instrument_closes_to_arrow_record_batch_bytes(data: typing.Sequence[model.InstrumentClose]) -> bytes:
    r"""
    Converts a list of `InstrumentClose` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_instrument_status_from_arrow_record_batch_bytes(data: typing.Sequence[builtins.int]) -> builtins.list[model.InstrumentStatus]:
    r"""
    Decodes Arrow IPC bytes into a list of `InstrumentStatus`.
    
    # Errors
    
    Returns a `PyErr` if decoding fails.
    """

def py_instrument_status_to_arrow_record_batch_bytes(data: typing.Sequence[model.InstrumentStatus]) -> bytes:
    r"""
    Converts a list of `InstrumentStatus` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_mark_prices_to_arrow_record_batch_bytes(data: typing.Sequence[model.MarkPriceUpdate]) -> bytes:
    r"""
    Converts a list of `MarkPriceUpdate` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_option_greeks_from_arrow_record_batch_bytes(data: typing.Sequence[builtins.int]) -> builtins.list[model.OptionGreeks]:
    r"""
    Decodes Arrow IPC bytes into a list of `OptionGreeks`.
    
    # Errors
    
    Returns a `PyErr` if decoding fails.
    """

def py_option_greeks_to_arrow_record_batch_bytes(data: typing.Sequence[model.OptionGreeks]) -> bytes:
    r"""
    Converts a list of `OptionGreeks` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_quotes_to_arrow_record_batch_bytes(data: typing.Sequence[model.QuoteTick]) -> bytes:
    r"""
    Converts a list of `QuoteTick` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def py_trades_to_arrow_record_batch_bytes(data: typing.Sequence[model.TradeTick]) -> bytes:
    r"""
    Converts a list of `TradeTick` into Arrow IPC bytes for Python.
    
    # Errors
    
    Returns a `PyErr` if encoding fails.
    """

def pyobjects_to_arrow_record_batch_bytes(data: typing.Sequence[typing.Any]) -> bytes:
    r"""
    Converts a vector of `OrderBookDelta` into an Arrow `RecordBatch`.
    """

