# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
import enum
from nautilus_trader import model
import typing
__all__ = [
    "DeriveDataClientConfig",
    "DeriveDataClientFactory",
    "DeriveEnvironment",
    "DeriveExecClientConfig",
    "DeriveExecFactoryConfig",
    "DeriveExecutionClientFactory",
]

@typing.final
class DeriveDataClientConfig:
    r"""
    Configuration for the Derive data client.
    """
    def py_new(self, base_url_rest: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[DeriveEnvironment], http_timeout_secs: typing.Optional[builtins.int], ws_timeout_secs: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], currencies: typing.Optional[typing.Sequence[builtins.str]], include_expired: typing.Optional[builtins.bool], auto_load_missing_instruments: typing.Optional[builtins.bool]) -> DeriveDataClientConfig:
        r"""
        Configuration for the Derive live data client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeriveDataClientFactory:
    r"""
    Factory for creating Derive data clients.
    """
    def py_new(self) -> DeriveDataClientFactory:
        r"""
        Factory for creating Derive data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class DeriveExecClientConfig:
    r"""
    Configuration for the Derive execution client.
    
    `Debug` is implemented manually so that `session_key` is redacted; the
    derived `Debug` would leak the raw secret through any logger or Python
    `__repr__`.
    """
    def py_new(self, wallet_address: typing.Optional[builtins.str], session_key: typing.Optional[builtins.str], subaccount_id: typing.Optional[builtins.int], base_url_rest: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[DeriveEnvironment], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], max_fee_per_contract: typing.Optional[decimal.Decimal], domain_separator: typing.Optional[builtins.str], action_typehash: typing.Optional[builtins.str], trade_module_address: typing.Optional[builtins.str], signature_expiry_secs: typing.Optional[builtins.int], market_order_slippage_bps: typing.Optional[builtins.int], max_matching_requests_per_second: typing.Optional[builtins.int]) -> DeriveExecClientConfig:
        r"""
        Configuration for the Derive live execution client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeriveExecFactoryConfig:
    r"""
    Configuration for creating Derive execution clients via factory.
    
    Bundles the trader and account identifiers required by
    [`ExecutionClientCore`] alongside the underlying execution client config.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, config: DeriveExecClientConfig) -> DeriveExecFactoryConfig:
        r"""
        Configuration for creating Derive execution clients via factory.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DeriveExecutionClientFactory:
    r"""
    Factory for creating Derive execution clients.
    """
    def py_new(self) -> DeriveExecutionClientFactory:
        r"""
        Factory for creating Derive execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class DeriveEnvironment(enum.Enum):
    r"""
    Derive network selector. Drives REST/WS URLs and per-network protocol
    constants (`DOMAIN_SEPARATOR`, module addresses).
    """
    Mainnet = ...
    r"""
    Production environment.
    """
    Testnet = ...
    r"""
    Public testnet environment.
    """

