# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import enum
from nautilus_trader import model
import typing
__all__ = [
    "OKXBalanceDetail",
    "OKXContractType",
    "OKXDataClientConfig",
    "OKXDataClientFactory",
    "OKXEndpointType",
    "OKXEnvironment",
    "OKXExecClientConfig",
    "OKXExecutionClientFactory",
    "OKXGreeksType",
    "OKXHttpClient",
    "OKXInstrumentType",
    "OKXMarginMode",
    "OKXOrderStatus",
    "OKXPositionMode",
    "OKXTradeMode",
    "OKXVipLevel",
    "OKXWebSocketClient",
    "OKXWebSocketError",
    "derive_okx_ws_url",
    "get_okx_http_base_url",
    "get_okx_ws_url_business",
    "get_okx_ws_url_private",
    "get_okx_ws_url_public",
    "okx_requires_authentication",
]

@typing.final
class OKXBalanceDetail:
    r"""
    Represents a balance detail for a single currency in an OKX account.
    """
    def ccy(self) -> builtins.str: ...
    def cash_bal(self) -> builtins.str: ...
    def liab(self) -> builtins.str: ...

@typing.final
class OKXDataClientConfig:
    r"""
    Configuration for the OKX data client.
    """
    def py_new(self, instrument_types: typing.Optional[typing.Sequence[OKXInstrumentType]], environment: typing.Optional[OKXEnvironment], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], api_passphrase: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws_public: typing.Optional[builtins.str], base_url_ws_business: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], vip_level: typing.Optional[OKXVipLevel], load_spreads: builtins.bool) -> OKXDataClientConfig:
        r"""
        Configuration for the OKX data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class OKXDataClientFactory:
    r"""
    Factory for creating OKX data clients.
    """
    def py_new(self) -> OKXDataClientFactory:
        r"""
        Factory for creating OKX data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class OKXExecClientConfig:
    r"""
    Configuration for the OKX execution client.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, instrument_types: typing.Optional[typing.Sequence[OKXInstrumentType]], environment: typing.Optional[OKXEnvironment], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], api_passphrase: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws_private: typing.Optional[builtins.str], base_url_ws_business: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], margin_mode: typing.Optional[OKXMarginMode], load_spreads: builtins.bool) -> OKXExecClientConfig:
        r"""
        Configuration for the OKX execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class OKXExecutionClientFactory:
    r"""
    Factory for creating OKX execution clients.
    """
    def py_new(self) -> OKXExecutionClientFactory:
        r"""
        Factory for creating OKX execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class OKXHttpClient:
    r"""
    Provides a higher-level HTTP client for the [OKX](https://okx.com) REST API.
    
    This client wraps the underlying `OKXHttpInnerClient` to handle conversions
    into the Nautilus domain model.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], api_passphrase: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, environment: OKXEnvironment, proxy_url: typing.Optional[builtins.str]) -> OKXHttpClient:
        r"""
        Provides a higher-level HTTP client for the [OKX](https://okx.com) REST API.
        
        This client wraps the underlying `OKXHttpInnerClient` to handle conversions
        into the Nautilus domain model.
        """
    def py_from_env(self) -> OKXHttpClient:
        r"""
        Creates a new authenticated `OKXHttpClient` using environment variables and
        the default OKX HTTP base url.
        
        # Errors
        
        Returns an error if the operation fails.
        """
    def py_base_url(self) -> builtins.str:
        r"""
        Returns the base url being used by the client.
        """
    def py_api_key(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the public API key being used by the client.
        """
    def py_api_key_masked(self) -> typing.Optional[builtins.str]:
        r"""
        Returns a masked version of the API key for logging purposes.
        """
    def py_is_initialized(self) -> builtins.bool:
        r"""
        Checks if the client is initialized.
        
        The client is considered initialized if any instruments have been cached from the venue.
        """
    def py_get_cached_symbols(self) -> builtins.list[builtins.str]:
        r"""
        Returns a snapshot of all instrument symbols currently held in the
        internal cache.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancel all pending HTTP requests.
        """
    def py_cache_instruments(self, instruments: typing.Sequence[typing.Any]) -> None:
        r"""
        Caches multiple instruments.
        
        Any existing instruments with the same symbols will be replaced.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches a single instrument.
        
        Any existing instrument with the same symbol will be replaced.
        """
    def py_set_position_mode(self, position_mode: OKXPositionMode) -> typing.Any:
        r"""
        Sets the position mode for the account.
        
        Defaults to NetMode if no position mode is provided.
        
        # Note
        
        This endpoint only works for accounts with derivatives trading enabled.
        If the account only has spot trading, this will return an error.
        """
    def py_request_instruments(self, instrument_type: OKXInstrumentType, instrument_family: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests all instruments for the `instrument_type` from OKX.
        
        # Returns
        
        A tuple containing:
        - `Vec<InstrumentAny>`: The parsed instruments
        - `Vec<(Ustr, u64)>`: Mappings of inst_id to inst_id_code for WebSocket order operations
        """
    def py_request_spread_instruments(self, base_currency: typing.Optional[builtins.str], instrument_id: typing.Optional[model.InstrumentId], spread_id: typing.Optional[builtins.str], state: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests spread instruments from OKX.
        """
    def py_request_instrument(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Requests a single instrument by `instrument_id` from OKX.
        
        Fetches the instrument from the API, caches it, and returns it.
        """
    def py_request_event_contract_series(self, series_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests event contract series metadata from OKX.
        """
    def py_request_event_contract_events(self, series_id: builtins.str, event_id: typing.Optional[builtins.str], state: typing.Optional[builtins.str], limit: typing.Optional[builtins.str], before: typing.Optional[builtins.str], after: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests event metadata for an event contract series from OKX.
        """
    def py_request_event_contract_markets(self, series_id: builtins.str, event_id: typing.Optional[builtins.str], inst_id: typing.Optional[builtins.str], state: typing.Optional[builtins.str], limit: typing.Optional[builtins.str], before: typing.Optional[builtins.str], after: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests event contract market metadata from OKX.
        """
    def py_request_account_state(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests the account state for the `account_id` from OKX.
        """
    def py_request_trades(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests trades for the `instrument_id` and `start` -> `end` time range.
        """
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests historical bars for the given bar type and time range.
        
        The aggregation source must be `EXTERNAL`. Time range validation ensures start < end.
        Returns bars sorted oldest to newest.
        
        # Endpoint Selection
        
        The OKX API has different endpoints with different limits:
        - Regular endpoint (`/api/v5/market/candles`): ≤ 300 rows/call, ≤ 40 req/2s
          - Used when: start is None OR age ≤ 100 days
        - History endpoint (`/api/v5/market/history-candles`): ≤ 100 rows/call, ≤ 20 req/2s
          - Used when: start is Some AND age > 100 days
        
        Age is calculated as `Utc::now() - start` at the time of the first request.
        
        # Supported Aggregations
        
        Maps to OKX bar query parameter:
        - `Second` → `{n}s`
        - `Minute` → `{n}m`
        - `Hour` → `{n}H`
        - `Day` → `{n}D`
        - `Week` → `{n}W`
        - `Month` → `{n}M`
        
        # Pagination
        
        - Uses `before` parameter for backwards pagination
        - Pages backwards from end time (or now) to start time
        - Stops when: limit reached, time window covered, or API returns empty
        - Rate limit safety: ≥ 50ms between requests
        
        # References
        
        - <https://tr.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks>
        - <https://tr.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks-history>
        """
    def py_request_orderbook_snapshot(self, instrument_id: model.InstrumentId, depth: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests an order book snapshot as `OrderBookDeltas` for the `instrument_id`.
        """
    def py_request_funding_rates(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests historical funding rates for the `instrument_id`.
        """
    def py_request_forward_prices(self, underlying: builtins.str, instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any:
        r"""
        Requests forward prices for OKX options using the option summary endpoint.
        """
    def py_request_mark_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Requests the latest mark price for the `instrument_type` from OKX.
        """
    def py_request_index_price(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Requests the latest index price for the `instrument_id` from OKX.
        """
    def py_request_order_status_reports(self, account_id: model.AccountId, instrument_type: typing.Optional[OKXInstrumentType], instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], open_only: builtins.bool, limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests historical order status reports for the given parameters.
        
        # References
        
        - <https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-order-history-last-7-days>.
        - <https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-order-history-last-3-months>.
        """
    def py_request_algo_order_status_reports(self, account_id: model.AccountId, instrument_type: typing.Optional[OKXInstrumentType], instrument_id: typing.Optional[model.InstrumentId], algo_id: typing.Optional[builtins.str], algo_client_order_id: typing.Optional[model.ClientOrderId], state: typing.Optional[OKXOrderStatus], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests algo order status reports.
        """
    def py_request_algo_order_status_report(self, account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId) -> typing.Any:
        r"""
        Requests an algo order status report by client order identifier.
        """
    def py_request_fill_reports(self, account_id: model.AccountId, instrument_type: typing.Optional[OKXInstrumentType], instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Requests fill reports (transaction details) for the given parameters.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-trade-get-transaction-details-last-3-days>.
        """
    def py_request_position_status_reports(self, account_id: model.AccountId, instrument_type: typing.Optional[OKXInstrumentType], instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any:
        r"""
        Requests current position status reports for the given parameters.
        
        # Position Modes
        
        OKX supports two position modes, which affects how position data is returned:
        
        ## Net Mode (One-way)
        - `posSide` field will be `"net"`
        - `pos` field uses **signed quantities**:
          - Positive value = Long position
          - Negative value = Short position
          - Zero = Flat/no position
        
        ## Long/Short Mode (Hedge/Dual-side)
        - `posSide` field will be `"long"` or `"short"`
        - `pos` field is **always positive** (use `posSide` to determine actual side)
        - Allows holding simultaneous long and short positions on the same instrument
        - Position IDs are suffixed with `-LONG` or `-SHORT` for uniqueness
        
        # References
        
        <https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-positions>
        """
    def py_place_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, td_mode: OKXTradeMode, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: typing.Optional[model.TimeInForce], price: typing.Optional[model.Price], post_only: typing.Optional[builtins.bool], reduce_only: typing.Optional[builtins.bool], quote_quantity: typing.Optional[builtins.bool], position_side: typing.Optional[model.PositionSide], attach_algo_ords: typing.Optional[typing.Sequence[dict]], px_usd: typing.Optional[builtins.str], px_vol: typing.Optional[builtins.str], speed_bump: typing.Optional[builtins.str], outcome: typing.Optional[builtins.str], slippage_pct: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Places a regular order via HTTP.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-trade-post-place-order>
        """
    def py_place_algo_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, td_mode: OKXTradeMode, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], limit_price: typing.Optional[model.Price], reduce_only: typing.Optional[builtins.bool], close_fraction: typing.Optional[builtins.str], callback_ratio: typing.Optional[builtins.str], callback_spread: typing.Optional[builtins.str], activation_price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Places an algo order via HTTP.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-algo-trading-post-place-algo-order>
        """
    def py_cancel_algo_order(self, instrument_id: model.InstrumentId, algo_id: builtins.str) -> typing.Any:
        r"""
        Cancels an algo order via HTTP.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-algo-trading-post-cancel-algo-order>
        """
    def py_cancel_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels an order via HTTP, routing spread instruments to the spread endpoint.
        """
    def py_cancel_all_orders(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Cancels all open orders for an instrument via HTTP.
        """
    def py_amend_algo_order(self, instrument_id: model.InstrumentId, algo_id: builtins.str, new_trigger_price: typing.Optional[model.Price], new_limit_price: typing.Optional[model.Price], new_quantity: typing.Optional[model.Quantity], new_callback_ratio: typing.Optional[builtins.str], new_callback_spread: typing.Optional[builtins.str], new_activation_price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Amends an algo order via HTTP.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-algo-trading-post-amend-algo-order>
        """
    def py_cancel_algo_orders(self, orders: typing.Sequence[tuple[model.InstrumentId, builtins.str]]) -> typing.Any:
        r"""
        Cancels multiple algo orders via HTTP in a single request.
        
        Items with non-zero `sCode` are logged as warnings but do not
        fail the entire batch.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#order-book-trading-algo-trading-post-cancel-algo-order>
        """
    def py_cancel_advance_algo_order(self, instrument_id: model.InstrumentId, algo_id: builtins.str) -> typing.Any: ...
    def py_get_server_time(self) -> typing.Any:
        r"""
        Requests the current server time from OKX.
        
        Returns the OKX system time as a Unix timestamp in milliseconds.
        
        # Errors
        
        Returns an error if the HTTP request fails or if the response cannot be parsed.
        """
    def py_get_balance(self) -> typing.Any: ...

@typing.final
class OKXWebSocketClient:
    r"""
    Provides a WebSocket client for connecting to [OKX](https://okx.com).
    """
    def py_new(self, url: typing.Optional[builtins.str], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], api_passphrase: typing.Optional[builtins.str], account_id: typing.Optional[model.AccountId], heartbeat: typing.Optional[builtins.int], auth_timeout_secs: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str]) -> OKXWebSocketClient:
        r"""
        Provides a WebSocket client for connecting to [OKX](https://okx.com).
        """
    def py_with_credentials(self, url: typing.Optional[builtins.str], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], api_passphrase: typing.Optional[builtins.str], account_id: typing.Optional[model.AccountId], heartbeat: typing.Optional[builtins.int], auth_timeout_secs: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str]) -> OKXWebSocketClient: ...
    def py_from_env(self) -> OKXWebSocketClient: ...
    def py_url(self) -> builtins.str: ...
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_is_active(self) -> builtins.bool: ...
    def py_is_closed(self) -> builtins.bool: ...
    def py_cancel_all_requests(self) -> None: ...
    def py_get_subscriptions(self, instrument_id: model.InstrumentId) -> builtins.list[builtins.str]: ...
    def py_set_vip_level(self, vip_level: OKXVipLevel) -> None:
        r"""
        Sets the VIP level for this client.
        
        The VIP level determines which WebSocket channels are available.
        """
    def py_vip_level(self) -> OKXVipLevel:
        r"""
        Gets the current VIP level.
        """
    def py_connect(self, loop_: typing.Any, instruments: typing.Sequence[typing.Any], callback: typing.Any) -> typing.Any: ...
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any: ...
    def py_close(self) -> typing.Any: ...
    def py_subscribe_instruments(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_subscribe_instrument(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book50_l2_tbt(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book_l2_tbt(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book_with_depth(self, instrument_id: model.InstrumentId, depth: builtins.int) -> typing.Any: ...
    def py_subscribe_book_depth5(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_trades(self, instrument_id: model.InstrumentId, aggregated: builtins.bool) -> typing.Any: ...
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_unsubscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book_depth5(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book50_l2_tbt(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book_l2_tbt(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId, aggregated: builtins.bool) -> typing.Any: ...
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_subscribe_ticker(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_ticker(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_add_option_greeks_sub(self, instrument_id: model.InstrumentId) -> None: ...
    def py_add_option_greeks_sub_with_conventions(self, instrument_id: model.InstrumentId, conventions: typing.Sequence[OKXGreeksType]) -> None: ...
    def py_remove_option_greeks_sub(self, instrument_id: model.InstrumentId) -> None: ...
    def py_subscribe_option_summary(self, inst_family: builtins.str) -> typing.Any: ...
    def py_unsubscribe_option_summary(self, inst_family: builtins.str) -> typing.Any: ...
    def py_subscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_event_contract_markets(self) -> typing.Any: ...
    def py_unsubscribe_event_contract_markets(self) -> typing.Any: ...
    def py_subscribe_orders(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_unsubscribe_orders(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_subscribe_spread_orders(self) -> typing.Any: ...
    def py_unsubscribe_spread_orders(self) -> typing.Any: ...
    def py_subscribe_orders_algo(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_unsubscribe_orders_algo(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_subscribe_algo_advance(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_unsubscribe_algo_advance(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_subscribe_fills(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_unsubscribe_fills(self, instrument_type: OKXInstrumentType) -> typing.Any: ...
    def py_subscribe_account(self) -> typing.Any: ...
    def py_unsubscribe_account(self) -> typing.Any: ...
    def py_submit_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, td_mode: OKXTradeMode, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: typing.Optional[model.TimeInForce], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], post_only: typing.Optional[builtins.bool], reduce_only: typing.Optional[builtins.bool], quote_quantity: typing.Optional[builtins.bool], position_side: typing.Optional[model.PositionSide], attach_algo_ords: typing.Optional[typing.Sequence[dict]], px_usd: typing.Optional[builtins.str], px_vol: typing.Optional[builtins.str], speed_bump: typing.Optional[builtins.str], outcome: typing.Optional[builtins.str], slippage_pct: typing.Optional[builtins.str]) -> typing.Any: ...
    def py_cancel_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any: ...
    def py_modify_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId], price: typing.Optional[model.Price], quantity: typing.Optional[model.Quantity], new_px_usd: typing.Optional[builtins.str], new_px_vol: typing.Optional[builtins.str], speed_bump: typing.Optional[builtins.str]) -> typing.Any: ...
    def py_batch_submit_orders(self, orders: typing.Sequence[typing.Any]) -> typing.Any: ...
    def py_batch_cancel_orders(self, cancels: typing.Sequence[typing.Any]) -> typing.Any:
        r"""
        Cancels multiple orders via WebSocket.
        """
    def py_batch_modify_orders(self, orders: typing.Sequence[typing.Any]) -> typing.Any: ...
    def py_mass_cancel_orders(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_cache_instruments(self, instruments: typing.Sequence[typing.Any]) -> None: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None: ...
    def py_cache_inst_id_codes(self, mappings: typing.Sequence[tuple[builtins.str, builtins.int]]) -> None: ...

@typing.final
class OKXWebSocketError:
    r"""
    Represents an OKX WebSocket error.
    """
    ...

@typing.final
class OKXContractType(enum.Enum):
    r"""
    Represents an instrument contract type on OKX.
    """
    None = ...
    Linear = ...
    Inverse = ...

    def py_new(self, value: typing.Any) -> OKXContractType:
        r"""
        Represents an instrument contract type on OKX.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def py_from_str(self, data: typing.Any) -> OKXContractType: ...
    def variants(self) -> builtins.list[builtins.str]: ...

@typing.final
class OKXEndpointType(enum.Enum):
    r"""
    OKX endpoint types for determining URL and authentication requirements.
    """
    Public = ...
    Private = ...
    Business = ...

@typing.final
class OKXEnvironment(enum.Enum):
    r"""
    OKX API environment.
    """
    Live = ...
    r"""
    Live trading environment.
    """
    Demo = ...
    r"""
    Demo trading environment.
    """

    def py_new(self, value: typing.Any) -> OKXEnvironment:
        r"""
        OKX API environment.
        """
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXEnvironment: ...

@typing.final
class OKXGreeksType(enum.Enum):
    r"""
    Represents the convention used for option greeks on OKX.
    
    OKX publishes two parallel greek sets on `opt-summary` and related endpoints:
    Black-Scholes greeks denominated in USD, and price-adjusted greeks denominated
    in the underlying/coin units.
    """
    Bs = ...
    r"""
    Black-Scholes greeks in USD.
    """
    Pa = ...
    r"""
    Price-adjusted greeks in the underlying/coin units.
    """

@typing.final
class OKXInstrumentType(enum.Enum):
    r"""
    Represents instrument types on OKX.
    """
    Any = ...
    r"""
    Any product type.
    """
    Spot = ...
    r"""
    Spot products.
    """
    Margin = ...
    r"""
    Margin products.
    """
    Swap = ...
    r"""
    Swap products.
    """
    Futures = ...
    r"""
    Futures products.
    """
    Option = ...
    r"""
    Option products.
    """
    Events = ...
    r"""
    Event contract products.
    """

    def py_new(self, value: typing.Any) -> OKXInstrumentType:
        r"""
        Represents instrument types on OKX.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXInstrumentType: ...

@typing.final
class OKXMarginMode(enum.Enum):
    r"""
    Represents the margin mode for OKX accounts.
    
    # Reference
    
    - <https://www.okx.com/en-au/help/iv-isolated-margin-mode>
    - <https://www.okx.com/en-au/help/iii-single-currency-margin-cross-margin-trading>
    - <https://www.okx.com/en-au/help/iv-multi-currency-margin-mode-cross-margin-trading>
    """
    None = ...
    Isolated = ...
    Cross = ...

    def py_new(self, value: typing.Any) -> OKXMarginMode:
        r"""
        Represents the margin mode for OKX accounts.
        
        # Reference
        
        - <https://www.okx.com/en-au/help/iv-isolated-margin-mode>
        - <https://www.okx.com/en-au/help/iii-single-currency-margin-cross-margin-trading>
        - <https://www.okx.com/en-au/help/iv-multi-currency-margin-mode-cross-margin-trading>
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXMarginMode: ...

@typing.final
class OKXOrderStatus(enum.Enum):
    r"""
    Represents the possible states of an order throughout its lifecycle.
    """
    Canceled = ...
    Live = ...
    PartiallyFilled = ...
    Filled = ...
    MmpCanceled = ...

    def py_new(self, value: typing.Any) -> OKXOrderStatus:
        r"""
        Represents the possible states of an order throughout its lifecycle.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXOrderStatus: ...

@typing.final
class OKXPositionMode(enum.Enum):
    r"""
    Represents the position mode for OKX accounts.
    
    # References
    
    <https://www.okx.com/docs-v5/en/#trading-account-rest-api-set-position-mode>
    """
    NetMode = ...
    LongShortMode = ...

    def py_new(self, value: typing.Any) -> OKXPositionMode:
        r"""
        Represents the position mode for OKX accounts.
        
        # References
        
        <https://www.okx.com/docs-v5/en/#trading-account-rest-api-set-position-mode>
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXPositionMode: ...

@typing.final
class OKXTradeMode(enum.Enum):
    r"""
    Represents the trading mode for OKX orders.
    """
    Cash = ...
    Isolated = ...
    Cross = ...
    SpotIsolated = ...

    def py_new(self, value: typing.Any) -> OKXTradeMode:
        r"""
        Represents the trading mode for OKX orders.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXTradeMode: ...

@typing.final
class OKXVipLevel(enum.Enum):
    r"""
    Represents OKX VIP level tiers for trading fee structure and API limits.
    
    VIP levels determine:
    - Trading fee discounts.
    - API rate limits.
    - Access to advanced order book channels (L2/L3 depth).
    
    Higher VIP levels (VIP4+) get access to:
    - "books50-l2-tbt" channel (50 depth, 10ms updates).
    - "bbo-tbt" channel (1 depth, 10ms updates).
    
    VIP5+ get access to:
    - "books-l2-tbt" channel (400 depth, 10ms updates).
    """
    Vip0 = ...
    r"""
    VIP level 0 (default tier).
    """
    Vip1 = ...
    r"""
    VIP level 1.
    """
    Vip2 = ...
    r"""
    VIP level 2.
    """
    Vip3 = ...
    r"""
    VIP level 3.
    """
    Vip4 = ...
    r"""
    VIP level 4 (can access books50-l2-tbt channel).
    """
    Vip5 = ...
    r"""
    VIP level 5 (can access books-l2-tbt channel).
    """
    Vip6 = ...
    r"""
    VIP level 6.
    """
    Vip7 = ...
    r"""
    VIP level 7.
    """
    Vip8 = ...
    r"""
    VIP level 8.
    """
    Vip9 = ...
    r"""
    VIP level 9 (highest tier).
    """

    def py_new(self, value: typing.Any) -> OKXVipLevel:
        r"""
        Represents OKX VIP level tiers for trading fee structure and API limits.
        
        VIP levels determine:
        - Trading fee discounts.
        - API rate limits.
        - Access to advanced order book channels (L2/L3 depth).
        
        Higher VIP levels (VIP4+) get access to:
        - "books50-l2-tbt" channel (50 depth, 10ms updates).
        - "bbo-tbt" channel (1 depth, 10ms updates).
        
        VIP5+ get access to:
        - "books-l2-tbt" channel (400 depth, 10ms updates).
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> OKXVipLevel: ...

def derive_okx_ws_url(base_url: builtins.str, channel: builtins.str) -> builtins.str:
    r"""
    Derives a WebSocket URL for a given channel from a base URL.
    """

def get_okx_http_base_url() -> builtins.str:
    r"""
    Returns the OKX HTTP base URL.
    """

def get_okx_ws_url_business(environment: OKXEnvironment) -> builtins.str:
    r"""
    Returns the OKX WebSocket URL for business data (bars/candlesticks).
    """

def get_okx_ws_url_private(environment: OKXEnvironment) -> builtins.str:
    r"""
    Returns the OKX WebSocket URL for private data (account/order management).
    """

def get_okx_ws_url_public(environment: OKXEnvironment) -> builtins.str:
    r"""
    Returns the OKX WebSocket URL for public data (market data).
    """

def okx_requires_authentication(endpoint_type: OKXEndpointType) -> builtins.bool:
    r"""
    Checks if OKX endpoint requires authentication.
    """

