# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "PostgresConnectOptions",
]

@typing.final
class PostgresConnectOptions:
    def py_new(self, host: builtins.str, port: builtins.int, user: builtins.str, password: builtins.str, database: builtins.str) -> PostgresConnectOptions:
        r"""
        Creates a new `PostgresConnectOptions` instance.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns a string representation of the configuration.
        """
    def host(self) -> builtins.str:
        r"""
        Returns the host.
        """
    def port(self) -> builtins.int:
        r"""
        Returns the port.
        """
    def username(self) -> builtins.str:
        r"""
        Returns the username.
        """
    def password(self) -> builtins.str:
        r"""
        Returns the password.
        """
    def database(self) -> builtins.str:
        r"""
        Returns the database.
        """

