# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "RiskEngineConfig",
]

@typing.final
class RiskEngineConfig:
    r"""
    Configuration for `RiskEngineConfig` instances.
    """
    def py_new(self, bypass: typing.Optional[builtins.bool], max_order_submit_rate: typing.Optional[builtins.str], max_order_modify_rate: typing.Optional[builtins.str], max_notional_per_order: typing.Optional[typing.Mapping[builtins.str, typing.Any]], debug: typing.Optional[builtins.bool]) -> RiskEngineConfig:
        r"""
        Configuration for `RiskEngine` instances.
        """
    def py_bypass(self) -> builtins.bool: ...
    def py_max_order_submit_rate(self) -> builtins.str: ...
    def py_max_order_modify_rate(self) -> builtins.str: ...
    def py_max_notional_per_order(self) -> builtins.dict[builtins.str, builtins.str]: ...
    def py_debug(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

