# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from nautilus_trader import model
import os
import pathlib
import typing
__all__ = [
    "ReplayNormalizedRequestOptions",
    "StreamNormalizedRequestOptions",
    "TardisBatchedDeltasStreamIterator",
    "TardisDataClientConfig",
    "TardisDataClientFactory",
    "TardisDeltaStreamIterator",
    "TardisDepth10StreamIterator",
    "TardisFundingRateStreamIterator",
    "TardisHttpClient",
    "TardisInstrumentKey",
    "TardisInstrumentMiniInfo",
    "TardisMachineClient",
    "TardisQuoteStreamIterator",
    "TardisTradeStreamIterator",
    "py_bar_spec_to_tardis_trade_bar_string",
    "py_load_tardis_deltas",
    "py_load_tardis_depth10_from_snapshot25",
    "py_load_tardis_depth10_from_snapshot5",
    "py_load_tardis_funding_rates",
    "py_load_tardis_quotes",
    "py_load_tardis_trades",
    "py_run_tardis_machine_replay",
    "py_stream_tardis_batched_deltas",
    "py_stream_tardis_deltas",
    "py_stream_tardis_depth10_from_snapshot25",
    "py_stream_tardis_depth10_from_snapshot5",
    "py_stream_tardis_funding_rates",
    "py_stream_tardis_quotes",
    "py_stream_tardis_trades",
    "py_tardis_exchange_from_venue_str",
    "py_tardis_exchange_is_option_exchange",
    "py_tardis_exchange_to_venue_str",
    "py_tardis_exchanges",
    "py_tardis_normalize_symbol_str",
]

@typing.final
class ReplayNormalizedRequestOptions:
    r"""
    The options that can be specified for calling Tardis Machine Server's replay-normalized.
    """
    def py_from_json(self, data: bytes) -> ReplayNormalizedRequestOptions: ...
    def py_from_json_array(self, data: bytes) -> builtins.list[ReplayNormalizedRequestOptions]: ...

@typing.final
class StreamNormalizedRequestOptions:
    r"""
    The options that can be specified for calling Tardis Machine Server's stream-normalized.
    """
    def py_from_json(self, data: bytes) -> StreamNormalizedRequestOptions: ...
    def py_from_json_array(self, data: bytes) -> builtins.list[StreamNormalizedRequestOptions]: ...

@typing.final
class TardisBatchedDeltasStreamIterator:
    def __iter__(self) -> TardisBatchedDeltasStreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[typing.Any]]: ...

@typing.final
class TardisDataClientConfig:
    r"""
    Configuration for the Tardis data client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], tardis_ws_url: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], normalize_symbols: typing.Optional[builtins.bool], options: typing.Optional[typing.Sequence[ReplayNormalizedRequestOptions]], stream_options: typing.Optional[typing.Sequence[StreamNormalizedRequestOptions]], extract_bbo_as_quotes: typing.Optional[builtins.bool]) -> TardisDataClientConfig:
        r"""
        Configuration for the Tardis data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TardisDataClientFactory:
    r"""
    Factory for creating Tardis data clients.
    """
    def py_new(self) -> TardisDataClientFactory:
        r"""
        Factory for creating Tardis data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class TardisDeltaStreamIterator:
    def __iter__(self) -> TardisDeltaStreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[model.OrderBookDelta]]: ...

@typing.final
class TardisDepth10StreamIterator:
    def __iter__(self) -> TardisDepth10StreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[model.OrderBookDepth10]]: ...

@typing.final
class TardisFundingRateStreamIterator:
    def __iter__(self) -> TardisFundingRateStreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[model.FundingRateUpdate]]: ...

@typing.final
class TardisHttpClient:
    r"""
    A Tardis HTTP API client.
    See <https://docs.tardis.dev/api/http>.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], timeout_secs: typing.Optional[builtins.int], normalize_symbols: builtins.bool, proxy_url: typing.Optional[builtins.str]) -> TardisHttpClient:
        r"""
        A Tardis HTTP API client.
        See <https://docs.tardis.dev/api/http>.
        """
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_instruments(self, exchange: builtins.str, symbol: typing.Optional[builtins.str], base_currency: typing.Optional[typing.Sequence[builtins.str]], quote_currency: typing.Optional[typing.Sequence[builtins.str]], instrument_type: typing.Optional[typing.Sequence[builtins.str]], contract_type: typing.Optional[typing.Sequence[builtins.str]], active: typing.Optional[builtins.bool], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], available_offset: typing.Optional[builtins.int], effective: typing.Optional[builtins.int], ts_init: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Returns all Nautilus instrument definitions for the given `exchange`, and filter params.
        """

@typing.final
class TardisInstrumentKey:
    r"""
    Instrument definition information necessary for stream parsing.
    """
    ...

@typing.final
class TardisInstrumentMiniInfo:
    r"""
    Instrument definition information necessary for stream parsing.
    """
    def py_new(self, instrument_id: model.InstrumentId, raw_symbol: builtins.str, exchange: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> TardisInstrumentMiniInfo:
        r"""
        Instrument definition information necessary for stream parsing.
        """
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_raw_symbol(self) -> builtins.str: ...
    def py_exchange(self) -> builtins.str: ...
    def py_price_precision(self) -> builtins.int: ...
    def py_size_precision(self) -> builtins.int: ...

@typing.final
class TardisMachineClient:
    r"""
    Provides a client for connecting to a [Tardis Machine Server](https://docs.tardis.dev/api/tardis-machine).
    """
    def py_new(self, base_url: typing.Optional[builtins.str], normalize_symbols: builtins.bool, book_snapshot_output: builtins.str, extract_bbo_as_quotes: builtins.bool) -> TardisMachineClient:
        r"""
        Provides a client for connecting to a [Tardis Machine Server](https://docs.tardis.dev/api/tardis-machine).
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Returns `true` if `close()` has been called.
        
        This checks that both replay and stream signals have been set,
        which only occurs when `close()` is explicitly called.
        """
    def py_close(self) -> None: ...
    def py_replay(self, instruments: typing.Sequence[TardisInstrumentMiniInfo], options: typing.Sequence[ReplayNormalizedRequestOptions], callback: typing.Any) -> typing.Any:
        r"""
        Connects to the Tardis Machine replay WebSocket and yields parsed `Data` items.
        """
    def py_replay_bars(self, instruments: typing.Sequence[TardisInstrumentMiniInfo], options: typing.Sequence[ReplayNormalizedRequestOptions]) -> typing.Any: ...
    def py_stream(self, instruments: typing.Sequence[TardisInstrumentMiniInfo], options: typing.Sequence[StreamNormalizedRequestOptions], callback: typing.Any) -> typing.Any:
        r"""
        Connects to the Tardis Machine stream WebSocket for a single instrument and yields parsed `Data` items.
        """

@typing.final
class TardisQuoteStreamIterator:
    def __iter__(self) -> TardisQuoteStreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[model.QuoteTick]]: ...

@typing.final
class TardisTradeStreamIterator:
    def __iter__(self) -> TardisTradeStreamIterator: ...
    def __next__(self) -> typing.Optional[builtins.list[model.TradeTick]]: ...

def py_bar_spec_to_tardis_trade_bar_string(bar_spec: model.BarSpecification) -> builtins.str:
    r"""
    Converts a Nautilus `BarSpecification` to the Tardis trade bar string convention.
    
    # Errors
    
    Returns an error if the bar aggregation kind is unsupported.
    """

def py_load_tardis_deltas(filepath: builtins.str | os.PathLike | pathlib.Path, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.OrderBookDelta]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_load_tardis_depth10_from_snapshot25(filepath: builtins.str | os.PathLike | pathlib.Path, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.OrderBookDepth10]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_load_tardis_depth10_from_snapshot5(filepath: builtins.str | os.PathLike | pathlib.Path, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.OrderBookDepth10]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_load_tardis_funding_rates(filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.FundingRateUpdate]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_load_tardis_quotes(filepath: builtins.str | os.PathLike | pathlib.Path, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.QuoteTick]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_load_tardis_trades(filepath: builtins.str | os.PathLike | pathlib.Path, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> builtins.list[model.TradeTick]:
    r"""
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_run_tardis_machine_replay(config_filepath: builtins.str) -> typing.Any:
    r"""
    Run the Tardis Machine replay as an async Python future.
    
    # Errors
    
    Returns a `PyErr` if reading the config file or replay execution fails.
    """

def py_stream_tardis_batched_deltas(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisBatchedDeltasStreamIterator:
    r"""
    Streams batched order book deltas from a Tardis CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_deltas(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisDeltaStreamIterator:
    r"""
    Streams order book deltas from a Tardis CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_depth10_from_snapshot25(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisDepth10StreamIterator:
    r"""
    Streams order book depth10 from a Tardis snapshot25 CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_depth10_from_snapshot5(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisDepth10StreamIterator:
    r"""
    Streams order book depth10 from a Tardis snapshot5 CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_funding_rates(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisFundingRateStreamIterator:
    r"""
    Streams funding rate updates from a Tardis derivative ticker CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_quotes(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisQuoteStreamIterator:
    r"""
    Streams quote ticks from a Tardis CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_stream_tardis_trades(filepath: builtins.str | os.PathLike | pathlib.Path, chunk_size: builtins.int, price_precision: typing.Optional[builtins.int], size_precision: typing.Optional[builtins.int], instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> TardisTradeStreamIterator:
    r"""
    Streams trade ticks from a Tardis CSV file.
    
    # Errors
    
    Returns a Python error if loading or parsing the CSV file fails.
    """

def py_tardis_exchange_from_venue_str(venue_str: builtins.str) -> builtins.list[builtins.str]: ...

def py_tardis_exchange_is_option_exchange(exchange_str: builtins.str) -> builtins.bool: ...

def py_tardis_exchange_to_venue_str(exchange_str: builtins.str) -> builtins.str: ...

def py_tardis_exchanges() -> builtins.list[builtins.str]: ...

def py_tardis_normalize_symbol_str(symbol: builtins.str, exchange: builtins.str, instrument_type: builtins.str, is_inverse: typing.Optional[builtins.bool]) -> builtins.str:
    r"""
    Normalize a symbol string for Tardis, returning a suffix-modified symbol.
    
    # Errors
    
    Returns a `PyErr` if the `exchange` or `instrument_type` cannot be parsed.
    """

