# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from nautilus_trader import model
import os
import pathlib
import typing
__all__ = [
    "DatabentoDataClient",
    "DatabentoDataClientFactory",
    "DatabentoDataLoader",
    "DatabentoHistoricalClient",
    "DatabentoImbalance",
    "DatabentoLiveClient",
    "DatabentoLiveClientConfig",
    "DatabentoPublisher",
    "DatabentoStatisticType",
    "DatabentoStatisticUpdateAction",
    "DatabentoStatistics",
    "DatabentoSubscriptionAck",
    "get_databento_arrow_schema_map",
]

@typing.final
class DatabentoDataClient:
    r"""
    A Databento data client that combines live streaming and historical data functionality.
    
    This client uses the existing `DatabentoFeedHandler` for live data subscriptions
    and `DatabentoHistoricalClient` for historical data requests. It supports multiple
    datasets simultaneously, with separate feed handlers per dataset.
    """
    ...

@typing.final
class DatabentoDataClientFactory:
    r"""
    Factory for creating Databento data clients.
    """
    def py_new(self) -> DatabentoDataClientFactory:
        r"""
        Factory for creating Databento data clients.
        """
    def py_name(self) -> builtins.str: ...
    def py_create_live_data_client(self, client_id: model.ClientId, api_key: builtins.str, publishers_filepath: builtins.str | os.PathLike | pathlib.Path, use_exchange_as_venue: builtins.bool, bars_timestamp_on_close: builtins.bool) -> DatabentoDataClient:
        r"""
        Creates a new `DatabentoDataClient` instance.
        """

@typing.final
class DatabentoDataLoader:
    r"""
    A Nautilus data loader for Databento Binary Encoding (DBN) format data.
    
    # Supported Schemas
     - `MBO` -> `OrderBookDelta`
     - `MBP_1` -> `(QuoteTick, Option<TradeTick>)`
     - `MBP_10` -> `OrderBookDepth10`
     - `BBO_1S` -> `QuoteTick`
     - `BBO_1M` -> `QuoteTick`
     - `CMBP_1` -> `(QuoteTick, Option<TradeTick>)`
     - `CBBO_1S` -> `QuoteTick`
     - `CBBO_1M` -> `QuoteTick`
     - `TCBBO` -> `(QuoteTick, TradeTick)`
     - `TBBO` -> `(QuoteTick, TradeTick)`
     - `TRADES` -> `TradeTick`
     - `OHLCV_1S` -> `Bar`
     - `OHLCV_1M` -> `Bar`
     - `OHLCV_1H` -> `Bar`
     - `OHLCV_1D` -> `Bar`
     - `OHLCV_EOD` -> `Bar`
     - `DEFINITION` -> `Instrument`
     - `IMBALANCE` -> `DatabentoImbalance`
     - `STATISTICS` -> `DatabentoStatistics`
     - `STATUS` -> `InstrumentStatus`
    
    # References
    
    <https://databento.com/docs/schemas-and-data-formats>
    """
    def py_new(self, publishers_filepath: typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> DatabentoDataLoader:
        r"""
        A Nautilus data loader for Databento Binary Encoding (DBN) format data.
        
        # Supported Schemas
         - `MBO` -> `OrderBookDelta`
         - `MBP_1` -> `(QuoteTick, Option<TradeTick>)`
         - `MBP_10` -> `OrderBookDepth10`
         - `BBO_1S` -> `QuoteTick`
         - `BBO_1M` -> `QuoteTick`
         - `CMBP_1` -> `(QuoteTick, Option<TradeTick>)`
         - `CBBO_1S` -> `QuoteTick`
         - `CBBO_1M` -> `QuoteTick`
         - `TCBBO` -> `(QuoteTick, TradeTick)`
         - `TBBO` -> `(QuoteTick, TradeTick)`
         - `TRADES` -> `TradeTick`
         - `OHLCV_1S` -> `Bar`
         - `OHLCV_1M` -> `Bar`
         - `OHLCV_1H` -> `Bar`
         - `OHLCV_1D` -> `Bar`
         - `OHLCV_EOD` -> `Bar`
         - `DEFINITION` -> `Instrument`
         - `IMBALANCE` -> `DatabentoImbalance`
         - `STATISTICS` -> `DatabentoStatistics`
         - `STATUS` -> `InstrumentStatus`
        
        # References
        
        <https://databento.com/docs/schemas-and-data-formats>
        """
    def py_load_publishers(self, publishers_filepath: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Load the publishers data from the file at the given `filepath`.
        
        # Errors
        
        Returns an error if the file cannot be read or parsed as JSON.
        """
    def py_get_publishers(self) -> builtins.dict[builtins.int, DatabentoPublisher]:
        r"""
        Returns the internal Databento publishers currently held by the loader.
        """
    def py_set_dataset_for_venue(self, dataset: builtins.str, venue: model.Venue) -> None:
        r"""
        Sets the `venue` to map to the given `dataset`.
        """
    def py_get_dataset_for_venue(self, venue: model.Venue) -> typing.Optional[builtins.str]:
        r"""
        Returns the dataset which matches the given `venue` (if found).
        """
    def py_get_venue_for_publisher(self, publisher_id: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Returns the venue which matches the given `publisher_id` (if found).
        """
    def py_set_price_precision(self, symbol: builtins.str, price_precision: builtins.int) -> None:
        r"""
        Caches a `price_precision` for the given `symbol`.
        
        When market data is read without an explicit `price_precision` argument,
        the loader resolves precision per record from this cache. Definitions
        loaded via `Self.load_instruments` are inserted automatically.
        """
    def py_get_price_precisions(self) -> builtins.dict[builtins.str, builtins.int]:
        r"""
        Returns the cached price precisions keyed by symbol.
        """
    def py_schema_for_file(self, filepath: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.str]: ...
    def py_load_instruments(self, filepath: builtins.str | os.PathLike | pathlib.Path, use_exchange_as_venue: builtins.bool, skip_on_error: builtins.bool) -> typing.Any:
        r"""
        Loads all instrument definitions from a DBN file.
        
        When `skip_on_error` is true, instruments that fail to decode are logged
        as warnings and skipped. When false (default), any decode error is propagated.
        """
    def py_load_order_book_deltas(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.OrderBookDelta]:
        r"""
        Loads order book delta messages from a DBN MBO schema file.
        
        Cannot include trades.
        """
    def py_load_order_book_deltas_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int], include_trades: typing.Optional[builtins.bool]) -> typing.Any: ...
    def py_load_order_book_depth10(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.OrderBookDepth10]:
        r"""
        Loads order book depth10 snapshots from a DBN MBP-10 schema file.
        """
    def py_load_order_book_depth10_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_quotes(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.QuoteTick]:
        r"""
        Loads quote tick messages from a DBN MBP-1 or TBBO schema file.
        """
    def py_load_quotes_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int], include_trades: typing.Optional[builtins.bool]) -> typing.Any: ...
    def py_load_bbo_quotes(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.QuoteTick]:
        r"""
        Loads best bid/offer quote messages from a DBN BBO schema file.
        """
    def py_load_bbo_quotes_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_cmbp_quotes(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.QuoteTick]:
        r"""
        Loads consolidated MBP-1 quote messages from a DBN CMBP-1 schema file.
        """
    def py_load_cmbp_quotes_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int], include_trades: typing.Optional[builtins.bool]) -> typing.Any: ...
    def py_load_cbbo_quotes(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.QuoteTick]:
        r"""
        Loads consolidated best bid/offer quote messages from a DBN CBBO schema file.
        """
    def py_load_cbbo_quotes_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_tbbo_trades(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.TradeTick]:
        r"""
        Loads trade messages from a DBN TBBO schema file.
        """
    def py_load_tbbo_trades_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_tcbbo_trades(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.TradeTick]:
        r"""
        Loads trade messages from a DBN TCBBO schema file.
        """
    def py_load_tcbbo_trades_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_trades(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[model.TradeTick]:
        r"""
        Loads trade messages from a DBN TRADES schema file.
        """
    def py_load_trades_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_load_bars(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int], timestamp_on_close: builtins.bool) -> builtins.list[model.Bar]:
        r"""
        Loads OHLCV bar messages from a DBN OHLCV schema file.
        """
    def py_load_bars_as_pycapsule(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int], timestamp_on_close: builtins.bool) -> typing.Any: ...
    def py_load_status(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId]) -> builtins.list[model.InstrumentStatus]: ...
    def py_load_imbalance(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[DatabentoImbalance]: ...
    def py_load_statistics(self, filepath: builtins.str | os.PathLike | pathlib.Path, instrument_id: typing.Optional[model.InstrumentId], price_precision: typing.Optional[builtins.int]) -> builtins.list[DatabentoStatistics]: ...

@typing.final
class DatabentoHistoricalClient:
    r"""
    Python wrapper for the core Databento historical client.
    """
    def py_new(self, key: builtins.str, publishers_filepath: builtins.str | os.PathLike | pathlib.Path, use_exchange_as_venue: builtins.bool) -> DatabentoHistoricalClient:
        r"""
        Core Databento historical client for fetching historical market data.
        
        This client provides both synchronous and asynchronous interfaces for fetching
        various types of historical market data from Databento.
        """
    def py_api_key(self) -> builtins.str:
        r"""
        Returns the API key from the stored credential.
        """
    def py_set_price_precision(self, symbol: builtins.str, price_precision: builtins.int) -> None:
        r"""
        Caches a `price_precision` for the given `symbol`.
        
        When market data is fetched without an explicit `price_precision`, the
        client resolves precision per record from this cache. Instruments
        returned by `Self.get_range_instruments` are inserted automatically.
        """
    def py_get_dataset_range(self, dataset: builtins.str) -> typing.Any:
        r"""
        Gets the date range for a specific dataset.
        """
    def py_get_range_instruments(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches instrument definitions for the given parameters.
        """
    def py_get_range_quotes(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int], schema: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Fetches quote ticks for the given parameters.
        """
    def py_get_range_trades(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches trade ticks for the given parameters.
        """
    def py_get_range_bars(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], aggregation: model.BarAggregation, start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int], timestamp_on_close: builtins.bool) -> typing.Any:
        r"""
        Fetches bars for the given parameters.
        """
    def py_get_order_book_depth10(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], depth: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_get_range_order_book_deltas(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches order book deltas for the given parameters.
        """
    def py_get_range_imbalance(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches imbalance data for the given parameters.
        """
    def py_get_range_statistics(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int], price_precision: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches statistics data for the given parameters.
        """
    def py_get_range_status(self, dataset: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: builtins.int, end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches status data for the given parameters.
        """

@typing.final
class DatabentoImbalance:
    r"""
    Represents an auction imbalance.
    
    This data type includes the populated data fields provided by `Databento`,
    excluding `publisher_id` and `instrument_id`.
    """
    def __richcmp__(self, other: DatabentoImbalance, op: int) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_ref_price(self) -> model.Price: ...
    def py_cont_book_clr_price(self) -> model.Price: ...
    def py_auct_interest_clr_price(self) -> model.Price: ...
    def py_paired_qty(self) -> model.Quantity: ...
    def py_total_imbalance_qty(self) -> model.Quantity: ...
    def py_side(self) -> model.OrderSide: ...
    def py_significant_imbalance(self) -> builtins.str: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_recv(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...
    def py_from_dict(self, values: dict) -> DatabentoImbalance: ...
    def py_to_dict(self) -> typing.Any:
        r"""
        # Errors
        
        Returns a `PyErr` if generating the Python dictionary fails.
        """

@typing.final
class DatabentoLiveClient:
    def py_new(self, key: builtins.str, dataset: builtins.str, publishers_filepath: builtins.str | os.PathLike | pathlib.Path, use_exchange_as_venue: builtins.bool, bars_timestamp_on_close: typing.Optional[builtins.bool], reconnect_timeout_mins: typing.Optional[builtins.int]) -> DatabentoLiveClient:
        r"""
        # Errors
        
        Returns a `PyErr` if reading or parsing the publishers file fails.
        """
    def py_is_running(self) -> builtins.bool: ...
    def py_is_closed(self) -> builtins.bool: ...
    def py_subscribe(self, schema: builtins.str, instrument_ids: typing.Sequence[model.InstrumentId], start: typing.Optional[builtins.int], snapshot: typing.Optional[builtins.bool], price_precisions: typing.Optional[typing.Sequence[typing.Optional[builtins.int]]], stype_in: typing.Optional[builtins.str]) -> None: ...
    def py_start(self, callback: typing.Any, callback_pyo3: typing.Any) -> typing.Any: ...
    def py_close(self) -> None: ...

@typing.final
class DatabentoLiveClientConfig:
    r"""
    Configuration for Databento data clients used with `LiveNode`.
    """
    def py_new(self, api_key: builtins.str, publishers_filepath: builtins.str | os.PathLike | pathlib.Path, use_exchange_as_venue: builtins.bool, bars_timestamp_on_close: builtins.bool) -> DatabentoLiveClientConfig:
        r"""
        Configuration for Databento data clients used with `LiveNode`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DatabentoPublisher:
    r"""
    Represents a Databento publisher.
    """
    ...

@typing.final
class DatabentoStatistics:
    r"""
    Represents a market statistics snapshot.
    
    This data type includes the populated data fields provided by `Databento`,
    excluding `publisher_id` and `instrument_id`.
    """
    def __richcmp__(self, other: DatabentoStatistics, op: int) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_stat_type(self) -> DatabentoStatisticType: ...
    def py_update_action(self) -> DatabentoStatisticUpdateAction: ...
    def py_price(self) -> typing.Optional[model.Price]: ...
    def py_quantity(self) -> typing.Optional[model.Quantity]: ...
    def py_channel_id(self) -> builtins.int: ...
    def py_stat_flags(self) -> builtins.int: ...
    def py_sequence(self) -> builtins.int: ...
    def py_ts_ref(self) -> builtins.int: ...
    def py_ts_in_delta(self) -> builtins.int: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_recv(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...
    def py_from_dict(self, values: dict) -> DatabentoStatistics: ...
    def py_to_dict(self) -> typing.Any:
        r"""
        # Errors
        
        Returns a `PyErr` if generating the Python dictionary fails.
        """

@typing.final
class DatabentoSubscriptionAck:
    r"""
    Subscription acknowledgement from the Databento gateway.
    """
    ...

@typing.final
class DatabentoStatisticType(enum.Enum):
    r"""
    Represents a Databento statistic type.
    """
    OpeningPrice = ...
    IndicativeOpeningPrice = ...
    SettlementPrice = ...
    TradingSessionLowPrice = ...
    TradingSessionHighPrice = ...
    ClearedVolume = ...
    LowestOffer = ...
    HighestBid = ...
    OpenInterest = ...
    FixingPrice = ...
    ClosePrice = ...
    NetChange = ...
    Vwap = ...
    Volatility = ...
    Delta = ...
    UncrossingPrice = ...
    UpperPriceLimit = ...
    LowerPriceLimit = ...
    BlockVolume = ...
    IndicativeClosePrice = ...

    def py_new(self, value: typing.Any) -> DatabentoStatisticType:
        r"""
        Represents a Databento statistic type.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def py_from_str(self, data: typing.Any) -> DatabentoStatisticType: ...

@typing.final
class DatabentoStatisticUpdateAction(enum.Enum):
    r"""
    Represents a Databento statistic update action.
    """
    Added = ...
    Deleted = ...

    def py_new(self, value: typing.Any) -> DatabentoStatisticUpdateAction:
        r"""
        Represents a Databento statistic update action.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def py_from_str(self, data: typing.Any) -> DatabentoStatisticUpdateAction: ...

def get_databento_arrow_schema_map(cls: type) -> typing.Any:
    r"""
    Returns a mapping from field names to Arrow data types for the given Databento data class.
    
    # Errors
    
    Returns a `PyErr` if the class name is not recognized.
    """

