# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "HttpClient",
    "HttpMethod",
    "HttpResponse",
    "Quota",
    "SocketClient",
    "SocketConfig",
    "WebSocketClient",
    "WebSocketConfig",
    "http_delete",
    "http_download",
    "http_get",
    "http_patch",
    "http_post",
]

@typing.final
class HttpClient:
    r"""
    An HTTP client that supports rate limiting and timeouts.
    
    Built on `reqwest` for async I/O. Allows per-endpoint and default quotas
    through a rate limiter.
    
    This struct is designed to handle HTTP requests efficiently, providing
    support for rate limiting, timeouts, and custom headers. The client is
    built on top of `reqwest` and can be used for both synchronous and
    asynchronous HTTP requests.
    """
    def py_new(self, default_headers: typing.Mapping[builtins.str, builtins.str], header_keys: typing.Sequence[builtins.str], keyed_quotas: typing.Sequence[tuple[builtins.str, Quota]], default_quota: typing.Optional[Quota], timeout_secs: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str]) -> HttpClient:
        r"""
        An HTTP client that supports rate limiting and timeouts.
        
        Built on `reqwest` for async I/O. Allows per-endpoint and default quotas
        through a rate limiter.
        
        This struct is designed to handle HTTP requests efficiently, providing
        support for rate limiting, timeouts, and custom headers. The client is
        built on top of `reqwest` and can be used for both synchronous and
        asynchronous HTTP requests.
        """
    def py_request(self, method: HttpMethod, url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], body: typing.Optional[typing.Sequence[builtins.int]], keys: typing.Optional[typing.Sequence[builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Sends an HTTP request.
        
        # Examples
        
        If requesting `/foo/bar`, pass rate-limit keys `["foo/bar", "foo"]`.
        """
    def py_get(self, url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], keys: typing.Optional[typing.Sequence[builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Sends an HTTP GET request.
        """
    def py_post(self, url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], body: typing.Optional[typing.Sequence[builtins.int]], keys: typing.Optional[typing.Sequence[builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Sends an HTTP POST request.
        """
    def py_patch(self, url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], body: typing.Optional[typing.Sequence[builtins.int]], keys: typing.Optional[typing.Sequence[builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Sends an HTTP PATCH request.
        """
    def py_delete(self, url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], keys: typing.Optional[typing.Sequence[builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Sends an HTTP DELETE request.
        """

@typing.final
class HttpResponse:
    r"""
    Represents the response from an HTTP request.
    
    This struct encapsulates the status, headers, and body of an HTTP response,
    providing easy access to the key components of the response.
    """
    def py_new(self, status: builtins.int, body: typing.Sequence[builtins.int]) -> HttpResponse:
        r"""
        Represents the response from an HTTP request.
        
        This struct encapsulates the status, headers, and body of an HTTP response,
        providing easy access to the key components of the response.
        """
    def py_status(self) -> builtins.int: ...
    def py_headers(self) -> builtins.dict[builtins.str, builtins.str]: ...
    def py_body(self) -> bytes: ...

@typing.final
class Quota:
    r"""
    A rate-limiting quota.
    
    Quotas are expressed in a positive number of "cells" (the maximum number of positive decisions /
    allowed items until the rate limiter needs to replenish) and the amount of time for the rate
    limiter to replenish a single cell.
    
    Neither the number of cells nor the replenishment unit of time may be zero.
    
    # Burst Sizes
    There are multiple ways of expressing the same quota: a quota given as `Quota::per_second(1)`
    allows, on average, the same number of cells through as a quota given as `Quota::per_minute(60)`.
    The quota of `Quota::per_minute(60)` has a burst size of 60 cells, meaning it is
    possible to accommodate 60 cells in one go, after which the equivalent of a minute of inactivity
    is required for the burst allowance to be fully restored.
    
    Burst size gets really important when you construct a rate limiter that should allow multiple
    elements through at one time (using [`RateLimiter.check_n`](struct.RateLimiter.html#method.check_n)
    and its related functions): Only
    at most as many cells can be let through in one call as are given as the burst size.
    
    In other words, the burst size is the maximum number of cells that the rate limiter will ever
    allow through without replenishing them.
    """
    def rate_per_second(self, max_burst: builtins.int) -> Quota:
        r"""
        Construct a quota for a number of requests per second.
        
        # Errors
        
        Returns a `PyErr` if the max burst capacity is 0
        """
    def rate_per_minute(self, max_burst: builtins.int) -> Quota:
        r"""
        Construct a quota for a number of requests per minute.
        
        # Errors
        
        Returns a `PyErr` if the max burst capacity is 0
        """
    def rate_per_hour(self, max_burst: builtins.int) -> Quota:
        r"""
        Construct a quota for a number of requests per hour.
        
        # Errors
        
        Returns a `PyErr` if the max burst capacity is 0
        """

@typing.final
class SocketClient:
    def py_connect(self, config: SocketConfig, post_connection: typing.Optional[typing.Any], post_reconnection: typing.Optional[typing.Any], post_disconnection: typing.Optional[typing.Any]) -> typing.Any:
        r"""
        Connect to the server.
        """
    def py_is_active(self) -> builtins.bool:
        r"""
        Check if the client connection is active.
        
        Returns `true` if the client is connected and has not been signalled to disconnect.
        The client will automatically retry connection based on its configuration.
        """
    def py_is_reconnecting(self) -> builtins.bool:
        r"""
        Check if the client is reconnecting.
        
        Returns `true` if the client lost connection and is attempting to reestablish it.
        The client will automatically retry connection based on its configuration.
        """
    def py_is_disconnecting(self) -> builtins.bool:
        r"""
        Check if the client is disconnecting.
        
        Returns `true` if the client is in disconnect mode.
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Check if the client is closed.
        
        Returns `true` if the client has been explicitly disconnected or reached
        maximum reconnection attempts. In this state, the client cannot be reused
        and a new client must be created for further connections.
        """
    def py_mode(self) -> builtins.str: ...
    def py_reconnect(self) -> typing.Any:
        r"""
        Reconnect the client.
        """
    def py_close(self) -> typing.Any:
        r"""
        Close the client.
        
        Controller task will periodically check the disconnect mode
        and shutdown the client if it is not alive.
        """
    def py_send(self, data: typing.Sequence[builtins.int]) -> typing.Any:
        r"""
        Send bytes data to the connection.
        
        # Errors
        
        - Throws an Exception if it is not able to send data.
        """

@typing.final
class SocketConfig:
    r"""
    Configuration for TCP socket connection.
    """
    def py_new(self, url: builtins.str, ssl: builtins.bool, suffix: typing.Sequence[builtins.int], handler: typing.Any, heartbeat: typing.Optional[tuple[builtins.int, typing.Sequence[builtins.int]]], reconnect_timeout_ms: typing.Optional[builtins.int], reconnect_delay_initial_ms: typing.Optional[builtins.int], reconnect_delay_max_ms: typing.Optional[builtins.int], reconnect_backoff_factor: typing.Optional[builtins.float], reconnect_jitter_ms: typing.Optional[builtins.int], connection_max_retries: typing.Optional[builtins.int], reconnect_max_attempts: typing.Optional[builtins.int], idle_timeout_ms: typing.Optional[builtins.int], certs_dir: typing.Optional[builtins.str]) -> SocketConfig:
        r"""
        Configuration for TCP socket connection.
        """

@typing.final
class WebSocketClient:
    r"""
    WebSocket client with automatic reconnection.
    
    Handles connection state, callbacks, and rate limiting.
    See module docs for architecture details.
    """
    def py_connect(self, loop_: typing.Any, config: WebSocketConfig, handler: typing.Any, ping_handler: typing.Optional[typing.Any], post_reconnection: typing.Optional[typing.Any], keyed_quotas: typing.Sequence[tuple[builtins.str, Quota]], default_quota: typing.Optional[Quota]) -> typing.Any:
        r"""
        Creates a websocket client in **handler mode** with automatic reconnection.
        
        The handler is called for each incoming message on an internal task.
        Automatic reconnection is **enabled** with exponential backoff. On disconnection,
        the client automatically attempts to reconnect and replaces the internal reader
        (the handler continues working seamlessly).
        
        Use handler mode for simplified connection management, automatic reconnection, Python
        bindings, or callback-based message handling.
        
        See `WebSocketConfig` documentation for comparison with stream mode.
        """
    def py_disconnect(self) -> typing.Any:
        r"""
        Set disconnect mode to true.
        
        Controller task will periodically check the disconnect mode
        and shutdown the client if it is alive
        """
    def py_is_active(self) -> builtins.bool:
        r"""
        Check if the client connection is active.
        
        Returns `true` if the client is connected and has not been signalled to disconnect.
        The client will automatically retry connection based on its configuration.
        """
    def py_is_reconnecting(self) -> builtins.bool:
        r"""
        Check if the client is reconnecting.
        
        Returns `true` if the client lost connection and is attempting to reestablish it.
        The client will automatically retry connection based on its configuration.
        """
    def py_is_disconnecting(self) -> builtins.bool:
        r"""
        Check if the client is disconnecting.
        
        Returns `true` if the client is in disconnect mode.
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Check if the client is closed.
        
        Returns `true` if the client has been explicitly disconnected or reached
        maximum reconnection attempts. In this state, the client cannot be reused
        and a new client must be created for further connections.
        """
    def py_send(self, data: typing.Sequence[builtins.int], keys: typing.Optional[typing.Sequence[builtins.str]]) -> typing.Any:
        r"""
        Send bytes data to the server.
        
        # Errors
        
        Returns an error if:
        - The connection is not active or closes while waiting for rate limit (`WebSocketClientError`).
        - The writer channel is broken (`PyRuntimeError`).
        """
    def py_send_text(self, data: typing.Sequence[builtins.int], keys: typing.Optional[typing.Sequence[builtins.str]]) -> typing.Any:
        r"""
        Sends the given text `data` to the server.
        
        Returns `Ok(())` when the message is enqueued to the writer channel. This does NOT
        guarantee delivery: if a disconnect occurs concurrently, the writer task may drop the
        message. During reconnection, messages are buffered and replayed on the new connection.
        """
    def py_send_pong(self, data: typing.Sequence[builtins.int]) -> typing.Any:
        r"""
        Sends a pong frame back to the server.
        """

@typing.final
class WebSocketConfig:
    r"""
    Configuration for WebSocket client connections.
    
    This struct contains only static configuration settings. Runtime callbacks
    (message handler, ping handler) are passed separately to `connect()`.
    
    # Connection Modes
    
    ## Handler Mode
    
    - Use with [`crate::websocket::WebSocketClient::connect`].
    - Pass a message handler to `connect()` to receive messages via callback.
    - Client spawns internal task to read messages and call handler.
    - Supports automatic reconnection with exponential backoff.
    - Reconnection config fields (`reconnect_*`) are active.
    - Best for long-lived connections, Python bindings, callback-based APIs.
    
    ## Stream Mode
    
    - Use with [`crate::websocket::WebSocketClient::connect_stream`].
    - Returns a [`MessageReader`](super::types::MessageReader) stream for the caller to read from.
    - **Does NOT support automatic reconnection** (reader owned by caller).
    - Reconnection config fields are ignored.
    - On disconnect, client transitions to CLOSED state and caller must manually reconnect.
    """
    def py_new(self, url: builtins.str, headers: typing.Sequence[tuple[builtins.str, builtins.str]], heartbeat: typing.Optional[builtins.int], heartbeat_msg: typing.Optional[builtins.str], reconnect_timeout_ms: typing.Optional[builtins.int], reconnect_delay_initial_ms: typing.Optional[builtins.int], reconnect_delay_max_ms: typing.Optional[builtins.int], reconnect_backoff_factor: typing.Optional[builtins.float], reconnect_jitter_ms: typing.Optional[builtins.int], reconnect_max_attempts: typing.Optional[builtins.int], idle_timeout_ms: typing.Optional[builtins.int], proxy_url: typing.Optional[builtins.str]) -> WebSocketConfig:
        r"""
        Configuration for WebSocket client connections.
        
        This struct contains only static configuration settings. Runtime callbacks
        (message handler, ping handler) are passed separately to `connect()`.
        
        # Connection Modes
        
        ## Handler Mode
        
        - Use with `crate.websocket.WebSocketClient.connect`.
        - Pass a message handler to `connect()` to receive messages via callback.
        - Client spawns internal task to read messages and call handler.
        - Supports automatic reconnection with exponential backoff.
        - Reconnection config fields (`reconnect_*`) are active.
        - Best for long-lived connections, Python bindings, callback-based APIs.
        
        ## Stream Mode
        
        - Use with `crate.websocket.WebSocketClient.connect_stream`.
        - Returns a `MessageReader` stream for the caller to read from.
        - **Does NOT support automatic reconnection** (reader owned by caller).
        - Reconnection config fields are ignored.
        - On disconnect, client transitions to CLOSED state and caller must manually reconnect.
        """

@typing.final
class HttpMethod(enum.Enum):
    r"""
    Represents the HTTP methods supported by the `HttpClient`.
    """
    GET = ...
    POST = ...
    PUT = ...
    DELETE = ...
    PATCH = ...

    def __hash__(self) -> builtins.int: ...

def http_delete(url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> HttpResponse:
    r"""
    Blocking HTTP DELETE request.
    
    Creates an `HttpClient` internally and blocks on the async operation using a dedicated runtime.
    
    # Errors
    
    Returns an error if:
    - The HTTP client fails to initialize.
    - The dedicated runtime cannot be created or the request thread panics.
    - The HTTP request fails (e.g., network error, timeout, invalid URL).
    - The server returns an error response.
    - The params argument is not a dict.
    """

def http_download(url: builtins.str, filepath: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> None:
    r"""
    Downloads a file from URL to filepath using streaming.
    
    Uses `reqwest::blocking::Client` to stream the response directly to disk,
    avoiding loading large files into memory.
    
    # Errors
    
    Returns an error if:
    - Parent directories cannot be created.
    - The HTTP client fails to build.
    - The HTTP request fails (e.g., network error, timeout, invalid URL).
    - The server returns a non-success status code.
    - The file cannot be created or written to.
    - The params argument is not a dict.
    """

def http_get(url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], timeout_secs: typing.Optional[builtins.int]) -> HttpResponse:
    r"""
    Blocking HTTP GET request.
    
    Creates an `HttpClient` internally and blocks on the async operation using a dedicated runtime.
    
    # Errors
    
    Returns an error if:
    - The HTTP client fails to initialize.
    - The dedicated runtime cannot be created or the request thread panics.
    - The HTTP request fails (e.g., network error, timeout, invalid URL).
    - The server returns an error response.
    - The params argument is not a dict.
    """

def http_patch(url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], body: typing.Optional[typing.Sequence[builtins.int]], timeout_secs: typing.Optional[builtins.int]) -> HttpResponse:
    r"""
    Blocking HTTP PATCH request.
    
    Creates an `HttpClient` internally and blocks on the async operation using a dedicated runtime.
    
    # Errors
    
    Returns an error if:
    - The HTTP client fails to initialize.
    - The dedicated runtime cannot be created or the request thread panics.
    - The HTTP request fails (e.g., network error, timeout, invalid URL).
    - The server returns an error response.
    - The params argument is not a dict.
    """

def http_post(url: builtins.str, params: typing.Optional[typing.Any], headers: typing.Optional[typing.Mapping[builtins.str, builtins.str]], body: typing.Optional[typing.Sequence[builtins.int]], timeout_secs: typing.Optional[builtins.int]) -> HttpResponse:
    r"""
    Blocking HTTP POST request.
    
    Creates an `HttpClient` internally and blocks on the async operation using a dedicated runtime.
    
    # Errors
    
    Returns an error if:
    - The HTTP client fails to initialize.
    - The dedicated runtime cannot be created or the request thread panics.
    - The HTTP request fails (e.g., network error, timeout, invalid URL).
    - The server returns an error response.
    - The params argument is not a dict.
    """

