# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
from nautilus_trader import model
import typing
__all__ = [
    "DataTesterConfig",
    "ExecTesterConfig",
    "py_ensure_file_exists_or_download_http",
]

@typing.final
class DataTesterConfig:
    r"""
    Configuration for the data tester actor.
    """
    def py_new(self, actor_id: typing.Optional[model.ActorId], client_id: typing.Optional[model.ClientId], instrument_ids: typing.Optional[typing.Sequence[model.InstrumentId]], bar_types: typing.Optional[typing.Sequence[model.BarType]], subscribe_book_deltas: typing.Optional[builtins.bool], subscribe_book_depth: typing.Optional[builtins.bool], subscribe_book_at_interval: typing.Optional[builtins.bool], subscribe_quotes: typing.Optional[builtins.bool], subscribe_trades: typing.Optional[builtins.bool], subscribe_mark_prices: typing.Optional[builtins.bool], subscribe_index_prices: typing.Optional[builtins.bool], subscribe_funding_rates: typing.Optional[builtins.bool], subscribe_bars: typing.Optional[builtins.bool], subscribe_instrument: typing.Optional[builtins.bool], subscribe_instrument_status: typing.Optional[builtins.bool], subscribe_instrument_close: typing.Optional[builtins.bool], subscribe_option_greeks: typing.Optional[builtins.bool], can_unsubscribe: typing.Optional[builtins.bool], request_instruments: typing.Optional[builtins.bool], request_quotes: typing.Optional[builtins.bool], request_trades: typing.Optional[builtins.bool], request_bars: typing.Optional[builtins.bool], request_book_snapshot: typing.Optional[builtins.bool], request_book_deltas: typing.Optional[builtins.bool], request_funding_rates: typing.Optional[builtins.bool], book_depth: typing.Optional[builtins.int], book_interval_ms: typing.Optional[builtins.int], book_levels_to_print: typing.Optional[builtins.int], manage_book: typing.Optional[builtins.bool], log_data: typing.Optional[builtins.bool], stats_interval_secs: typing.Optional[builtins.int], log_events: typing.Optional[builtins.bool], log_commands: typing.Optional[builtins.bool]) -> DataTesterConfig:
        r"""
        Configuration for the data tester actor.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExecTesterConfig:
    r"""
    Configuration for the execution tester strategy.
    """
    def py_new(self, strategy_id: typing.Optional[model.StrategyId], order_id_tag: typing.Optional[builtins.str], external_order_claims: typing.Optional[typing.Sequence[model.InstrumentId]], instrument_id: typing.Optional[model.InstrumentId], client_id: typing.Optional[model.ClientId], order_qty: typing.Optional[model.Quantity], subscribe_book: typing.Optional[builtins.bool], subscribe_quotes: typing.Optional[builtins.bool], subscribe_trades: typing.Optional[builtins.bool], open_position_on_start_qty: typing.Optional[decimal.Decimal], open_position_on_first_quote: typing.Optional[builtins.bool], open_position_time_in_force: typing.Optional[model.TimeInForce], enable_limit_buys: typing.Optional[builtins.bool], enable_limit_sells: typing.Optional[builtins.bool], enable_stop_buys: typing.Optional[builtins.bool], enable_stop_sells: typing.Optional[builtins.bool], tob_offset_ticks: typing.Optional[builtins.int], limit_time_in_force: typing.Optional[model.TimeInForce], use_post_only: typing.Optional[builtins.bool], limit_aggressive: typing.Optional[builtins.bool], cancel_orders_on_stop: typing.Optional[builtins.bool], close_positions_on_stop: typing.Optional[builtins.bool], close_positions_time_in_force: typing.Optional[model.TimeInForce], reduce_only_on_stop: typing.Optional[builtins.bool], dry_run: typing.Optional[builtins.bool], log_data: typing.Optional[builtins.bool], can_unsubscribe: typing.Optional[builtins.bool], clamp_to_instrument_price_range: typing.Optional[builtins.bool], log_events: typing.Optional[builtins.bool], log_commands: typing.Optional[builtins.bool]) -> ExecTesterConfig:
        r"""
        Configuration for the execution tester strategy.
        """
    def __repr__(self) -> builtins.str: ...

def py_ensure_file_exists_or_download_http(filepath: builtins.str, url: builtins.str, checksums: typing.Optional[builtins.str], timeout_secs: typing.Optional[builtins.int]) -> None:
    r"""
    Python wrapper for `ensure_file_exists_or_download_http`.
    
    Ensures that a file exists at the specified path by downloading it if necessary.
    
    # Errors
    
    Returns an error if:
    - The HTTP request fails or returns a non-success status code: `PyErr`.
    - Any I/O operation fails during file creation, reading, or writing: `PyErr`.
    - Checksum verification or JSON parsing fails: `PyErr`.
    """

