# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from nautilus_trader import common
from nautilus_trader import model
import typing
__all__ = [
    "BarDataWrangler",
    "DataBackendSession",
    "DataQueryResult",
    "NautilusDataType",
    "OrderBookDeltaDataWrangler",
    "OrderBookDepth10DataWrangler",
    "PyParquetDataCatalog",
    "PyStreamingFeatherWriter",
    "QuoteTickDataWrangler",
    "TradeTickDataWrangler",
]

@typing.final
class BarDataWrangler:
    def py_new(self, bar_type: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> BarDataWrangler: ...
    def bar_type(self) -> builtins.str: ...
    def price_precision(self) -> builtins.int: ...
    def size_precision(self) -> builtins.int: ...
    def process_record_batch_bytes(self, data: bytes) -> builtins.list[model.Bar]: ...

@typing.final
class DataBackendSession:
    r"""
    Provides a DataFusion session and registers DataFusion queries.
    
    The session is used to register data sources and make queries on them. A
    query returns a Chunk of Arrow records. It is decoded and converted into
    a Vec of data by types that implement [`DecodeDataFromRecordBatch`].
    """
    def new_session(self, chunk_size: builtins.int) -> DataBackendSession: ...
    def py_add_file(self, data_type: NautilusDataType, table_name: builtins.str, file_path: builtins.str, sql_query: typing.Optional[builtins.str]) -> None:
        r"""
        Registers a Parquet file and adds a batch stream for decoding.
        
        The caller must specify `T` to indicate the kind of data expected. `table_name` is
        the logical name for queries; `file_path` is the Parquet path; `sql_query` defaults
        to `SELECT * FROM {table_name} ORDER BY ts_init` if `None`.
        
        When `custom_type_name` is `Some`, it is merged into each batch's schema metadata
        before decoding (as `type_name`). Use this for custom data when Parquet/DataFusion
        does not preserve schema metadata so the decoder can look up the type in the registry.
        
        The file data must be ordered by the `ts_init` in ascending order for this
        to work correctly.
        """
    def py_add_custom_file(self, type_name: builtins.str, table_name: builtins.str, file_path: builtins.str, sql_query: typing.Optional[builtins.str]) -> None:
        r"""
        Registers a Parquet file for a custom data type identified by `type_name`.
        
        The custom data type must have been registered via
        `ensure_custom_data_registered::<T>()` before calling this method.
        """
    def to_query_result(self) -> DataQueryResult: ...
    def py_register_object_store_from_uri(self, uri: builtins.str, storage_options: typing.Optional[typing.Mapping[builtins.str, builtins.str]]) -> None:
        r"""
        Register an object store with the session context from a URI with optional storage options
        """

@typing.final
class DataQueryResult:
    def __iter__(self) -> DataQueryResult:
        r"""
        The reader implements an iterator.
        """
    def __next__(self) -> typing.Optional[typing.Any]:
        r"""
        Each iteration returns a chunk of values read from the parquet file.
        
        For built-in types, returns a PyCapsule containing a CVec of DataFFI (C layout)
        consumed by Cython `capsule_to_list`. For custom data types (which are not
        FFI-safe), returns a Python list of PyO3 objects directly.
        """

@typing.final
class OrderBookDeltaDataWrangler:
    def py_new(self, instrument_id: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> OrderBookDeltaDataWrangler: ...
    def instrument_id(self) -> builtins.str: ...
    def price_precision(self) -> builtins.int: ...
    def size_precision(self) -> builtins.int: ...
    def process_record_batch_bytes(self, data: bytes) -> builtins.list[model.OrderBookDelta]: ...

@typing.final
class OrderBookDepth10DataWrangler:
    def py_new(self, instrument_id: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> OrderBookDepth10DataWrangler: ...
    def instrument_id(self) -> builtins.str: ...
    def price_precision(self) -> builtins.int: ...
    def size_precision(self) -> builtins.int: ...
    def process_record_batch_bytes(self, data: bytes) -> builtins.list[model.OrderBookDepth10]: ...

@typing.final
class PyParquetDataCatalog:
    r"""
    A catalog for writing data to Parquet files.
    """
    def new(self, base_path: builtins.str, storage_options: typing.Optional[typing.Mapping[builtins.str, builtins.str]], batch_size: typing.Optional[builtins.int], compression: typing.Optional[builtins.int], max_row_group_size: typing.Optional[builtins.int]) -> PyParquetDataCatalog:
        r"""
        Create a new `ParquetCatalog` with the given base path and optional parameters.
        
        # Parameters
        
        - `base_path`: The base path for the catalog
        - `storage_options`: Optional storage configuration for cloud backends
        - `batch_size`: Optional batch size for processing (default: 5000)
        - `compression`: Optional compression type (0=UNCOMPRESSED, 1=SNAPPY, 2=GZIP, 3=LZO, 4=BROTLI, 5=LZ4, 6=ZSTD)
        - `max_row_group_size`: Optional maximum row group size (default: 5000)
        """
    def write_quote_ticks(self, data: typing.Sequence[model.QuoteTick], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write quote tick data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of quote ticks to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_trade_ticks(self, data: typing.Sequence[model.TradeTick], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write trade tick data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of trade ticks to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_order_book_deltas(self, data: typing.Sequence[model.OrderBookDelta], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write order book delta data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of order book deltas to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_bars(self, data: typing.Sequence[model.Bar], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write bar data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of bars to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_order_book_depths(self, data: typing.Sequence[model.OrderBookDepth10], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write order book depth data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of order book depths to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_mark_price_updates(self, data: typing.Sequence[model.MarkPriceUpdate], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write mark price update data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of mark price updates to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_index_price_updates(self, data: typing.Sequence[model.IndexPriceUpdate], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write index price update data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of index price updates to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_option_greeks(self, data: typing.Sequence[model.OptionGreeks], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write option greeks data to Parquet files.
        
        # Parameters
        
        - `data`: Vector of option greeks to write
        - `start`: Optional start timestamp override (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp override (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns the path of the created file as a string.
        """
    def write_instruments(self, data: typing.Any) -> builtins.list[builtins.str]:
        r"""
        Write instruments to Parquet files in the catalog.
        
        Instruments are stored under `data/instruments/{instrument_id}/` using timestamp-ranged
        parquet file names, allowing multiple historical versions of the same instrument to be
        written across separate calls.
        
        # Parameters
        
        - `data`: A Python list of instrument objects (e.g. CurrencyPair, Equity).
        
        # Returns
        
        Returns a list of written file paths.
        """
    def instruments(self, instrument_ids: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int]) -> builtins.list[typing.Any]:
        r"""
        Query instruments from the catalog.
        
        # Parameters
        
        - `instrument_ids`: Optional list of instrument IDs to filter by. If `None`, returns all instruments.
        - `start`: Optional inclusive lower bound for `ts_init` filtering.
        - `end`: Optional inclusive upper bound for `ts_init` filtering.
        
        # Returns
        
        Returns a list of instrument objects (e.g. CurrencyPair, Equity).
        """
    def extend_file_name(self, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str], start: builtins.int, end: builtins.int) -> None:
        r"""
        Extend file names in the catalog with additional timestamp information.
        
        # Parameters
        
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        - `start`: Start timestamp (nanoseconds since Unix epoch)
        - `end`: End timestamp (nanoseconds since Unix epoch)
        """
    def consolidate_catalog(self, start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], ensure_contiguous_files: typing.Optional[builtins.bool], deduplicate: typing.Optional[builtins.bool]) -> None:
        r"""
        Consolidate all data files in the catalog within the specified time range.
        
        # Parameters
        
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `ensure_contiguous_files`: Optional flag to ensure files are contiguous
        - `deduplicate`: Optional flag to deduplicate rows when combining files
        """
    def consolidate_data(self, type_name: builtins.str, instrument_id: typing.Optional[builtins.str], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], ensure_contiguous_files: typing.Optional[builtins.bool], deduplicate: typing.Optional[builtins.bool]) -> None:
        r"""
        Consolidate data files for a specific data type within the specified time range.
        
        # Parameters
        
        - `type_name`: The data type name to consolidate
        - `instrument_id`: Optional instrument ID filter
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `ensure_contiguous_files`: Optional flag to ensure files are contiguous
        - `deduplicate`: Optional flag to deduplicate rows when combining files
        """
    def consolidate_catalog_by_period(self, period_nanos: typing.Optional[builtins.int], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], ensure_contiguous_files: typing.Optional[builtins.bool]) -> None:
        r"""
        Consolidate all data files in the catalog by splitting them into fixed time periods.
        
        This method identifies all leaf directories in the catalog that contain parquet files
        and consolidates them by period. A leaf directory is one that contains files but no subdirectories.
        This is a convenience method that effectively calls `consolidate_data_by_period` for all data types
        and instrument IDs in the catalog.
        
        # Parameters
        
        - `period_nanos`: Optional period duration for consolidation in nanoseconds. Default is 1 day (86400000000000).
          Examples: 3600000000000 (1 hour), 604800000000000 (7 days), 1800000000000 (30 minutes)
        - `start`: Optional start timestamp for the consolidation range (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp for the consolidation range (nanoseconds since Unix epoch)
        - `ensure_contiguous_files`: Optional flag to control file naming strategy
        """
    def consolidate_data_by_period(self, type_name: builtins.str, identifier: typing.Optional[builtins.str], period_nanos: typing.Optional[builtins.int], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], ensure_contiguous_files: typing.Optional[builtins.bool]) -> None:
        r"""
        Consolidate data files by splitting them into fixed time periods.
        
        This method queries data by period and writes consolidated files immediately,
        using efficient period-based consolidation logic. When start/end boundaries intersect existing files,
        the function automatically splits those files to preserve all data.
        
        # Parameters
        
        - `type_name`: The data type directory name (e.g., "quotes", "trades", "bars")
        - `identifier`: Optional instrument ID to consolidate. If None, consolidates all instruments
        - `period_nanos`: Optional period duration for consolidation in nanoseconds. Default is 1 day (86400000000000).
          Examples: 3600000000000 (1 hour), 604800000000000 (7 days), 1800000000000 (30 minutes)
        - `start`: Optional start timestamp for consolidation range (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp for consolidation range (nanoseconds since Unix epoch)
        - `ensure_contiguous_files`: Optional flag to control file naming strategy
        """
    def reset_all_file_names(self) -> None:
        r"""
        Reset all catalog file names to their canonical form.
        """
    def reset_data_file_names(self, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str]) -> None:
        r"""
        Reset data file names for a specific data class to their canonical form.
        
        # Parameters
        
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        """
    def delete_catalog_range(self, start: typing.Optional[builtins.int], end: typing.Optional[builtins.int]) -> None:
        r"""
        Delete data within a specified time range across the entire catalog.
        
        This method identifies all leaf directories in the catalog that contain parquet files
        and deletes data within the specified time range from each directory. A leaf directory
        is one that contains files but no subdirectories. This is a convenience method that
        effectively calls `delete_data_range` for all data types and instrument IDs in the catalog.
        
        # Parameters
        
        - `start`: Optional start timestamp for the deletion range (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp for the deletion range (nanoseconds since Unix epoch)
        
        # Notes
        
        - This operation permanently removes data and cannot be undone
        - The deletion process handles file intersections intelligently by splitting files
          when they partially overlap with the deletion range
        - Files completely within the deletion range are removed entirely
        - Files partially overlapping the deletion range are split to preserve data outside the range
        - This method is useful for bulk data cleanup operations across the entire catalog
        - Empty directories are not automatically removed after deletion
        """
    def delete_data_range(self, type_name: builtins.str, instrument_id: typing.Optional[builtins.str], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int]) -> None:
        r"""
        Delete data within a specified time range for a specific data type and instrument.
        
        This method identifies all parquet files that intersect with the specified time range
        and handles them appropriately:
        - Files completely within the range are deleted
        - Files partially overlapping the range are split to preserve data outside the range
        - The original intersecting files are removed after processing
        
        # Parameters
        
        - `type_name`: The data type directory name (e.g., "quotes", "trades", "bars")
        - `instrument_id`: Optional instrument ID to delete data for. If None, deletes data across all instruments
        - `start`: Optional start timestamp for the deletion range (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp for the deletion range (nanoseconds since Unix epoch)
        
        # Notes
        
        - This operation permanently removes data and cannot be undone
        - Files that partially overlap the deletion range are split to preserve data outside the range
        - The method ensures data integrity by using atomic operations where possible
        - Empty directories are not automatically removed after deletion
        """
    def write_custom_data(self, data: typing.Sequence[typing.Any], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], skip_disjoint_check: builtins.bool) -> builtins.str:
        r"""
        Write custom data to Parquet files.
        
        Requires `CustomData` wrappers. Callers must wrap raw custom objects in
        `CustomData(data_type=DataType(cls, metadata=...), data=...)` before writing.
        """
    def list_instruments(self, data_type: builtins.str) -> builtins.list[builtins.str]:
        r"""
        List all instrument IDs available in the catalog for a given data type.
        """
    def list_parquet_files(self, data_type: builtins.str, instrument_id: builtins.str) -> builtins.list[builtins.str]:
        r"""
        List all Parquet files in the catalog for a given data type and instrument.
        """
    def query_files(self, data_cls: builtins.str, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int]) -> builtins.list[builtins.str]:
        r"""
        Query files in the catalog matching the specified criteria.
        
        # Parameters
        
        - `data_cls`: The data class name to query
        - `identifiers`: Optional list of identifiers to filter by. Can be instrument_id strings
          (e.g., "EUR/USD.SIM") or bar_type strings (e.g., "EUR/USD.SIM-1-MINUTE-LAST-EXTERNAL").
          For bars, partial matching is supported.
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        
        # Returns
        
        Returns a list of file paths matching the criteria.
        """
    def get_missing_intervals_for_request(self, start: builtins.int, end: builtins.int, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str]) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Get missing time intervals for a data request.
        
        # Parameters
        
        - `start`: Start timestamp (nanoseconds since Unix epoch)
        - `end`: End timestamp (nanoseconds since Unix epoch)
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        
        # Returns
        
        Returns a list of (start, end) timestamp tuples representing missing intervals.
        """
    def query_first_timestamp(self, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str]) -> typing.Optional[builtins.int]:
        r"""
        Query the first timestamp for a specific data class and instrument.
        
        # Parameters
        
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        
        # Returns
        
        Returns the first timestamp as nanoseconds since Unix epoch, or None if no data exists.
        """
    def query_last_timestamp(self, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str]) -> typing.Optional[builtins.int]:
        r"""
        Query the last timestamp for a specific data class and instrument.
        
        # Parameters
        
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        
        # Returns
        
        Returns the last timestamp as nanoseconds since Unix epoch, or None if no data exists.
        """
    def get_intervals(self, data_cls: builtins.str, instrument_id: typing.Optional[builtins.str]) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Get time intervals covered by data for a specific data class and instrument.
        
        # Parameters
        
        - `data_cls`: The data class name
        - `instrument_id`: Optional instrument ID filter
        
        # Returns
        
        Returns a list of (start, end) timestamp tuples representing covered intervals.
        """
    def query(self, data_type: builtins.str, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str], files: typing.Optional[typing.Sequence[builtins.str]], optimize_file_loading: builtins.bool) -> builtins.list[typing.Any]:
        r"""
        Query Parquet files for data matching the given criteria.
        """
    def query_quote_ticks(self, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.QuoteTick]:
        r"""
        Query quote tick data from Parquet files.
        
        # Parameters
        
        - `identifiers`: Optional list of identifiers to filter by. Can be instrument_id strings
          (e.g., "EUR/USD.SIM") or bar_type strings (e.g., "EUR/USD.SIM-1-MINUTE-LAST-EXTERNAL").
          For bars, partial matching is supported.
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `QuoteTick` objects matching the query criteria.
        """
    def query_trade_ticks(self, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.TradeTick]:
        r"""
        Query trade tick data from Parquet files.
        
        # Parameters
        
        - `identifiers`: Optional list of identifiers to filter by. Can be instrument_id strings
          (e.g., "EUR/USD.SIM") or bar_type strings (e.g., "EUR/USD.SIM-1-MINUTE-LAST-EXTERNAL").
          For bars, partial matching is supported.
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `TradeTick` objects matching the query criteria.
        """
    def query_order_book_deltas(self, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.OrderBookDelta]:
        r"""
        Query order book delta data from Parquet files.
        
        # Parameters
        
        - `identifiers`: Optional list of identifiers to filter by. Can be instrument_id strings
          (e.g., "EUR/USD.SIM") or bar_type strings (e.g., "EUR/USD.SIM-1-MINUTE-LAST-EXTERNAL").
          For bars, partial matching is supported.
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `OrderBookDelta` objects matching the query criteria.
        """
    def query_bars(self, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.Bar]:
        r"""
        Query bar data from Parquet files.
        
        # Parameters
        
        - `identifiers`: Optional list of identifiers to filter by. Can be instrument_id strings
          (e.g., "EUR/USD.SIM") or bar_type strings (e.g., "EUR/USD.SIM-1-MINUTE-LAST-EXTERNAL").
          For bars, partial matching is supported (e.g., "EUR/USD.SIM" will match all bar types for that instrument).
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of Bar objects matching the query criteria.
        """
    def query_order_book_depths(self, instrument_ids: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.OrderBookDepth10]:
        r"""
        Query order book depth data from Parquet files.
        
        # Parameters
        
        - `instrument_ids`: Optional list of instrument IDs to filter by
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `OrderBookDepth10` objects matching the query criteria.
        """
    def query_mark_price_updates(self, instrument_ids: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.MarkPriceUpdate]:
        r"""
        Query mark price update data from Parquet files.
        
        # Parameters
        
        - `instrument_ids`: Optional list of instrument IDs to filter by
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `MarkPriceUpdate` objects matching the query criteria.
        """
    def query_index_price_updates(self, instrument_ids: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.IndexPriceUpdate]:
        r"""
        Query index price update data from Parquet files.
        
        # Parameters
        
        - `instrument_ids`: Optional list of instrument IDs to filter by
        - `start`: Optional start timestamp (nanoseconds since Unix epoch)
        - `end`: Optional end timestamp (nanoseconds since Unix epoch)
        - `where_clause`: Optional SQL WHERE clause for additional filtering
        
        # Returns
        
        Returns a vector of `IndexPriceUpdate` objects matching the query criteria.
        """
    def query_option_greeks(self, instrument_ids: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[model.OptionGreeks]:
        r"""
        Query option greeks data from Parquet files.
        """
    def list_data_types(self) -> builtins.list[builtins.str]:
        r"""
        List all data types available in the catalog.
        
        # Returns
        
        Returns a list of data type names (as directory stems) in the catalog.
        """
    def list_live_runs(self) -> builtins.list[builtins.str]:
        r"""
        List all live run IDs available in the catalog.
        
        # Returns
        
        Returns a list of live run IDs (as directory stems) in the catalog.
        """
    def list_backtest_runs(self) -> builtins.list[builtins.str]:
        r"""
        List all backtest run IDs available in the catalog.
        
        # Returns
        
        Returns a list of backtest run IDs (as directory stems) in the catalog.
        """
    def list_backtests(self) -> builtins.list[builtins.str]:
        r"""
        List all backtest run instances available in the catalog.
        """
    def read_live_run(self, instance_id: builtins.str) -> builtins.list[typing.Any]:
        r"""
        Read data from a live run instance.
        
        # Parameters
        
        - `instance_id`: The ID of the live run instance
        
        # Returns
        
        Returns a list of data objects from the live run, sorted by timestamp.
        """
    def read_backtest(self, instance_id: builtins.str) -> builtins.list[typing.Any]:
        r"""
        Read data from a backtest run instance.
        
        # Parameters
        
        - `instance_id`: The ID of the backtest run instance
        
        # Returns
        
        Returns a list of data objects from the backtest run, sorted by timestamp.
        """
    def convert_stream_to_data(self, instance_id: builtins.str, data_cls: builtins.str, subdirectory: typing.Optional[builtins.str], identifiers: typing.Optional[typing.Sequence[builtins.str]], use_ts_event_for_ts_init: builtins.bool) -> None:
        r"""
        Convert stream data from feather files to parquet files.
        
        This method reads data from feather files generated during a backtest or live run
        and writes it to the catalog in parquet format. It's useful for converting temporary
        stream data into a more permanent and queryable format.
        
        # Parameters
        
        - `instance_id`: The ID of the backtest or live run instance
        - `data_cls`: The data class name (e.g., "quotes", "trades", "bars")
        - `subdirectory`: Optional subdirectory containing the feather files. Either "backtest" or "live" (default: "backtest")
        - `identifiers`: Optional list of identifiers to filter by (instrument IDs or bar types)
        - `use_ts_event_for_ts_init`: If true, replaces the `ts_init` column with `ts_event` column values before deserializing
        
        # Returns
        
        Returns nothing on success.
        
        # Examples
        
        ```python
        # Convert backtest stream data to parquet
        catalog.convert_stream_to_data(
            "instance-123",
            "quotes",
            subdirectory="backtest"
        )
        
        # Convert live run data with identifier filtering
        catalog.convert_stream_to_data(
            "instance-456",
            "trades",
            subdirectory="live",
            identifiers=["EUR/USD.SIM"]
        )
        ```
        """
    def query_custom_data(self, type_name: builtins.str, identifiers: typing.Optional[typing.Sequence[builtins.str]], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], where_clause: typing.Optional[builtins.str]) -> builtins.list[typing.Any]:
        r"""
        Query custom data from Parquet files.
        """

@typing.final
class PyStreamingFeatherWriter:
    r"""
    Python binding for the Rust `FeatherWriter`.
    
    This provides a streaming writer of Nautilus objects into feather files with rotation
    capabilities, matching the interface of Python's `StreamingFeatherWriter`.
    """
    def new(self, path: builtins.str, cache: common.PyCache, clock: common.PyClock, fs_protocol: typing.Optional[builtins.str], fs_storage_options: typing.Optional[typing.Mapping[builtins.str, builtins.str]], include_types: typing.Optional[typing.Sequence[builtins.str]], rotation_mode: builtins.int, max_file_size: builtins.int, rotation_interval_ns: typing.Optional[builtins.int], rotation_time_ns: typing.Optional[builtins.int], rotation_timezone: builtins.str, flush_interval_ms: typing.Optional[builtins.int], replace: builtins.bool) -> PyStreamingFeatherWriter:
        r"""
        Creates a new `StreamingFeatherWriter` instance.
        
        # Parameters
        
        - `path`: The path to persist the stream to. Must be a directory.
        - `cache`: The cache for query info (PyCache).
        - `clock`: The clock to use for time-related operations (PyClock).
        - `fs_protocol`: Optional filesystem protocol (default: "file").
        - `fs_storage_options`: Optional storage options for cloud backends.
        - `include_types`: Optional list of type names to include (e.g., ["quotes", "trades"]).
        - `rotation_mode`: Rotation mode (0=SIZE, 1=INTERVAL, 2=SCHEDULED_DATES, 3=NO_ROTATION).
        - `max_file_size`: Maximum file size in bytes before rotation (for SIZE mode).
        - `rotation_interval_ns`: Rotation interval in nanoseconds (for INTERVAL/SCHEDULED_DATES modes).
        - `rotation_time_ns`: Scheduled rotation time in nanoseconds (for SCHEDULED_DATES mode).
        - `flush_interval_ms`: Flush interval in milliseconds (default: 1000). Set to 0 to disable auto-flush.
        - `replace`: If existing files at the given path should be replaced (default: False).
        """
    def subscribe(self) -> None:
        r"""
        Subscribes to all messages on the message bus (pattern "*").
        
        This matches the behavior of Python's StreamingFeatherWriter when subscribed
        via `trader.subscribe("*", writer.write)`.
        """
    def unsubscribe(self) -> None:
        r"""
        Unsubscribes from the message bus.
        """
    def write(self, data: typing.Any) -> None:
        r"""
        Writes a data object to the stream.
        
        # Parameters
        
        - `data`: The data object to write (must be a Nautilus data type from pyo3).
        """
    def flush(self) -> None:
        r"""
        Flushes all active buffers by writing any remaining buffered bytes to the object store.
        
        This is called automatically based on `flush_interval_ms` if configured, but can also
        be called manually by the client.
        """
    def close(self) -> None:
        r"""
        Closes all writers by flushing and removing them.
        
        After calling this, no further writes should be performed.
        """
    def is_closed(self) -> builtins.bool:
        r"""
        Returns whether the writer has been closed (no active writers).
        """
    def get_current_file_info(self) -> builtins.dict[builtins.str, tuple[builtins.int, builtins.str]]:
        r"""
        Returns information about the current files being written.
        
        Returns a dictionary mapping writer keys to (size, path) tuples.
        """
    def get_next_rotation_time(self, type_str: builtins.str, instrument_id: typing.Optional[builtins.str]) -> typing.Optional[builtins.int]:
        r"""
        Returns the next rotation time for a writer, or None if not set.
        """

@typing.final
class QuoteTickDataWrangler:
    def py_new(self, instrument_id: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> QuoteTickDataWrangler: ...
    def instrument_id(self) -> builtins.str: ...
    def price_precision(self) -> builtins.int: ...
    def size_precision(self) -> builtins.int: ...
    def process_record_batch_bytes(self, data: bytes) -> builtins.list[model.QuoteTick]: ...

@typing.final
class TradeTickDataWrangler:
    def py_new(self, instrument_id: builtins.str, price_precision: builtins.int, size_precision: builtins.int) -> TradeTickDataWrangler: ...
    def instrument_id(self) -> builtins.str: ...
    def price_precision(self) -> builtins.int: ...
    def size_precision(self) -> builtins.int: ...
    def process_record_batch_bytes(self, data: bytes) -> builtins.list[model.TradeTick]: ...

@typing.final
class NautilusDataType(enum.Enum):
    OrderBookDelta = ...
    OrderBookDepth10 = ...
    QuoteTick = ...
    TradeTick = ...
    Bar = ...
    MarkPriceUpdate = ...
    InstrumentStatus = ...
    OptionGreeks = ...

    def __hash__(self) -> builtins.int: ...

