# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import enum
import typing
__all__ = [
    "AlpacaDataClientConfig",
    "AlpacaDataFeed",
    "AlpacaExecutionClientConfig",
]

@typing.final
class AlpacaDataClientConfig:
    ...

@typing.final
class AlpacaExecutionClientConfig:
    ...

@typing.final
class AlpacaDataFeed(enum.Enum):
    Iex = ...
    Sip = ...

