# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "MassiveDataClientConfig",
    "MassiveDataClientFactory",
]

@typing.final
class MassiveDataClientConfig:
    ...

@typing.final
class MassiveDataClientFactory:
    r"""
    Factory for creating Massive data clients.
    """
    ...

