# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
from nautilus_trader import model
import typing
__all__ = [
    "BetfairDataClientFactory",
    "BetfairDataConfig",
    "BetfairExecConfig",
    "BetfairExecutionClientFactory",
]

@typing.final
class BetfairDataClientFactory:
    r"""
    Factory for creating Betfair data clients.
    """
    def py_new(self) -> BetfairDataClientFactory:
        r"""
        Factory for creating Betfair data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BetfairDataConfig:
    r"""
    Configuration for the Betfair live data client.
    """
    def py_new(self, account_currency: typing.Optional[builtins.str], username: typing.Optional[builtins.str], password: typing.Optional[builtins.str], app_key: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], request_rate_per_second: builtins.int, default_min_notional: typing.Optional[decimal.Decimal], event_type_ids: typing.Optional[typing.Sequence[builtins.int]], event_type_names: typing.Optional[typing.Sequence[builtins.str]], event_ids: typing.Optional[typing.Sequence[builtins.int]], country_codes: typing.Optional[typing.Sequence[builtins.str]], market_types: typing.Optional[typing.Sequence[builtins.str]], market_ids: typing.Optional[typing.Sequence[builtins.str]], min_market_start_time: typing.Optional[builtins.str], max_market_start_time: typing.Optional[builtins.str], stream_host: typing.Optional[builtins.str], stream_port: typing.Optional[builtins.int], stream_heartbeat_ms: builtins.int, stream_idle_timeout_ms: builtins.int, stream_reconnect_delay_initial_ms: builtins.int, stream_reconnect_delay_max_ms: builtins.int, stream_use_tls: builtins.bool, stream_conflate_ms: typing.Optional[builtins.int], subscription_delay_secs: typing.Optional[builtins.int], subscribe_race_data: builtins.bool) -> BetfairDataConfig:
        r"""
        Configuration for the Betfair live data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BetfairExecConfig:
    r"""
    Configuration for the Betfair live execution client.
    """
    def py_new(self, trader_id: typing.Optional[model.TraderId], account_id: typing.Optional[model.AccountId], account_currency: typing.Optional[builtins.str], username: typing.Optional[builtins.str], password: typing.Optional[builtins.str], app_key: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], request_rate_per_second: builtins.int, order_request_rate_per_second: builtins.int, stream_host: typing.Optional[builtins.str], stream_port: typing.Optional[builtins.int], stream_heartbeat_ms: builtins.int, stream_idle_timeout_ms: builtins.int, stream_reconnect_delay_initial_ms: builtins.int, stream_reconnect_delay_max_ms: builtins.int, stream_use_tls: builtins.bool, stream_market_ids_filter: typing.Optional[typing.Sequence[builtins.str]], ignore_external_orders: builtins.bool, calculate_account_state: builtins.bool, request_account_state_secs: builtins.int, reconcile_market_ids_only: builtins.bool, reconcile_market_ids: typing.Optional[typing.Sequence[builtins.str]], use_market_version: builtins.bool, stream_gap_recovery_lookback_mins: builtins.int) -> BetfairExecConfig:
        r"""
        Configuration for the Betfair live execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BetfairExecutionClientFactory:
    r"""
    Factory for creating Betfair execution clients.
    """
    def py_new(self) -> BetfairExecutionClientFactory:
        r"""
        Factory for creating Betfair execution clients.
        """
    def py_name(self) -> builtins.str: ...

