# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
import enum
from nautilus_trader import model
import typing
__all__ = [
    "CoinbaseDataClientConfig",
    "CoinbaseDataClientFactory",
    "CoinbaseEnvironment",
    "CoinbaseExecClientConfig",
    "CoinbaseExecutionClientFactory",
    "CoinbaseHttpClient",
    "CoinbaseMarginType",
    "CoinbaseWebSocketClient",
]

@typing.final
class CoinbaseDataClientConfig:
    r"""
    Configuration for the Coinbase data client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_rest: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[CoinbaseEnvironment], http_timeout_secs: typing.Optional[builtins.int], ws_timeout_secs: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], derivatives_poll_interval_secs: typing.Optional[builtins.int]) -> CoinbaseDataClientConfig:
        r"""
        Configuration for the Coinbase live data client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the optional proxy URL for HTTP and WebSocket transports.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CoinbaseDataClientFactory:
    r"""
    Factory for creating Coinbase data clients.
    """
    def py_new(self) -> CoinbaseDataClientFactory:
        r"""
        Factory for creating Coinbase data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class CoinbaseExecClientConfig:
    r"""
    Configuration for the Coinbase execution client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_rest: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[CoinbaseEnvironment], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], account_type: typing.Optional[model.AccountType], default_margin_type: typing.Optional[CoinbaseMarginType], default_leverage: typing.Optional[decimal.Decimal], retail_portfolio_id: typing.Optional[builtins.str]) -> CoinbaseExecClientConfig:
        r"""
        Configuration for the Coinbase live execution client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the optional proxy URL for HTTP and WebSocket transports.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CoinbaseExecutionClientFactory:
    r"""
    Factory for creating Coinbase execution clients.
    
    Dispatches the spot vs derivatives (CFM) scope from the config's
    [`AccountType`]: `Cash` bootstraps spot products and uses the
    `/accounts` endpoint; `Margin` bootstraps perpetual and dated futures,
    subscribes to the `futures_balance_summary` WebSocket channel, and
    produces position reports from the CFM endpoints. Other account types
    are rejected. Hedge mode is not exposed by the venue, so OMS is always
    `Netting`.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId) -> CoinbaseExecutionClientFactory:
        r"""
        Factory for creating Coinbase execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class CoinbaseHttpClient:
    r"""
    Provides a domain-level HTTP client for the Coinbase Advanced Trade API.
    
    Wraps [`CoinbaseRawHttpClient`] in an `Arc` and adds instrument caching
    and Nautilus type conversions. This is the primary HTTP interface for the
    data and execution clients.
    """
    ...

@typing.final
class CoinbaseWebSocketClient:
    r"""
    WebSocket client for Coinbase Advanced Trade market data and user streams.
    
    Manages connection lifecycle, subscription state, and JWT authentication.
    Spawns a [`FeedHandler`] task that parses raw messages into Nautilus types.
    """
    ...

@typing.final
class CoinbaseEnvironment(enum.Enum):
    r"""
    Coinbase environment type.
    """
    Live = ...
    r"""
    Production environment.
    """
    Sandbox = ...
    r"""
    Sandbox/testing environment.
    """

    def py_new(self) -> CoinbaseEnvironment:
        r"""
        Coinbase environment selection (live vs sandbox).
        """
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...

@typing.final
class CoinbaseMarginType(enum.Enum):
    r"""
    Coinbase order margin type.
    """
    Cross = ...
    Isolated = ...

