# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
from nautilus_trader import model
import typing
__all__ = [
    "BestPriceFillModel",
    "CappedOptionFeeModel",
    "CompetitionAwareFillModel",
    "DefaultFillModel",
    "ExecutionEngineConfig",
    "FixedFeeModel",
    "LimitOrderPartialFillModel",
    "MakerTakerFeeModel",
    "MarketHoursFillModel",
    "OneTickSlippageFillModel",
    "OrderEmulatorConfig",
    "PerContractFeeModel",
    "ProbabilisticFillModel",
    "SizeAwareFillModel",
    "StaticLatencyModel",
    "ThreeTierFillModel",
    "TieredNotionalOptionFeeModel",
    "TwoTierFillModel",
    "VolumeSensitiveFillModel",
    "py_calculate_reconciliation_price",
    "py_create_inferred_reconciliation_trade_id",
    "py_create_position_reconciliation_venue_order_id",
    "py_process_mass_status_for_reconciliation",
]

@typing.final
class BestPriceFillModel:
    r"""
    Fill model that executes all orders at the best available price with unlimited liquidity.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> BestPriceFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class CappedOptionFeeModel:
    def py_new(self, maker_rate: typing.Optional[decimal.Decimal], taker_rate: typing.Optional[decimal.Decimal], cap_rate: typing.Optional[decimal.Decimal]) -> CappedOptionFeeModel:
        r"""
        Creates a new `CappedOptionFeeModel` instance.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CompetitionAwareFillModel:
    r"""
    Fill model that reduces available liquidity by a factor to simulate market competition.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int], liquidity_factor: builtins.float) -> CompetitionAwareFillModel:
        r"""
        Fill model that reduces available liquidity by a factor to simulate market competition.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefaultFillModel:
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> DefaultFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExecutionEngineConfig:
    r"""
    Configuration for `ExecutionEngine` instances.
    """
    def py_new(self, load_cache: typing.Optional[builtins.bool], manage_own_order_books: typing.Optional[builtins.bool], snapshot_orders: typing.Optional[builtins.bool], snapshot_positions: typing.Optional[builtins.bool], snapshot_positions_interval_secs: typing.Optional[builtins.float], allow_overfills: typing.Optional[builtins.bool], external_clients: typing.Optional[typing.Sequence[model.ClientId]], purge_closed_orders_interval_mins: typing.Optional[builtins.int], purge_closed_orders_buffer_mins: typing.Optional[builtins.int], purge_closed_positions_interval_mins: typing.Optional[builtins.int], purge_closed_positions_buffer_mins: typing.Optional[builtins.int], purge_account_events_interval_mins: typing.Optional[builtins.int], purge_account_events_lookback_mins: typing.Optional[builtins.int], purge_from_database: typing.Optional[builtins.bool], debug: typing.Optional[builtins.bool]) -> ExecutionEngineConfig:
        r"""
        Configuration for `ExecutionEngine` instances.
        """
    def py_load_cache(self) -> builtins.bool: ...
    def py_manage_own_order_books(self) -> builtins.bool: ...
    def py_snapshot_orders(self) -> builtins.bool: ...
    def py_snapshot_positions(self) -> builtins.bool: ...
    def py_snapshot_positions_interval_secs(self) -> typing.Optional[builtins.float]: ...
    def py_allow_overfills(self) -> builtins.bool: ...
    def py_purge_from_database(self) -> builtins.bool: ...
    def py_debug(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class FixedFeeModel:
    def py_new(self, commission: model.Money, change_commission_once: typing.Optional[builtins.bool]) -> FixedFeeModel:
        r"""
        Creates a new `FixedFeeModel` instance.
        
        # Errors
        
        Returns an error if `commission` is negative.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class LimitOrderPartialFillModel:
    r"""
    Fill model that simulates partial fills: max 5 contracts at best, unlimited one tick worse.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> LimitOrderPartialFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MakerTakerFeeModel:
    def py_new(self) -> MakerTakerFeeModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MarketHoursFillModel:
    r"""
    Fill model that simulates varying conditions based on market hours.
    During low liquidity: wider spreads (one tick worse). Normal hours: standard liquidity.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> MarketHoursFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OneTickSlippageFillModel:
    r"""
    Fill model that forces exactly one tick of slippage for all orders.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> OneTickSlippageFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class OrderEmulatorConfig:
    r"""
    Configuration for `OrderEmulator` instances.
    """
    def py_new(self, debug: typing.Optional[builtins.bool]) -> OrderEmulatorConfig:
        r"""
        Configuration for `OrderEmulator` instances.
        """
    def py_debug(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class PerContractFeeModel:
    def py_new(self, commission: model.Money) -> PerContractFeeModel:
        r"""
        Creates a new `PerContractFeeModel` instance.
        
        # Errors
        
        Returns an error if `commission` is negative.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProbabilisticFillModel:
    r"""
    Fill model with 50/50 chance of best price fill or one tick slippage.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> ProbabilisticFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SizeAwareFillModel:
    r"""
    Fill model that applies different execution based on order size.
    Small orders (<=10) get 50 contracts at best. Large orders get 10 at best, remainder at +1 tick.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> SizeAwareFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class StaticLatencyModel:
    r"""
    Static latency model with fixed latency values.
    
    Models the latency for different order operations including base network latency
    and specific operation latencies for insert, update, and delete operations.
    
    The base latency is automatically added to each operation latency, matching
    Python's behavior. For example, if `base_latency_nanos = 100ms` and
    `insert_latency_nanos = 200ms`, the effective insert latency will be 300ms.
    """
    def py_new(self, base_latency_nanos: builtins.int, insert_latency_nanos: builtins.int, update_latency_nanos: builtins.int, cancel_latency_nanos: builtins.int) -> StaticLatencyModel:
        r"""
        Static latency model with fixed latency values.
        
        Models the latency for different order operations including base network latency
        and specific operation latencies for insert, update, and delete operations.
        
        The base latency is automatically added to each operation latency, matching
        Python's behavior. For example, if `base_latency_nanos = 100ms` and
        `insert_latency_nanos = 200ms`, the effective insert latency will be 300ms.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ThreeTierFillModel:
    r"""
    Fill model with three tiers: 50 at best, 30 at +1 tick, 20 at +2 ticks.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> ThreeTierFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TieredNotionalOptionFeeModel:
    def py_new(self, maker_rate: typing.Optional[decimal.Decimal], taker_rate: typing.Optional[decimal.Decimal]) -> TieredNotionalOptionFeeModel:
        r"""
        Creates a new `TieredNotionalOptionFeeModel` instance.
        
        # Errors
        
        Returns an error if any supplied rate is negative.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TwoTierFillModel:
    r"""
    Fill model with two tiers: first 10 contracts at best price, remainder one tick worse.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> TwoTierFillModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class VolumeSensitiveFillModel:
    r"""
    Fill model that adjusts liquidity based on recent trading volume.
    Uses 25% of recent volume at best price, unlimited one tick worse.
    """
    def py_new(self, prob_fill_on_limit: builtins.float, prob_slippage: builtins.float, random_seed: typing.Optional[builtins.int]) -> VolumeSensitiveFillModel: ...
    def __repr__(self) -> builtins.str: ...

def py_calculate_reconciliation_price(current_position_qty: decimal.Decimal, current_position_avg_px: typing.Optional[decimal.Decimal], target_position_qty: decimal.Decimal, target_position_avg_px: typing.Optional[decimal.Decimal]) -> typing.Optional[decimal.Decimal]:
    r"""
    Calculate the price needed for a reconciliation order to achieve target position.
    
    This is a pure function that calculates what price a fill would need to have
    to move from the current position state to the target position state with the
    correct average price, accounting for the netting simulation logic.
    
    # Returns
    
    Returns `Some(Decimal)` if a valid reconciliation price can be calculated, `None` otherwise.
    
    # Notes
    
    The function handles four scenarios:
    1. Position to flat: `reconciliation_px` = `current_avg_px` (close at current average)
    2. Flat to position: `reconciliation_px` = `target_avg_px`
    3. Position flip (sign change): `reconciliation_px` = `target_avg_px` (due to value reset in simulation)
    4. Accumulation/reduction: weighted average formula
    """

def py_create_inferred_reconciliation_trade_id(account_id: model.AccountId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId], order_side: model.OrderSide, order_type: model.OrderType, filled_qty: model.Quantity, last_qty: model.Quantity, last_px: model.Price, position_id: model.PositionId, ts_last: builtins.int) -> model.TradeId:
    r"""
    Create a deterministic `TradeId` for an inferred reconciliation fill.
    
    The `account_id` scopes the ID to the venue account, preventing cross-account
    collisions on venues where `venue_order_id` is only account-unique. The `ts_last`
    (venue-provided) differentiates successive reconciliation incidents with the same
    shape while keeping cross-restart replays deterministic.
    """

def py_create_position_reconciliation_venue_order_id(account_id: model.AccountId, instrument_id: model.InstrumentId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, price: typing.Optional[model.Price], venue_position_id: typing.Optional[model.PositionId], ts_last: builtins.int, tag: typing.Optional[builtins.str]) -> model.VenueOrderId:
    r"""
    The `account_id` scopes the ID to the venue account, preventing cross-account
    collisions where the engine would otherwise fall back to `ClientOrderId::from(venue_order_id)`
    and conflate orders from different accounts. The `ts_last` (venue-provided) ensures that
    successive reconciliation incidents with the same shape get distinct IDs, while the same
    logical event replayed after restart still hashes the same (venue re-reports identical ts).
    """

def py_process_mass_status_for_reconciliation(mass_status: typing.Any, instrument: typing.Any, tolerance: typing.Optional[builtins.str]) -> tuple:
    r"""
    Process fill reports from a mass status for position reconciliation.
    
    This is the main entry point for position reconciliation. It:
    1. Extracts fills and position for the given instrument
    2. Detects position discrepancies
    3. Returns adjusted order/fill reports ready for processing
    """

