# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import enum
from nautilus_trader import model
import typing
__all__ = [
    "BitmexDataClientConfig",
    "BitmexDataClientFactory",
    "BitmexEnvironment",
    "BitmexExecClientConfig",
    "BitmexExecFactoryConfig",
    "BitmexExecutionClientFactory",
    "BitmexHttpClient",
    "BitmexPositionSide",
    "BitmexSymbolStatus",
    "CancelBroadcaster",
    "PyBitmexWebSocketClient",
    "SubmitBroadcaster",
    "get_bitmex_http_base_url",
    "get_bitmex_ws_url",
]

@typing.final
class BitmexDataClientConfig:
    r"""
    Configuration for the BitMEX live data client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], active_only: typing.Optional[builtins.bool], update_instruments_interval_mins: typing.Optional[builtins.int], environment: typing.Optional[BitmexEnvironment], max_requests_per_second: typing.Optional[builtins.int], max_requests_per_minute: typing.Optional[builtins.int]) -> BitmexDataClientConfig:
        r"""
        Configuration for the BitMEX live data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BitmexDataClientFactory:
    r"""
    Factory for creating BitMEX data clients.
    """
    def py_new(self) -> BitmexDataClientFactory:
        r"""
        Factory for creating BitMEX data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BitmexExecClientConfig:
    r"""
    Configuration for the BitMEX live execution client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], active_only: typing.Optional[builtins.bool], environment: typing.Optional[BitmexEnvironment], account_id: typing.Optional[model.AccountId], max_requests_per_second: typing.Optional[builtins.int], max_requests_per_minute: typing.Optional[builtins.int], submitter_pool_size: typing.Optional[builtins.int], canceller_pool_size: typing.Optional[builtins.int], submitter_proxy_urls: typing.Optional[typing.Sequence[builtins.str]], canceller_proxy_urls: typing.Optional[typing.Sequence[builtins.str]], deadmans_switch_timeout_secs: typing.Optional[builtins.int]) -> BitmexExecClientConfig:
        r"""
        Configuration for the BitMEX live execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BitmexExecFactoryConfig:
    r"""
    Configuration for creating BitMEX execution clients via factory.
    
    This wraps [`BitmexExecClientConfig`] with the additional trader and account
    identifiers required by the [`ExecutionClientCore`].
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, config: BitmexExecClientConfig) -> BitmexExecFactoryConfig:
        r"""
        Configuration for creating BitMEX execution clients via factory.
        
        This wraps `BitmexExecClientConfig` with the additional trader and account
        identifiers required by the `ExecutionClientCore`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BitmexExecutionClientFactory:
    r"""
    Factory for creating BitMEX execution clients.
    """
    def py_new(self) -> BitmexExecutionClientFactory:
        r"""
        Factory for creating BitMEX execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BitmexHttpClient:
    r"""
    Provides a HTTP client for connecting to the [BitMEX](https://bitmex.com) REST API.
    
    This is the high-level client that wraps the inner client and provides
    Nautilus-specific functionality for trading operations.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], environment: BitmexEnvironment, timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, recv_window_ms: builtins.int, max_requests_per_second: builtins.int, max_requests_per_minute: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BitmexHttpClient:
        r"""
        Provides a HTTP client for connecting to the [BitMEX](https://bitmex.com) REST API.
        
        This is the high-level client that wraps the inner client and provides
        Nautilus-specific functionality for trading operations.
        """
    def py_from_env(self) -> BitmexHttpClient:
        r"""
        Creates a new `BitmexHttpClient` instance using environment variables and
        the default BitMEX HTTP base URL.
        
        # Errors
        
        Returns an error if required environment variables are not set or invalid.
        """
    def py_base_url(self) -> builtins.str:
        r"""
        Returns the base url being used by the client.
        """
    def py_api_key(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the public API key being used by the client.
        """
    def py_api_key_masked(self) -> typing.Optional[builtins.str]:
        r"""
        Returns a masked version of the API key for logging purposes.
        """
    def py_update_position_leverage(self, _symbol: builtins.str, _leverage: builtins.float) -> typing.Any:
        r"""
        Update position leverage.
        """
    def py_request_instrument(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Request a single instrument and parse it into a Nautilus type.
        """
    def py_request_instruments(self, active_only: builtins.bool) -> typing.Any:
        r"""
        Request all available instruments and parse them into Nautilus types.
        """
    def py_request_trades(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request trades for the given instrument.
        """
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int], partial: builtins.bool) -> typing.Any:
        r"""
        Request bars for the given bar type.
        """
    def py_query_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Query a single order by client order ID or venue order ID.
        """
    def py_request_order_status_reports(self, instrument_id: typing.Optional[model.InstrumentId], open_only: builtins.bool, limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request multiple order status reports.
        """
    def py_request_fill_reports(self, instrument_id: typing.Optional[model.InstrumentId], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request fill reports for the given instrument.
        """
    def py_request_position_status_reports(self) -> typing.Any:
        r"""
        Request position reports.
        """
    def py_submit_order(self, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], trailing_offset: typing.Optional[builtins.float], trailing_offset_type: typing.Optional[model.TrailingOffsetType], display_qty: typing.Optional[model.Quantity], post_only: builtins.bool, reduce_only: builtins.bool, order_list_id: typing.Optional[model.OrderListId], contingency_type: typing.Optional[model.ContingencyType], peg_price_type: typing.Optional[builtins.str], peg_offset_value: typing.Optional[builtins.float]) -> typing.Any:
        r"""
        Submit a new order.
        """
    def py_cancel_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancel an order.
        """
    def py_cancel_orders(self, instrument_id: model.InstrumentId, client_order_ids: typing.Optional[typing.Sequence[model.ClientOrderId]], venue_order_ids: typing.Optional[typing.Sequence[model.VenueOrderId]]) -> typing.Any:
        r"""
        Cancel multiple orders.
        """
    def py_cancel_all_orders(self, instrument_id: model.InstrumentId, order_side: typing.Optional[model.OrderSide]) -> typing.Any:
        r"""
        Cancel all orders for an instrument and optionally an order side.
        """
    def py_modify_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Modify an existing order.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches a single instrument.
        
        Any existing instrument with the same symbol will be replaced.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancel all pending HTTP requests.
        """
    def py_get_margin(self, currency: builtins.str) -> typing.Any:
        r"""
        Get user margin information for a specific currency.
        
        # Errors
        
        Returns an error if credentials are missing, the request fails, or the API returns an error.
        """
    def py_get_account_number(self) -> typing.Any: ...
    def py_request_account_state(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Request account state for the given account.
        """
    def py_submit_orders_bulk(self, orders: typing.Sequence[typing.Any]) -> typing.Any: ...
    def py_modify_orders_bulk(self, orders: typing.Sequence[typing.Any]) -> typing.Any: ...
    def py_cancel_all_after(self, timeout_ms: builtins.int) -> typing.Any:
        r"""
        Sets the dead man's switch (cancel all orders after timeout).
        
        Calling with `timeout_ms=0` disarms the switch.
        """
    def py_get_server_time(self) -> typing.Any:
        r"""
        Requests the current server time from BitMEX.
        
        Returns the BitMEX system time as a Unix timestamp in milliseconds.
        
        # Errors
        
        Returns an error if the HTTP request fails or if the response cannot be parsed.
        """

@typing.final
class CancelBroadcaster:
    r"""
    Broadcasts cancel requests to multiple HTTP clients for redundancy.
    
    This broadcaster fans out cancel requests to multiple pre-warmed HTTP clients
    in parallel, short-circuits when the first successful acknowledgement is received,
    and handles expected rejection patterns with appropriate log levels.
    """
    def py_new(self, pool_size: builtins.int, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], environment: BitmexEnvironment, timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, recv_window_ms: builtins.int, max_requests_per_second: builtins.int, max_requests_per_minute: builtins.int, health_check_interval_secs: builtins.int, health_check_timeout_secs: builtins.int, expected_reject_patterns: typing.Optional[typing.Sequence[builtins.str]], idempotent_success_patterns: typing.Optional[typing.Sequence[builtins.str]], proxy_urls: typing.Optional[typing.Sequence[typing.Optional[builtins.str]]]) -> CancelBroadcaster:
        r"""
        Broadcasts cancel requests to multiple HTTP clients for redundancy.
        
        This broadcaster fans out cancel requests to multiple pre-warmed HTTP clients
        in parallel, short-circuits when the first successful acknowledgement is received,
        and handles expected rejection patterns with appropriate log levels.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument in all HTTP clients in the pool.
        """
    def py_start(self) -> typing.Any:
        r"""
        Starts the broadcaster and health check loop.
        
        # Errors
        
        Returns an error if the broadcaster is already running.
        """
    def py_stop(self) -> typing.Any:
        r"""
        Stops the broadcaster and health check loop.
        """
    def py_broadcast_cancel(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Broadcasts a single cancel request to all healthy clients in parallel.
        
        # Returns
        
        - `Ok(Some(report))` if successfully cancelled with a report.
        - `Ok(None)` if the order was already cancelled (idempotent success).
        - `Err` if all requests failed.
        """
    def py_broadcast_batch_cancel(self, instrument_id: model.InstrumentId, client_order_ids: typing.Optional[typing.Sequence[model.ClientOrderId]], venue_order_ids: typing.Optional[typing.Sequence[model.VenueOrderId]]) -> typing.Any:
        r"""
        Broadcasts a batch cancel request to all healthy clients in parallel.
        """
    def py_broadcast_cancel_all(self, instrument_id: model.InstrumentId, order_side: typing.Optional[model.OrderSide]) -> typing.Any:
        r"""
        Broadcasts a cancel all request to all healthy clients in parallel.
        """
    def py_get_metrics(self) -> typing.Any:
        r"""
        Gets broadcaster metrics.
        """
    def py_get_client_stats(self) -> typing.Any:
        r"""
        Gets per-client statistics.
        """

@typing.final
class PyBitmexWebSocketClient:
    r"""
    Python wrapper around [`BitmexWebSocketClient`] that holds an instrument cache
    at the Python boundary for parsing venue messages into Nautilus domain types.
    """
    def py_new(self, url: typing.Optional[builtins.str], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], account_id: typing.Optional[model.AccountId], heartbeat: builtins.int, environment: BitmexEnvironment, proxy_url: typing.Optional[builtins.str]) -> PyBitmexWebSocketClient: ...
    def py_from_env(self) -> PyBitmexWebSocketClient: ...
    def py_url(self) -> builtins.str: ...
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_is_active(self) -> builtins.bool: ...
    def py_is_closed(self) -> builtins.bool: ...
    def py_get_subscriptions(self, instrument_id: model.InstrumentId) -> builtins.list[builtins.str]: ...
    def py_set_account_id(self, account_id: model.AccountId) -> None: ...
    def py_register_order_identity(self, client_order_id: model.ClientOrderId, instrument_id: model.InstrumentId, strategy_id: model.StrategyId, order_side: model.OrderSide, order_type: model.OrderType) -> None: ...
    def py_remove_order_identity(self, client_order_id: model.ClientOrderId) -> None: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None: ...
    def py_connect(self, loop_: typing.Any, instruments: typing.Sequence[typing.Any], callback: typing.Any, trader_id: typing.Optional[model.TraderId]) -> typing.Any: ...
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any: ...
    def py_close(self) -> typing.Any: ...
    def py_subscribe_instruments(self) -> typing.Any: ...
    def py_subscribe_instrument(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book_25(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book_depth10(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_unsubscribe_instruments(self) -> typing.Any: ...
    def py_unsubscribe_instrument(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book_25(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book_depth10(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_subscribe_orders(self) -> typing.Any: ...
    def py_subscribe_executions(self) -> typing.Any: ...
    def py_subscribe_positions(self) -> typing.Any: ...
    def py_subscribe_margin(self) -> typing.Any: ...
    def py_subscribe_wallet(self) -> typing.Any: ...
    def py_unsubscribe_orders(self) -> typing.Any: ...
    def py_unsubscribe_executions(self) -> typing.Any: ...
    def py_unsubscribe_positions(self) -> typing.Any: ...
    def py_unsubscribe_margin(self) -> typing.Any: ...
    def py_unsubscribe_wallet(self) -> typing.Any: ...

@typing.final
class SubmitBroadcaster:
    r"""
    Broadcasts submit requests to multiple HTTP clients for redundancy.
    
    This broadcaster fans out submit requests to multiple pre-warmed HTTP clients
    in parallel, short-circuits when the first successful acknowledgement is received,
    and handles expected rejection patterns (duplicate clOrdID) with appropriate log levels.
    """
    def py_new(self, pool_size: builtins.int, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], environment: BitmexEnvironment, timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, recv_window_ms: builtins.int, max_requests_per_second: builtins.int, max_requests_per_minute: builtins.int, health_check_interval_secs: builtins.int, health_check_timeout_secs: builtins.int, expected_reject_patterns: typing.Optional[typing.Sequence[builtins.str]], proxy_urls: typing.Optional[typing.Sequence[typing.Optional[builtins.str]]]) -> SubmitBroadcaster:
        r"""
        Broadcasts submit requests to multiple HTTP clients for redundancy.
        
        This broadcaster fans out submit requests to multiple pre-warmed HTTP clients
        in parallel, short-circuits when the first successful acknowledgement is received,
        and handles expected rejection patterns (duplicate clOrdID) with appropriate log levels.
        """
    def py_start(self) -> typing.Any:
        r"""
        Starts the broadcaster and health check loop.
        
        # Errors
        
        Returns an error if the broadcaster is already running.
        """
    def py_stop(self) -> typing.Any:
        r"""
        Stops the broadcaster and health check loop.
        """
    def py_broadcast_submit(self, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], trailing_offset: typing.Optional[builtins.float], trailing_offset_type: typing.Optional[model.TrailingOffsetType], display_qty: typing.Optional[model.Quantity], post_only: builtins.bool, reduce_only: builtins.bool, order_list_id: typing.Optional[model.OrderListId], contingency_type: typing.Optional[model.ContingencyType], submit_tries: typing.Optional[builtins.int], peg_price_type: typing.Optional[builtins.str], peg_offset_value: typing.Optional[builtins.float]) -> typing.Any:
        r"""
        Broadcasts a submit request to all healthy clients in parallel.
        
        # Returns
        
        - `Ok(report)` if successfully submitted with a report.
        - `Err` if all requests failed.
        """
    def py_get_metrics(self) -> typing.Any:
        r"""
        Gets broadcaster metrics.
        """
    def py_get_client_stats(self) -> typing.Any:
        r"""
        Gets per-client statistics.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches an instrument in all HTTP clients in the pool.
        """

@typing.final
class BitmexEnvironment(enum.Enum):
    r"""
    BitMEX API environment.
    """
    Mainnet = ...
    r"""
    Live trading environment.
    """
    Testnet = ...
    r"""
    Testnet environment.
    """

    def py_new(self, value: typing.Any) -> BitmexEnvironment:
        r"""
        BitMEX API environment.
        """
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BitmexEnvironment: ...

@typing.final
class BitmexPositionSide(enum.Enum):
    r"""
    Represents the position side for BitMEX positions.
    """
    Long = ...
    r"""
    Long position.
    """
    Short = ...
    r"""
    Short position.
    """
    Flat = ...
    r"""
    No position.
    """

@typing.final
class BitmexSymbolStatus(enum.Enum):
    r"""
    Represents the status of a BitMEX symbol.
    """
    Open = ...
    r"""
    Symbol is open for trading.
    """
    Closed = ...
    r"""
    Symbol is closed for trading.
    """
    Unlisted = ...
    r"""
    Symbol is unlisted.
    """

    def py_new(self, value: typing.Any) -> BitmexSymbolStatus:
        r"""
        Represents the status of a BitMEX symbol.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BitmexSymbolStatus: ...

def get_bitmex_http_base_url(environment: BitmexEnvironment) -> builtins.str:
    r"""
    Gets the BitMEX HTTP base URL.
    """

def get_bitmex_ws_url(environment: BitmexEnvironment) -> builtins.str:
    r"""
    Gets the BitMEX WebSocket URL.
    """

