# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import decimal
import enum
from nautilus_trader import model
import typing
__all__ = [
    "AxCancelReason",
    "AxCancelRejectionReason",
    "AxDataClientConfig",
    "AxEnvironment",
    "AxExecClientConfig",
    "AxHttpClient",
    "AxInstrumentState",
    "AxMarketDataLevel",
    "AxMdWsMessageType",
    "AxOrderSide",
    "AxOrderStatus",
    "AxOrderType",
    "AxOrderWsMessageType",
    "AxTimeInForce",
    "PyAxMdWebSocketClient",
    "PyAxOrdersWebSocketClient",
]

@typing.final
class AxDataClientConfig:
    r"""
    Configuration for the AX Exchange live data client.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], environment: typing.Optional[AxEnvironment], base_url_http: typing.Optional[builtins.str], base_url_ws_public: typing.Optional[builtins.str], base_url_ws_private: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], funding_rate_poll_interval_mins: typing.Optional[builtins.int]) -> AxDataClientConfig:
        r"""
        Configuration for the AX Exchange live data client.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class AxExecClientConfig:
    r"""
    Configuration for the AX Exchange live execution client.
    """
    def py_new(self, trader_id: typing.Optional[model.TraderId], account_id: typing.Optional[model.AccountId], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], environment: typing.Optional[AxEnvironment], base_url_http: typing.Optional[builtins.str], base_url_orders: typing.Optional[builtins.str], base_url_ws_private: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], cancel_on_disconnect: typing.Optional[builtins.bool]) -> AxExecClientConfig:
        r"""
        Configuration for the AX Exchange live execution client.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class AxHttpClient:
    r"""
    High-level HTTP client for the Ax REST API.
    
    This client wraps the underlying [`AxRawHttpClient`] to provide a convenient
    interface for Python bindings and instrument caching.
    """
    def py_new(self, base_url: typing.Optional[builtins.str], orders_base_url: typing.Optional[builtins.str], timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, proxy_url: typing.Optional[builtins.str]) -> AxHttpClient:
        r"""
        High-level HTTP client for the Ax REST API.
        
        This client wraps the underlying `AxRawHttpClient` to provide a convenient
        interface for Python bindings and instrument caching.
        """
    def py_with_credentials(self, api_key: builtins.str, api_secret: builtins.str, base_url: typing.Optional[builtins.str], orders_base_url: typing.Optional[builtins.str], timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, proxy_url: typing.Optional[builtins.str]) -> AxHttpClient:
        r"""
        Creates a new `AxHttpClient` configured with credentials.
        """
    def py_base_url(self) -> builtins.str:
        r"""
        Returns the base URL for this client.
        """
    def py_api_key_masked(self) -> builtins.str:
        r"""
        Returns a masked version of the API key for logging purposes.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancel all pending HTTP requests.
        """
    def py_cancel_all_orders(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Cancels all open orders for an instrument.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches a single instrument.
        
        Any existing instrument with the same symbol will be replaced.
        """
    def py_authenticate(self, api_key: builtins.str, api_secret: builtins.str, expiration_seconds: builtins.int) -> typing.Any:
        r"""
        Authenticates with Ax using API credentials.
        
        On success, the session token is automatically stored for subsequent authenticated requests.
        """
    def py_authenticate_auto(self, expiration_seconds: builtins.int) -> typing.Any:
        r"""
        Authenticates using stored credentials or environment variables.
        
        # Credential Resolution
        
        Credentials are resolved in the following order:
        1. Stored credentials (from `with_credentials` constructor)
        2. Environment variables (`AX_API_KEY` and `AX_API_SECRET`)
        
        On success, the session token is automatically stored for subsequent authenticated requests.
        """
    def py_request_instruments(self, maker_fee: typing.Optional[decimal.Decimal], taker_fee: typing.Optional[decimal.Decimal]) -> typing.Any:
        r"""
        Requests all instruments from Ax.
        """
    def py_request_trade_ticks(self, instrument_id: model.InstrumentId, limit: typing.Optional[builtins.int], start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime]) -> typing.Any:
        r"""
        Requests recent trades from Ax and parses them to Nautilus `TradeTick`.
        
        The AX trades endpoint does not accept time range parameters, so
        `start` and `end` are applied as client-side filters after fetching.
        
        Requires the instrument to be cached.
        """
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime]) -> typing.Any:
        r"""
        Requests historical bars from Ax and parses them to Nautilus Bar types.
        
        Requires the instrument to be cached (call `request_instruments` first).
        """
    def py_request_funding_rates(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime]) -> typing.Any:
        r"""
        Requests funding rates from Ax and parses them to Nautilus types.
        """
    def py_request_account_state(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests account state from Ax and parses to a Nautilus `AccountState`.
        """
    def py_request_order_status(self, account_id: model.AccountId, instrument_id: model.InstrumentId, order_side: model.OrderSide, order_type: model.OrderType, time_in_force: model.TimeInForce, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Queries a single order by venue order ID or client order ID using the
        dedicated `/order-status` endpoint, which works for any order state.
        
        The caller must supply `order_side`, `order_type`, and `time_in_force`
        because the endpoint does not return these fields.
        """
    def py_request_order_status_reports(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests open orders from Ax and parses them to Nautilus `OrderStatusReport`.
        
        Requires instruments to be cached for parsing order details.
        
        The `cid_resolver` parameter is an optional function that resolves a `cid` (u64)
        to a `ClientOrderId`. This is needed for correlating orders submitted via WebSocket.
        """
    def py_request_fill_reports(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests fills from Ax and parses them to Nautilus `FillReport`.
        
        Requires instruments to be cached for parsing fill details.
        """
    def py_request_position_reports(self, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests positions from Ax and parses them to Nautilus `PositionStatusReport`.
        
        Requires instruments to be cached for parsing position details.
        """
    def py_preview_aggressive_limit_order(self, instrument_id: model.InstrumentId, quantity: model.Quantity, side: model.OrderSide) -> typing.Any: ...

@typing.final
class PyAxMdWebSocketClient:
    r"""
    Python wrapper around [`AxMdWebSocketClient`] that holds an instrument cache
    at the Python boundary for parsing venue messages into Nautilus domain types.
    """
    def py_new(self, url: builtins.str, auth_token: builtins.str, heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> PyAxMdWebSocketClient: ...
    def py_without_auth(self, url: builtins.str, heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> PyAxMdWebSocketClient: ...
    def py_url(self) -> builtins.str: ...
    def py_is_active(self) -> builtins.bool: ...
    def py_is_closed(self) -> builtins.bool: ...
    def py_subscription_count(self) -> builtins.int: ...
    def py_set_auth_token(self, token: builtins.str) -> None: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None: ...
    def py_connect(self, loop_: typing.Any, callback: typing.Any) -> typing.Any: ...
    def py_subscribe_book_deltas(self, instrument_id: model.InstrumentId, level: AxMarketDataLevel) -> typing.Any: ...
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_instrument_status(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_book_deltas(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any: ...
    def py_unsubscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_instrument_status(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_disconnect(self) -> typing.Any: ...
    def py_close(self) -> typing.Any: ...

@typing.final
class PyAxOrdersWebSocketClient:
    r"""
    Python wrapper around [`AxOrdersWebSocketClient`] that handles order event
    parsing at the Python boundary.
    """
    def py_new(self, url: builtins.str, account_id: model.AccountId, trader_id: model.TraderId, heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> PyAxOrdersWebSocketClient: ...
    def py_url(self) -> builtins.str: ...
    def py_account_id(self) -> model.AccountId: ...
    def py_is_active(self) -> builtins.bool: ...
    def py_is_closed(self) -> builtins.bool: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None: ...
    def py_register_external_order(self, client_order_id: model.ClientOrderId, venue_order_id: model.VenueOrderId, instrument_id: model.InstrumentId, strategy_id: model.StrategyId) -> builtins.bool: ...
    def py_connect(self, loop_: typing.Any, callback: typing.Any, bearer_token: builtins.str) -> typing.Any: ...
    def py_submit_order(self, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], post_only: builtins.bool) -> typing.Any: ...
    def py_cancel_order(self, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any: ...
    def py_get_open_orders(self) -> typing.Any: ...
    def py_disconnect(self) -> typing.Any: ...
    def py_close(self) -> typing.Any: ...

@typing.final
class AxCancelReason(enum.Enum):
    r"""
    Reason for order cancellation.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/orders-ws>
    """
    UserRequested = ...
    r"""
    User requested cancellation.
    """
    Unknown = ...
    r"""
    Unrecognized or empty reason from the server.
    """

@typing.final
class AxCancelRejectionReason(enum.Enum):
    r"""
    Reason for cancel rejection.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/orders-ws>
    """
    OrderNotFound = ...
    r"""
    Order not found or already canceled.
    """
    Unknown = ...
    r"""
    Unrecognized reason from the server.
    """

@typing.final
class AxEnvironment(enum.Enum):
    r"""
    AX Exchange API environment.
    """
    Sandbox = ...
    r"""
    Sandbox/test environment.
    """
    Production = ...
    r"""
    Production/live environment.
    """

    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def py_from_str(self, data: typing.Any) -> AxEnvironment: ...

@typing.final
class AxInstrumentState(enum.Enum):
    r"""
    Instrument state as returned by the AX Exchange API.
    
    # References
    - <https://docs.architect.exchange/api-reference/symbols-instruments/get-instruments>
    """
    PreOpen = ...
    r"""
    Instrument is in pre-open state.
    """
    Open = ...
    r"""
    Instrument is open for trading.
    """
    Closed = ...
    r"""
    Instrument trading is closed.
    """
    ClosedFrozen = ...
    r"""
    Instrument trading is closed and frozen.
    """
    Halted = ...
    r"""
    Instrument trading is halted.
    """
    MatchAndCloseAuction = ...
    r"""
    Instrument is in a match-and-close auction.
    """
    Suspended = ...
    r"""
    Instrument trading is suspended.
    """
    Delisted = ...
    r"""
    Instrument has been delisted.
    """
    Unknown = ...
    r"""
    Instrument state is unknown.
    """

@typing.final
class AxMarketDataLevel(enum.Enum):
    r"""
    Market data subscription level.
    
    The AX API uses `LEVEL_1`, `LEVEL_2`, `LEVEL_3` on the wire (with underscore
    before the digit). Serde and strum per-variant renames handle the wire and
    string formats correctly, however PyO3's `rename_all` does not insert an
    underscore at letter-digit boundaries, so the Python variant names are
    `LEVEL1`, `LEVEL2`, `LEVEL3` (without underscore).
    
    # References
    - <https://docs.architect.exchange/api-reference/marketdata/md-ws>
    """
    Level1 = ...
    r"""
    Level 1: best bid/ask only.
    """
    Level2 = ...
    r"""
    Level 2: aggregated price levels.
    """
    Level3 = ...
    r"""
    Level 3: individual order quantities.
    """

    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def py_from_str(self, data: typing.Any) -> AxMarketDataLevel: ...

@typing.final
class AxMdWsMessageType(enum.Enum):
    r"""
    WebSocket market data message type (server to client).
    
    # References
    - <https://docs.architect.exchange/api-reference/marketdata/md-ws>
    """
    Heartbeat = ...
    r"""
    Heartbeat event.
    """
    Ticker = ...
    r"""
    Ticker statistics update.
    """
    Trade = ...
    r"""
    Trade event.
    """
    Candle = ...
    r"""
    Candle/OHLCV update.
    """
    BookLevel1 = ...
    r"""
    Level 1 book update (best bid/ask).
    """
    BookLevel2 = ...
    r"""
    Level 2 book update (aggregated levels).
    """
    BookLevel3 = ...
    r"""
    Level 3 book update (individual orders).
    """

@typing.final
class AxOrderSide(enum.Enum):
    r"""
    Order side for trading operations.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/place-order>
    """
    Buy = ...
    r"""
    Buy order.
    """
    Sell = ...
    r"""
    Sell order.
    """

@typing.final
class AxOrderStatus(enum.Enum):
    r"""
    Order status as returned by the AX Exchange API.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/get-open-orders>
    """
    Pending = ...
    r"""
    Order is pending submission.
    """
    Accepted = ...
    r"""
    Order has been accepted by the exchange (OPEN state).
    """
    PartiallyFilled = ...
    r"""
    Order has been partially filled.
    """
    Filled = ...
    r"""
    Order has been completely filled.
    """
    Canceling = ...
    r"""
    Order cancellation is in progress.
    """
    Canceled = ...
    r"""
    Order has been canceled.
    """
    Rejected = ...
    r"""
    Order has been rejected.
    """
    Expired = ...
    r"""
    Order has expired.
    """
    Replaced = ...
    r"""
    Order has been replaced.
    """
    DoneForDay = ...
    r"""
    Order is done for the day.
    """
    Out = ...
    r"""
    Order is no longer on the orderbook (terminal state).
    """
    ReconciledOut = ...
    r"""
    Order was reconciled out asynchronously.
    """
    Stale = ...
    r"""
    Order is in a stale state (expected transitions not occurring).
    """
    Unknown = ...
    r"""
    Order status is unknown.
    """

@typing.final
class AxOrderType(enum.Enum):
    r"""
    Order type as defined by the AX Exchange API.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/place-order>
    """
    Market = ...
    r"""
    Market order; execute immediately at best available price.
    """
    Limit = ...
    r"""
    Limit order; execute no worse than the limit price specified.
    """
    StopLossLimit = ...
    r"""
    Stop-limit order; if the trigger price is breached, place a limit order.
    """
    TakeProfitLimit = ...
    r"""
    Take-profit order; if the trigger price is breached, place a limit order.
    Note: Not currently implemented by Architect.
    """

@typing.final
class AxOrderWsMessageType(enum.Enum):
    r"""
    WebSocket order message type (server to client).
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/orders-ws>
    """
    Heartbeat = ...
    r"""
    Heartbeat event.
    """
    CancelRejected = ...
    r"""
    Cancel rejected event.
    """
    OrderAcknowledged = ...
    r"""
    Order acknowledged event.
    """
    OrderCanceled = ...
    r"""
    Order canceled event.
    """
    OrderReplaced = ...
    r"""
    Order replaced/amended event.
    """
    OrderRejected = ...
    r"""
    Order rejected event.
    """
    OrderExpired = ...
    r"""
    Order expired event.
    """
    OrderDoneForDay = ...
    r"""
    Order done for day event.
    """
    OrderPartiallyFilled = ...
    r"""
    Order partially filled event.
    """
    OrderFilled = ...
    r"""
    Order filled event.
    """

@typing.final
class AxTimeInForce(enum.Enum):
    r"""
    Time in force for order validity.
    
    # References
    - <https://docs.architect.exchange/api-reference/order-management/place-order>
    """
    Gtc = ...
    r"""
    Good-Till-Canceled: order remains active until filled or canceled.
    """
    Gtd = ...
    r"""
    Good-Till-Date: order remains active until specified datetime.
    """
    Day = ...
    r"""
    Day order: valid until end of trading day.
    """
    Ioc = ...
    r"""
    Immediate-Or-Cancel: fill immediately or cancel unfilled portion.
    """
    Fok = ...
    r"""
    Fill-Or-Kill: execute entire order immediately or cancel.
    """
    Ato = ...
    r"""
    At-the-Open: execute at market opening or expire.
    """
    Atc = ...
    r"""
    At-the-Close: execute at market close or expire.
    """

