# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "UUID4",
    "py_convert_to_snake_case",
    "py_is_pycapsule",
    "py_is_within_last_24_hours",
    "py_last_weekday_nanos",
    "py_mask_api_key",
    "py_micros_to_nanos",
    "py_millis_to_nanos",
    "py_nanos_to_micros",
    "py_nanos_to_millis",
    "py_nanos_to_secs",
    "py_secs_to_millis",
    "py_secs_to_nanos",
    "py_unix_nanos_to_iso8601",
]

@typing.final
class UUID4:
    r"""
    Represents a Universally Unique Identifier (UUID)
    version 4 based on a 128-bit label as specified in RFC 4122.
    """
    def py_new(self) -> UUID4:
        r"""
        Represents a Universally Unique Identifier (UUID)
        version 4 based on a 128-bit label as specified in RFC 4122.
        """
    def __setstate__(self, state: typing.Any) -> None:
        r"""
        Sets the state of the `UUID4` instance during unpickling.
        """
    def __getstate__(self) -> typing.Any:
        r"""
        Gets the state of the `UUID4` instance for pickling.
        """
    def __reduce__(self) -> typing.Any:
        r"""
        Reduces the `UUID4` instance for pickling.
        """
    def _safe_constructor(self) -> UUID4:
        r"""
        A safe constructor used during unpickling to ensure the correct initialization of `UUID4`.
        """
    def __richcmp__(self, other: UUID4, op: int) -> typing.Any:
        r"""
        Compares two `UUID4` instances for equality
        """
    def __hash__(self) -> builtins.int:
        r"""
        Returns a hash value for the `UUID4` instance.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns a detailed string representation of the `UUID4` instance.
        """
    def __str__(self) -> builtins.str:
        r"""
        Returns the `UUID4` as a string.
        """
    def py_value(self) -> builtins.str:
        r"""
        Gets the `UUID4` value as a string.
        """
    def py_from_str(self, value: builtins.str) -> UUID4:
        r"""
        Creates a new [`UUID4`] from a string representation.
        """

def py_convert_to_snake_case(input: builtins.str) -> builtins.str:
    r"""
    Convert the given string from any common case (PascalCase, camelCase, kebab-case, etc.)
    to *lower* `snake_case`.
    
    Parameters
    ----------
    input : str
        The input string to convert.
    
    Returns
    -------
    str
    """

def py_is_pycapsule(obj: typing.Any) -> builtins.bool:
    r"""
    Return a value indicating whether the `obj` is a `PyCapsule`.
    
    Parameters
    ----------
    obj : Any
        The object to check.
    
    # Returns
    
    bool
    """

def py_is_within_last_24_hours(timestamp_ns: builtins.int) -> builtins.bool:
    r"""
    Check whether the given UNIX nanoseconds timestamp is within the last 24 hours.
    
    # Errors
    
    Returns an error if the timestamp is invalid.
    """

def py_last_weekday_nanos(year: builtins.int, month: builtins.int, day: builtins.int) -> builtins.int:
    r"""
    Calculates the last weekday (Mon-Fri) from the given `year`, `month` and `day`.
    
    # Errors
    
    Returns an error if the date is invalid.
    """

def py_mask_api_key(api_key: builtins.str) -> builtins.str:
    r"""
    Masks an API key by showing only the first and last 4 characters.
    
    For keys 8 characters or shorter, returns asterisks only.
    
    # Examples
    
    ```
    use nautilus_core::string::secret::mask_api_key;
    
    assert_eq!(mask_api_key("abcdefghijklmnop"), "abcd...mnop");
    assert_eq!(mask_api_key("short"), "*****");
    ```
    """

def py_micros_to_nanos(micros: builtins.float) -> builtins.int:
    r"""
    Converts microseconds (μs) to nanoseconds (ns).
    
    Casting f64 to u64 by truncating the fractional part is intentional for unit conversion,
    which may lose precision and drop negative values after clamping.
    
    # Errors
    
    Returns an error if `micros` is non-finite or exceeds `MAX_MICROS_FOR_NANOS`.
    """

def py_millis_to_nanos(millis: builtins.float) -> builtins.int:
    r"""
    Converts milliseconds (ms) to nanoseconds (ns).
    
    Casting f64 to u64 by truncating the fractional part is intentional for unit conversion,
    which may lose precision and drop negative values after clamping.
    
    # Errors
    
    Returns an error if `millis` is non-finite or exceeds `MAX_MILLIS_FOR_NANOS`.
    """

def py_nanos_to_micros(nanos: builtins.int) -> builtins.int:
    r"""
    Converts nanoseconds (ns) to microseconds (μs).
    """

def py_nanos_to_millis(nanos: builtins.int) -> builtins.int:
    r"""
    Converts nanoseconds (ns) to milliseconds (ms).
    """

def py_nanos_to_secs(nanos: builtins.int) -> builtins.float:
    r"""
    Converts nanoseconds (ns) to seconds.
    
    Casting u64 to f64 may lose precision for large values,
    but is acceptable when computing fractional seconds.
    """

def py_secs_to_millis(secs: builtins.float) -> builtins.int:
    r"""
    Converts seconds to milliseconds (ms).
    
    # Errors
    
    Returns an error if `secs` is non-finite or exceeds `MAX_SECS_FOR_MILLIS`.
    """

def py_secs_to_nanos(secs: builtins.float) -> builtins.int:
    r"""
    Converts seconds to nanoseconds (ns).
    
    # Errors
    
    Returns an error if `secs` is non-finite or exceeds `MAX_SECS_FOR_NANOS`.
    """

def py_unix_nanos_to_iso8601(timestamp_ns: builtins.int, nanos_precision: typing.Optional[builtins.bool]) -> builtins.str:
    r"""
    Converts a UNIX nanoseconds timestamp to an ISO 8601 (RFC 3339) format string.
    
    Returns the raw nanosecond value as a string if it exceeds the representable
    datetime range (`i64::MAX`, approximately year 2262).
    """

