# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import decimal
import enum
from nautilus_trader import model
import typing
__all__ = [
    "HyperliquidAllDexsAssetCtxs",
    "HyperliquidAllMids",
    "HyperliquidConditionalOrderType",
    "HyperliquidDataClientConfig",
    "HyperliquidDataClientFactory",
    "HyperliquidEnvironment",
    "HyperliquidExecClientConfig",
    "HyperliquidExecFactoryConfig",
    "HyperliquidExecutionClientFactory",
    "HyperliquidHttpClient",
    "HyperliquidOpenInterest",
    "HyperliquidProductType",
    "HyperliquidRawHttpClient",
    "HyperliquidTpSl",
    "HyperliquidTrailingOffsetType",
    "HyperliquidWebSocketClient",
    "py_get_hyperliquid_http_base_url",
    "py_get_hyperliquid_ws_url",
    "py_hyperliquid_cloid_from_client_order_id",
    "py_hyperliquid_product_type_from_symbol",
    "py_hyperliquid_resolve_execution_account_address",
]

@typing.final
class HyperliquidAllDexsAssetCtxs:
    r"""
    Hyperliquid normalized aggregate snapshot from the `allDexsAssetCtxs` WebSocket channel.
    
    This feed is live-only and intentionally JSON-backed; it is not coupled to Arrow persistence.
    """
    @property
    def entries(self) -> typing.Any: ...
    @property
    def ts_event(self) -> builtins.int: ...
    @property
    def ts_init(self) -> builtins.int: ...
    def __new__(cls, entries: typing.Any, ts_event: builtins.int, ts_init: builtins.int) -> HyperliquidAllDexsAssetCtxs: ...
    def __repr__(self) -> builtins.str:
        r"""
        Python `repr()`: uses the Rust `Display` implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Python `str()`: uses the Rust `Display` implementation.
        """
    def to_json(self) -> builtins.str:
        r"""
        Serializes to JSON string. Used by CustomData.to_json_bytes and PythonCustomDataWrapper.
        """
    @classmethod
    def from_json(cls, _cls: type, data: typing.Any) -> typing.Any:
        r"""
        Class method for JSON deserialization. Used by register_custom_data_class.
        """

@typing.final
class HyperliquidAllMids:
    r"""
    Hyperliquid all mid prices snapshot from the `allMids` WebSocket channel.
    """
    @property
    def mids(self) -> typing.Any: ...
    @property
    def ts_event(self) -> builtins.int: ...
    @property
    def ts_init(self) -> builtins.int: ...
    def __new__(cls, mids: typing.Any, ts_event: builtins.int, ts_init: builtins.int) -> HyperliquidAllMids: ...
    def __repr__(self) -> builtins.str:
        r"""
        Python `repr()`: uses the Rust `Display` implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Python `str()`: uses the Rust `Display` implementation.
        """
    def to_json(self) -> builtins.str:
        r"""
        Serializes to JSON string. Used by CustomData.to_json_bytes and PythonCustomDataWrapper.
        """
    @classmethod
    def from_json(cls, _cls: type, data: typing.Any) -> typing.Any:
        r"""
        Class method for JSON deserialization. Used by register_custom_data_class.
        """
    @classmethod
    def decode_record_batch_py(cls, metadata: typing.Mapping[builtins.str, builtins.str], py_batch: typing.Any) -> typing.Any:
        r"""
        Decodes a RecordBatch from a PyArrow batch into a list of instances.
        Class method: call via MarketTickData.decode_record_batch_py(metadata, batch).
        """
    def encode_record_batch_py(self, items: list) -> typing.Any:
        r"""
        Encodes a batch of items to an Arrow RecordBatch. Returns a PyArrow RecordBatch
        using zero-copy C Data interface.
        """

@typing.final
class HyperliquidDataClientConfig:
    r"""
    Configuration for the Hyperliquid data client.
    """
    def py_new(self, environment: typing.Optional[HyperliquidEnvironment], private_key: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], ws_timeout_secs: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int]) -> HyperliquidDataClientConfig:
        r"""
        Configuration for the Hyperliquid data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class HyperliquidDataClientFactory:
    r"""
    Factory for creating Hyperliquid data clients.
    """
    def py_new(self) -> HyperliquidDataClientFactory:
        r"""
        Factory for creating Hyperliquid data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class HyperliquidExecClientConfig:
    r"""
    Configuration for the Hyperliquid execution client.
    """
    def py_new(self, private_key: typing.Optional[builtins.str], vault_address: typing.Optional[builtins.str], account_address: typing.Optional[builtins.str], environment: typing.Optional[HyperliquidEnvironment], base_url_ws: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_exchange: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], normalize_prices: typing.Optional[builtins.bool], market_order_slippage_bps: typing.Optional[builtins.int], ws_post_timeout_secs: typing.Optional[builtins.int]) -> HyperliquidExecClientConfig:
        r"""
        Configuration for the Hyperliquid execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class HyperliquidExecFactoryConfig:
    r"""
    Configuration for creating Hyperliquid execution clients via factory.
    
    This wraps [`HyperliquidExecClientConfig`] with the additional trader and account
    identifiers required by the [`ExecutionClientCore`].
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, config: HyperliquidExecClientConfig) -> HyperliquidExecFactoryConfig:
        r"""
        Configuration for creating Hyperliquid execution clients via factory.
        
        This wraps `HyperliquidExecClientConfig` with the additional trader and account
        identifiers required by the `ExecutionClientCore`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class HyperliquidExecutionClientFactory:
    r"""
    Factory for creating Hyperliquid execution clients.
    """
    def py_new(self) -> HyperliquidExecutionClientFactory:
        r"""
        Factory for creating Hyperliquid execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class HyperliquidHttpClient:
    r"""
    Provides a high-level HTTP client for the [Hyperliquid](https://hyperliquid.xyz/) REST API.
    
    This domain client wraps [`HyperliquidRawHttpClient`] and provides methods that work
    with Nautilus domain types. It maintains an instrument cache and handles conversions
    between Hyperliquid API responses and Nautilus domain models.
    """
    def py_new(self, private_key: typing.Optional[builtins.str], vault_address: typing.Optional[builtins.str], account_address: typing.Optional[builtins.str], environment: HyperliquidEnvironment, timeout_secs: builtins.int, proxy_url: typing.Optional[builtins.str], normalize_prices: builtins.bool) -> HyperliquidHttpClient:
        r"""
        Provides a high-level HTTP client for the [Hyperliquid](https://hyperliquid.xyz/) REST API.
        
        This domain client wraps `HyperliquidRawHttpClient` and provides methods that work
        with Nautilus domain types. It maintains an instrument cache and handles conversions
        between Hyperliquid API responses and Nautilus domain models.
        """
    def py_from_env(self, environment: HyperliquidEnvironment) -> HyperliquidHttpClient:
        r"""
        Creates an authenticated client from environment variables for the specified network.
        
        # Errors
        
        Returns `Error.Auth` if required environment variables are not set.
        """
    def py_from_credentials(self, private_key: builtins.str, vault_address: typing.Optional[builtins.str], environment: HyperliquidEnvironment, timeout_secs: builtins.int, proxy_url: typing.Optional[builtins.str]) -> HyperliquidHttpClient:
        r"""
        Creates a new `HyperliquidHttpClient` configured with explicit credentials.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Caches a single instrument.
        
        This is required for parsing orders, fills, and positions into reports.
        Any existing instrument with the same symbol will be replaced.
        """
    def py_set_account_id(self, account_id: builtins.str) -> None:
        r"""
        Set the account ID for this client.
        
        This is required for generating reports with the correct account ID.
        """
    def py_get_user_address(self) -> builtins.str:
        r"""
        Gets the user address derived from the private key (if client has credentials).
        
        # Errors
        
        Returns `Error.Auth` if the client has no signer configured.
        """
    def py_get_spot_fill_coin_mapping(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Get mapping from spot fill coin identifiers to instrument symbols.
        
        Hyperliquid WebSocket fills for spot use `@{pair_index}` format (e.g., `@107`),
        while instruments are identified by full symbols (e.g., `HYPE-USDC-SPOT`).
        This mapping allows looking up the instrument from a spot fill.
        
        This method also caches the mapping internally for use by fill parsing methods.
        """
    def py_get_spot_meta(self) -> typing.Any:
        r"""
        Get spot metadata (internal helper).
        """
    def py_get_perp_meta(self) -> typing.Any: ...
    def py_build_all_dex_asset_ctxs_instrument_ids(self) -> typing.Any:
        r"""
        Builds the `allDexsAssetCtxs` normalization map from dex name to ordered instrument IDs.
        
        The order of instrument IDs must match the venue universe ordering for each perp dex so
        incoming `ctxs` arrays can be normalized without leaking raw positional payloads.
        """
    def py_load_instrument_definitions(self, include_spot: builtins.bool, include_perps: builtins.bool, include_perps_hip3: builtins.bool, include_outcomes: builtins.bool) -> typing.Any: ...
    def py_request_quote_ticks(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_request_trade_ticks(self, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any: ...
    def py_request_bars(self, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request historical bars for an instrument.
        
        Fetches candle data from the Hyperliquid API and converts it to Nautilus bars.
        Incomplete bars (where end_timestamp >= current time) are filtered out.
        
        # References
        
        <https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint#candles-snapshot>
        """
    def py_submit_order(self, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], post_only: builtins.bool, reduce_only: builtins.bool) -> typing.Any:
        r"""
        Submits an order to the exchange.
        """
    def py_cancel_order(self, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancel an order on the Hyperliquid exchange.
        
        Can cancel either by venue order ID or client order ID.
        At least one ID must be provided.
        """
    def py_modify_order(self, instrument_id: model.InstrumentId, venue_order_id: model.VenueOrderId, order_side: model.OrderSide, order_type: model.OrderType, price: model.Price, quantity: model.Quantity, trigger_price: typing.Optional[model.Price], reduce_only: builtins.bool, post_only: builtins.bool, time_in_force: model.TimeInForce, client_order_id: typing.Optional[model.ClientOrderId]) -> typing.Any:
        r"""
        Modify an order on the Hyperliquid exchange.
        
        The HL modify API requires a full replacement order spec plus the
        venue order ID. The caller must provide all order fields.
        """
    def py_submit_orders(self, orders: typing.Sequence[typing.Any]) -> typing.Any:
        r"""
        Submit multiple orders to the Hyperliquid exchange in a single request.
        """
    def py_request_order_status_reports(self, instrument_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request order status reports for a user.
        
        Fetches open orders via `info_frontend_open_orders` and parses them into OrderStatusReports.
        This method requires instruments to be added to the client cache via `cache_instrument()`.
        
        For vault tokens (starting with "vntls:") that are not in the cache, synthetic instruments
        will be created automatically.
        """
    def py_request_order_status_report(self, venue_order_id: typing.Optional[builtins.str], client_order_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request a single order status report by venue order ID.
        
        Queries `info_frontend_open_orders` and filters for the given oid so the
        result includes trigger metadata (trigger_px, tpsl, trailing_stop, etc.).
        Falls back to `info_order_status` when the order is no longer open.
        """
    def py_request_fill_reports(self, instrument_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request fill reports for a user.
        
        Fetches user fills via `info_user_fills` and parses them into FillReports.
        This method requires instruments to be added to the client cache via `cache_instrument()`.
        
        For vault tokens (starting with "vntls:") that are not in the cache, synthetic instruments
        will be created automatically.
        """
    def py_request_position_status_reports(self, instrument_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request position status reports for a user.
        
        Fetches perp clearinghouse state and spot clearinghouse state, then returns
        the union of perp asset positions (short/long with PnL) and spot holdings
        (long only). This method requires instruments to be added to the client
        cache via `cache_instrument()`.
        
        When `instrument_id` resolves to a specific product type, the opposite
        product's endpoint is skipped to avoid wasted round trips and make
        filtered queries independent of the unused endpoint's availability.
        HIP-4 outcomes live in `spotClearinghouseState`, so an outcome filter
        is routed like a spot filter (perp leg skipped).
        
        For vault tokens (starting with "vntls:") that are not in the cache,
        synthetic instruments will be created automatically. Spot balances whose
        base token has no cached instrument are skipped with a debug log.
        """
    def py_request_account_state(self) -> typing.Any:
        r"""
        Request account state (balances and margins) for a user.
        
        Fetches perp and spot clearinghouse state from Hyperliquid and merges them
        into a single `AccountState`. USDC is taken from the perp margin summary
        when present (to avoid double-counting combined `withdrawable`); non-USDC
        tokens are appended from the spot balances.
        
        # Errors
        
        Returns an error if `account_id` is not set, or if either the perp or
        spot clearinghouse request fails. Spot failures are propagated so the
        caller sees real API errors instead of a silently truncated snapshot.
        """
    def py_request_spot_balances(self) -> typing.Any:
        r"""
        Request spot token balances for a user.
        
        Fetches `spotClearinghouseState` and returns one `AccountBalance` per
        non-zero token. USDC is included as a separate balance entry when present;
        callers that also report perp margin state must dedupe currencies before
        emitting an `AccountState`.
        
        # Errors
        
        Returns an error if the API request fails or the response cannot be parsed.
        """
    def py_request_spot_position_status_reports(self, instrument_id: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request spot position status reports for a user.
        
        Each non-zero spot balance is reported as a Long position against its
        `{BASE}-{QUOTE}-SPOT` instrument. HIP-4 outcome side tokens arrive on
        this same endpoint with `coin` set to the `+<encoding>` token form;
        those balances are resolved against the matching Outcome instrument so
        outcome holdings surface as positions through the standard reconcile
        path. Balances whose base token has no matching instrument in the
        cache are skipped with a debug log (callers should ensure
        `request_instruments` has run first).
        """
    def py_info_spot_clearinghouse_state(self) -> typing.Any:
        r"""
        Get spot clearinghouse state (per-token spot balances) for a user.
        """
    def py_info_user_fees(self) -> typing.Any:
        r"""
        Get user fee schedule and effective rates.
        """
    def py_submit_split_outcome(self, outcome: builtins.int, amount: decimal.Decimal) -> typing.Any:
        r"""
        Split an HIP-4 outcome's quote tokens into matched Yes and No side tokens.
        
        Submits a `userOutcome` exchange action with the `splitOutcome` operation:
        debits `amount` quote tokens (USDH) and credits `amount` Yes plus `amount`
        No side tokens for the given `outcome` index. Ordinary directional
        buys and sells on outcome instruments go through the standard order path
        without calling this; the action is for dual-side market making and
        inventory creation.
        """
    def py_submit_merge_outcome(self, outcome: builtins.int, amount: typing.Optional[decimal.Decimal]) -> typing.Any:
        r"""
        Merge matched Yes + No side-token pairs of an HIP-4 outcome back into quote tokens.
        
        Submits a `userOutcome` action with the `mergeOutcome` operation. Pass
        `amount = None` to merge the maximum mergeable balance (venue-side
        `null`).
        """
    def py_submit_merge_question(self, question: builtins.int, amount: typing.Optional[decimal.Decimal]) -> typing.Any:
        r"""
        Merge `Yes` shares of every outcome in a multi-outcome question into quote tokens.
        
        Submits a `userOutcome` action with the `mergeQuestion` operation. Pass
        `amount = None` to merge the maximum balance.
        """
    def py_submit_negate_outcome(self, question: builtins.int, outcome: builtins.int, amount: decimal.Decimal) -> typing.Any:
        r"""
        Swap `No` shares of one outcome into `Yes` shares of every other outcome.
        
        Submits a `userOutcome` action with the `negateOutcome` operation. Both
        outcomes must belong to the same multi-outcome `question`.
        """

@typing.final
class HyperliquidOpenInterest:
    r"""
    Hyperliquid open interest update from the `activeAssetCtx` WebSocket channel.
    
    Hyperliquid does not provide a native event timestamp on this payload, so
    `ts_event` mirrors `ts_init` like the peer asset-context update types.
    """
    @property
    def instrument_id(self) -> model.InstrumentId: ...
    @property
    def open_interest(self) -> typing.Any: ...
    @property
    def ts_event(self) -> builtins.int: ...
    @property
    def ts_init(self) -> builtins.int: ...
    def __new__(cls, instrument_id: model.InstrumentId, open_interest: typing.Any, ts_event: builtins.int, ts_init: builtins.int) -> HyperliquidOpenInterest: ...
    def __repr__(self) -> builtins.str:
        r"""
        Python `repr()`: uses the Rust `Display` implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Python `str()`: uses the Rust `Display` implementation.
        """
    def to_json(self) -> builtins.str:
        r"""
        Serializes to JSON string. Used by CustomData.to_json_bytes and PythonCustomDataWrapper.
        """
    @classmethod
    def from_json(cls, _cls: type, data: typing.Any) -> typing.Any:
        r"""
        Class method for JSON deserialization. Used by register_custom_data_class.
        """
    @classmethod
    def decode_record_batch_py(cls, metadata: typing.Mapping[builtins.str, builtins.str], py_batch: typing.Any) -> typing.Any:
        r"""
        Decodes a RecordBatch from a PyArrow batch into a list of instances.
        Class method: call via MarketTickData.decode_record_batch_py(metadata, batch).
        """
    def encode_record_batch_py(self, items: list) -> typing.Any:
        r"""
        Encodes a batch of items to an Arrow RecordBatch. Returns a PyArrow RecordBatch
        using zero-copy C Data interface.
        """

@typing.final
class HyperliquidRawHttpClient:
    r"""
    Provides a raw HTTP client for low-level Hyperliquid REST API operations.
    
    This client handles HTTP infrastructure, request signing, and raw API calls
    that closely match Hyperliquid endpoint specifications.
    """
    ...

@typing.final
class HyperliquidWebSocketClient:
    r"""
    Hyperliquid WebSocket client following the BitMEX pattern.
    
    Orchestrates WebSocket connection and subscriptions using a command-based architecture,
    where the inner FeedHandler owns the WebSocketClient and handles all I/O.
    """
    def py_new(self, url: typing.Optional[builtins.str], environment: HyperliquidEnvironment, account_id: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str]) -> HyperliquidWebSocketClient:
        r"""
        Hyperliquid WebSocket client following the BitMEX pattern.
        
        Orchestrates WebSocket connection and subscriptions using a command-based architecture,
        where the inner FeedHandler owns the WebSocketClient and handles all I/O.
        """
    def py_url(self) -> builtins.str:
        r"""
        Returns the URL of this WebSocket client.
        """
    def py_is_active(self) -> builtins.bool:
        r"""
        Returns true if the WebSocket is actively connected.
        """
    def py_is_closed(self) -> builtins.bool: ...
    def py_set_post_timeout(self, timeout_secs: builtins.int) -> None:
        r"""
        Sets the timeout for WebSocket post trading requests.
        """
    def py_submit_order(self, signer: HyperliquidHttpClient, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: model.TimeInForce, price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], post_only: builtins.bool, reduce_only: builtins.bool) -> typing.Any:
        r"""
        Submit an order through the Hyperliquid WebSocket post API.
        
        The HTTP client supplies signing credentials, builder attribution, and
        cached instrument metadata. The action itself is sent over WebSocket.
        """
    def py_submit_orders(self, signer: HyperliquidHttpClient, orders: typing.Sequence[typing.Any]) -> typing.Any:
        r"""
        Submit multiple orders through the Hyperliquid WebSocket post API.
        """
    def py_cancel_order(self, signer: HyperliquidHttpClient, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancel an order through the Hyperliquid WebSocket post API.
        """
    def py_cancel_orders(self, signer: HyperliquidHttpClient, cancels: typing.Sequence[tuple[model.InstrumentId, model.ClientOrderId, typing.Optional[model.VenueOrderId]]]) -> typing.Any:
        r"""
        Cancel multiple orders through one Hyperliquid WebSocket post action.
        """
    def py_modify_order(self, signer: HyperliquidHttpClient, instrument_id: model.InstrumentId, venue_order_id: model.VenueOrderId, order_side: model.OrderSide, order_type: model.OrderType, price: model.Price, quantity: model.Quantity, trigger_price: typing.Optional[model.Price], reduce_only: builtins.bool, post_only: builtins.bool, time_in_force: model.TimeInForce, client_order_id: typing.Optional[model.ClientOrderId]) -> typing.Any:
        r"""
        Modify an order through the Hyperliquid WebSocket post API.
        """
    def py_cache_spot_fill_coins(self, mapping: typing.Mapping[builtins.str, builtins.str]) -> None:
        r"""
        Caches spot fill coin mappings for instrument lookup.
        
        Hyperliquid WebSocket fills for spot use `@{pair_index}` format (e.g., `@107`),
        while instruments are identified by full symbols (e.g., `HYPE-USDC-SPOT`).
        This mapping allows the handler to look up instruments from spot fills.
        """
    def py_cache_all_dex_asset_ctxs_instrument_ids(self, mapping: typing.Mapping[builtins.str, typing.Sequence[typing.Optional[model.InstrumentId]]]) -> None:
        r"""
        Cache the ordered instrument IDs required to normalize `allDexsAssetCtxs`.
        """
    def py_cache_cloid_mapping(self, cloid: builtins.str, client_order_id: model.ClientOrderId) -> None:
        r"""
        Caches a venue CLOID to client_order_id mapping for order/fill resolution.
        
        This mapping allows WebSocket order status and fill reports to be resolved back to
        the original client_order_id.
        
        This writes directly to a shared cache that the handler reads from, avoiding any
        race conditions between caching and WebSocket message processing.
        """
    def py_remove_cloid_mapping(self, cloid: builtins.str) -> None:
        r"""
        Removes a cloid mapping from the cache.
        
        Called on terminal order state. The cache is FIFO-bounded so missed
        removals self-evict (see GH-3972 cancel-replace drain).
        """
    def py_clear_cloid_cache(self) -> None:
        r"""
        Clears all cloid mappings from the cache.
        
        Useful for cleanup during reconnection or shutdown.
        """
    def py_cloid_cache_len(self) -> builtins.int:
        r"""
        Returns the number of cloid mappings in the cache.
        """
    def py_get_cloid_mapping(self, cloid: builtins.str) -> typing.Optional[model.ClientOrderId]:
        r"""
        Looks up a client_order_id by its venue CLOID.
        
        Returns `Some(ClientOrderId)` if the mapping exists, `None` otherwise.
        """
    def py_connect(self, loop_: typing.Any, instruments: typing.Sequence[typing.Any], callback: typing.Any) -> typing.Any:
        r"""
        Establishes WebSocket connection and spawns the message handler.
        """
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any: ...
    def py_close(self) -> typing.Any: ...
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to trades for an instrument.
        """
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from trades for an instrument.
        """
    def py_subscribe_all_mids(self) -> typing.Any:
        r"""
        Subscribe to all mid prices across markets.
        """
    def py_subscribe_all_dexs_asset_ctxs(self) -> typing.Any:
        r"""
        Subscribe to aggregate asset contexts across all perp dexes.
        """
    def py_subscribe_all_mids_with_dex(self, dex: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Subscribe to all mid prices across markets, optionally scoped to a specific dex.
        """
    def py_subscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to L2 order book for an instrument.
        """
    def py_unsubscribe_book(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from L2 order book for an instrument.
        """
    def py_subscribe_book_deltas(self, instrument_id: model.InstrumentId, _book_type: builtins.int, _depth: builtins.int) -> typing.Any: ...
    def py_unsubscribe_book_deltas(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_subscribe_book_snapshots(self, instrument_id: model.InstrumentId, _book_type: builtins.int, _depth: builtins.int) -> typing.Any: ...
    def py_subscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to best bid/offer (BBO) quotes for an instrument.
        """
    def py_unsubscribe_quotes(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from quote ticks for an instrument.
        """
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Subscribe to candle/bar data for a specific coin and interval.
        """
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Unsubscribe from candle/bar data.
        """
    def py_unsubscribe_all_mids(self) -> typing.Any:
        r"""
        Unsubscribe from all mid prices across markets.
        """
    def py_unsubscribe_all_dexs_asset_ctxs(self) -> typing.Any:
        r"""
        Unsubscribe from aggregate asset contexts across all perp dexes.
        """
    def py_unsubscribe_all_mids_with_dex(self, dex: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Unsubscribe from all mid prices across markets, optionally scoped to a specific dex.
        """
    def py_subscribe_order_updates(self, user: builtins.str) -> typing.Any:
        r"""
        Subscribe to order updates for a specific user address.
        """
    def py_subscribe_user_events(self, user: builtins.str) -> typing.Any:
        r"""
        Subscribe to user events (fills, funding, liquidations) for a specific user address.
        """
    def py_subscribe_user_fills(self, user: builtins.str) -> typing.Any:
        r"""
        Subscribe to user fills for a specific user address.
        
        Note: This channel is redundant with `userEvents` which already includes fills.
        Prefer using `subscribe_user_events` or `subscribe_all_user_channels` instead.
        """
    def py_subscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to mark price updates for an instrument.
        """
    def py_unsubscribe_mark_prices(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from mark price updates for an instrument.
        """
    def py_subscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to index/oracle price updates for an instrument.
        """
    def py_unsubscribe_index_prices(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from index/oracle price updates for an instrument.
        """
    def py_subscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to funding rate updates for an instrument.
        """
    def py_subscribe_open_interest(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribe to open interest updates for an instrument.
        """
    def py_unsubscribe_funding_rates(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from funding rate updates for an instrument.
        """
    def py_unsubscribe_open_interest(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribe from open interest updates for an instrument.
        """

@typing.final
class HyperliquidConditionalOrderType(enum.Enum):
    r"""
    Represents conditional/trigger order types.
    
    Hyperliquid supports various conditional order types that trigger
    based on market conditions. These map to Nautilus OrderType variants.
    """
    StopMarket = ...
    r"""
    Stop market order (protective stop with market execution).
    """
    StopLimit = ...
    r"""
    Stop limit order (protective stop with limit price).
    """
    TakeProfitMarket = ...
    r"""
    Take profit market order (profit-taking with market execution).
    """
    TakeProfitLimit = ...
    r"""
    Take profit limit order (profit-taking with limit price).
    """
    TrailingStopMarket = ...
    r"""
    Trailing stop market order (dynamic stop with market execution).
    """
    TrailingStopLimit = ...
    r"""
    Trailing stop limit order (dynamic stop with limit price).
    """

    def py_new(self, value: typing.Any) -> HyperliquidConditionalOrderType:
        r"""
        Represents conditional/trigger order types.
        
        Hyperliquid supports various conditional order types that trigger
        based on market conditions. These map to Nautilus OrderType variants.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> HyperliquidConditionalOrderType: ...

@typing.final
class HyperliquidEnvironment(enum.Enum):
    r"""
    Hyperliquid API environment.
    """
    Mainnet = ...
    r"""
    Mainnet trading environment.
    """
    Testnet = ...
    r"""
    Testnet environment.
    """

    def py_new(self, value: typing.Any) -> HyperliquidEnvironment:
        r"""
        Hyperliquid API environment.
        """
    def __hash__(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> HyperliquidEnvironment: ...

@typing.final
class HyperliquidProductType(enum.Enum):
    r"""
    Hyperliquid product type.
    """
    Perp = ...
    r"""
    Perpetual futures.
    """
    Spot = ...
    r"""
    Spot markets.
    """
    Outcome = ...
    r"""
    HIP-4 binary outcome side tokens.
    """

    def py_new(self, value: typing.Any) -> HyperliquidProductType:
        r"""
        Hyperliquid product type.
        """
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: HyperliquidProductType) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> HyperliquidProductType: ...

@typing.final
class HyperliquidTpSl(enum.Enum):
    r"""
    Represents the take profit / stop loss type.
    """
    Tp = ...
    r"""
    Take Profit.
    """
    Sl = ...
    r"""
    Stop Loss.
    """

    def py_new(self, value: typing.Any) -> HyperliquidTpSl:
        r"""
        Represents the take profit / stop loss type.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> HyperliquidTpSl: ...

@typing.final
class HyperliquidTrailingOffsetType(enum.Enum):
    r"""
    Represents trailing offset types for trailing stop orders.
    
    Trailing stops adjust dynamically based on market movement:
    - Price: Fixed price offset (e.g., $100)
    - Percentage: Percentage offset (e.g., 5%)
    - BasisPoints: Basis points offset (e.g., 250 bps = 2.5%)
    """
    Price = ...
    r"""
    Fixed price offset.
    """
    Percentage = ...
    r"""
    Percentage offset.
    """
    BasisPoints = ...
    r"""
    Basis points offset (1 bp = 0.01%).
    """

    def py_new(self, value: typing.Any) -> HyperliquidTrailingOffsetType:
        r"""
        Represents trailing offset types for trailing stop orders.
        
        Trailing stops adjust dynamically based on market movement:
        - Price: Fixed price offset (e.g., $100)
        - Percentage: Percentage offset (e.g., 5%)
        - BasisPoints: Basis points offset (e.g., 250 bps = 2.5%)
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> HyperliquidTrailingOffsetType: ...

def py_get_hyperliquid_http_base_url(environment: HyperliquidEnvironment) -> builtins.str:
    r"""
    Get the HTTP base URL for Hyperliquid API (info endpoint).
    
    # Returns
    
    The HTTP base URL string.
    """

def py_get_hyperliquid_ws_url(environment: HyperliquidEnvironment) -> builtins.str:
    r"""
    Get the WebSocket URL for Hyperliquid API.
    
    # Returns
    
    The WebSocket URL string.
    """

def py_hyperliquid_cloid_from_client_order_id(client_order_id: model.ClientOrderId) -> builtins.str:
    r"""
    Compute the deterministic CLOID from a client_order_id.
    
    The CLOID is derived from a keccak256 hash of the client_order_id,
    truncated to 16 bytes, represented as a hex string with `0x` prefix.
    """

def py_hyperliquid_product_type_from_symbol(symbol: builtins.str) -> HyperliquidProductType:
    r"""
    Extract product type from a Hyperliquid symbol.
    
    # Errors
    
    Returns an error if the symbol does not contain a valid Hyperliquid product type suffix.
    """

def py_hyperliquid_resolve_execution_account_address(private_key: typing.Optional[builtins.str], vault_address: typing.Optional[builtins.str], account_address: typing.Optional[builtins.str], environment: HyperliquidEnvironment) -> typing.Optional[builtins.str]:
    r"""
    Resolve the Hyperliquid execution account address for REST queries and WebSocket subscriptions.
    
    # Errors
    
    Returns an error if the selected vault address or private key is invalid.
    """

