# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "py_ed25519_signature",
    "py_hmac_signature",
    "py_rsa_signature",
]

def py_ed25519_signature(private_key: bytes, data: builtins.str) -> builtins.str:
    r"""
    Signs `data` using Ed25519 with the provided private key seed.
    """

def py_hmac_signature(secret: builtins.str, data: builtins.str) -> builtins.str:
    r"""
    Generates an HMAC-SHA256 signature for the given data using the provided secret.
    
    This function creates a cryptographic hash-based message authentication code (HMAC)
    using SHA-256 as the underlying hash function. The resulting signature is returned
    as a lowercase hexadecimal string.
    
    # Errors
    
    Returns an error if signature generation fails due to key or cryptographic errors.
    """

def py_rsa_signature(private_key_pem: builtins.str, data: builtins.str) -> builtins.str:
    r"""
    Signs `data` using RSA PKCS#1 v1.5 SHA-256 with the provided private key in PEM format.
    
    # Errors
    
    Returns an error if:
    - `data` is empty.
    - `private_key_pem` is not a valid PEM-encoded PKCS#8 RSA private key or cannot be parsed.
    - Signature generation fails due to key or cryptographic errors.
    """

