# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "YahooDataClientFactory",
]

@typing.final
class YahooDataClientFactory:
    r"""
    Factory for creating Yahoo data clients.
    """
    ...

