# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
import enum
from nautilus_trader import model
import typing
__all__ = [
    "BinanceBar",
    "BinanceDataClientConfig",
    "BinanceDataClientFactory",
    "BinanceEnvironment",
    "BinanceExecClientConfig",
    "BinanceExecutionClientFactory",
    "BinanceFuturesLiquidation",
    "BinanceFuturesOpenInterest",
    "BinanceFuturesOpenInterestHist",
    "BinanceFuturesOpenInterestHistPoint",
    "BinanceMarginType",
    "BinancePositionSide",
    "BinanceProductType",
    "BinanceSpotMarketDataMode",
    "get_binance_arrow_schema_map",
]

@typing.final
class BinanceBar:
    r"""
    Represents a Binance bar (kline/candlestick) with additional Binance-specific fields.
    
    Extends the core `Bar` fields with `quote_volume`, `count`,
    `taker_buy_base_volume`, and `taker_buy_quote_volume`.
    """
    def __richcmp__(self, other: BinanceBar, op: int) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def py_bar_type(self) -> model.BarType: ...
    def py_open(self) -> model.Price: ...
    def py_high(self) -> model.Price: ...
    def py_low(self) -> model.Price: ...
    def py_close(self) -> model.Price: ...
    def py_volume(self) -> model.Quantity: ...
    def py_quote_volume(self) -> decimal.Decimal: ...
    def py_count(self) -> builtins.int: ...
    def py_taker_buy_base_volume(self) -> decimal.Decimal: ...
    def py_taker_buy_quote_volume(self) -> decimal.Decimal: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...
    def py_from_dict(self, values: dict) -> BinanceBar: ...
    def py_to_dict(self) -> typing.Any:
        r"""
        # Errors
        
        Returns a `PyErr` if generating the Python dictionary fails.
        """

@typing.final
class BinanceDataClientConfig:
    r"""
    Configuration for Binance data client.
    
    Ed25519 API keys are required for SBE WebSocket streams.
    """
    def py_new(self, product_type: typing.Optional[BinanceProductType], environment: typing.Optional[BinanceEnvironment], base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], spot_market_data_mode: typing.Optional[BinanceSpotMarketDataMode], instrument_status_poll_secs: typing.Optional[builtins.int]) -> BinanceDataClientConfig:
        r"""
        Configuration for Binance data client.
        
        Ed25519 API keys are required for SBE WebSocket streams.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BinanceDataClientFactory:
    r"""
    Factory for creating Binance data clients.
    """
    def py_new(self) -> BinanceDataClientFactory:
        r"""
        Factory for creating Binance data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BinanceExecClientConfig:
    r"""
    Configuration for Binance execution client.
    
    Ed25519 API keys are required for execution clients. Binance deprecated
    listenKey-based user data streams in favor of WebSocket API authentication,
    which only supports Ed25519.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, product_type: typing.Optional[BinanceProductType], environment: typing.Optional[BinanceEnvironment], base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], base_url_ws_trading: typing.Optional[builtins.str], use_ws_trading: builtins.bool, use_position_ids: builtins.bool, default_taker_fee: typing.Optional[builtins.float], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], futures_leverages: typing.Optional[typing.Mapping[builtins.str, builtins.int]], futures_margin_types: typing.Optional[typing.Mapping[builtins.str, BinanceMarginType]], treat_expired_as_canceled: builtins.bool, use_trade_lite: builtins.bool) -> BinanceExecClientConfig:
        r"""
        Configuration for Binance execution client.
        
        Ed25519 API keys are required for execution clients. Binance deprecated
        listenKey-based user data streams in favor of WebSocket API authentication,
        which only supports Ed25519.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BinanceExecutionClientFactory:
    r"""
    Factory for creating Binance Spot execution clients.
    """
    def py_new(self) -> BinanceExecutionClientFactory:
        r"""
        Factory for creating Binance Spot execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BinanceFuturesLiquidation:
    r"""
    Binance Futures liquidation update from the `forceOrder` stream.
    """
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_side(self) -> model.OrderSide: ...
    def py_price(self) -> model.Price: ...
    def py_average_price(self) -> model.Price: ...
    def py_last_filled_qty(self) -> model.Quantity: ...
    def py_accumulated_qty(self) -> model.Quantity: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...

@typing.final
class BinanceFuturesOpenInterest:
    r"""
    Binance Futures current open interest snapshot.
    """
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_open_interest(self) -> decimal.Decimal: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...

@typing.final
class BinanceFuturesOpenInterestHist:
    r"""
    Binance Futures historical open interest batch.
    
    For COIN-M requests, the current Binance adapter support is limited to
    perpetual instruments. Although Binance also exposes quarter-delivery
    contract types on the historical OI endpoint, the futures instrument
    parsing/symbology path in this adapter is still perpetual-only.
    """
    def py_instrument_id(self) -> model.InstrumentId: ...
    def py_period(self) -> builtins.str: ...
    def py_points(self) -> list: ...
    def py_ts_event(self) -> builtins.int: ...
    def py_ts_init(self) -> builtins.int: ...

@typing.final
class BinanceFuturesOpenInterestHistPoint:
    r"""
    Binance Futures historical open interest point.
    """
    def py_sum_open_interest(self) -> decimal.Decimal: ...
    def py_sum_open_interest_value(self) -> decimal.Decimal: ...
    def py_ts_event(self) -> builtins.int: ...

@typing.final
class BinanceEnvironment(enum.Enum):
    r"""
    Binance environment type.
    """
    Live = ...
    r"""
    Live exchange environment.
    """
    Testnet = ...
    r"""
    Testnet environment.
    """
    Demo = ...
    r"""
    Demo trading environment.
    """

    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class BinanceMarginType(enum.Enum):
    r"""
    Margin type applied to a position.
    
    Serializes to the POST format (`CROSSED`/`ISOLATED`) expected by
    `/fapi/v1/marginType`. Deserializes from both POST and GET/WS
    formats (`cross`/`isolated`) via serde aliases.
    """
    Cross = ...
    r"""
    Cross margin.
    """
    Isolated = ...
    r"""
    Isolated margin.
    """
    Unknown = ...
    r"""
    Unknown or undocumented value.
    """

@typing.final
class BinancePositionSide(enum.Enum):
    r"""
    Position side for dual-side position mode.
    """
    Both = ...
    r"""
    Single position mode (both).
    """
    Long = ...
    r"""
    Long position.
    """
    Short = ...
    r"""
    Short position.
    """
    Unknown = ...
    r"""
    Unknown or undocumented value.
    """

@typing.final
class BinanceProductType(enum.Enum):
    r"""
    Binance product type identifier.
    
    Each product type corresponds to a different Binance API domain and
    has distinct trading rules and instrument specifications.
    """
    Spot = ...
    r"""
    Spot trading (api.binance.com).
    """
    Margin = ...
    r"""
    Spot Margin trading (uses Spot API with margin endpoints).
    """
    UsdM = ...
    r"""
    USD-M Futures - linear perpetuals and delivery futures (fapi.binance.com).
    """
    CoinM = ...
    r"""
    COIN-M Futures - inverse perpetuals and delivery futures (dapi.binance.com).
    """
    Options = ...
    r"""
    European Options (eapi.binance.com).
    """

    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class BinanceSpotMarketDataMode(enum.Enum):
    r"""
    Spot market-data transport mode.
    """
    Sbe = ...
    r"""
    Spot SBE streams (requires Ed25519 credentials).
    """
    Json = ...
    r"""
    Force Spot public JSON streams (does not require credentials).
    """

def get_binance_arrow_schema_map(cls: type) -> typing.Any:
    r"""
    Returns a mapping from field names to Arrow data types for the `BinanceBar` class.
    
    # Errors
    
    Returns a `PyErr` if the class name is not recognized.
    """

