# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import enum
import typing
__all__ = [
    "AlpacaDataClientConfig",
    "AlpacaDataClientFactory",
    "AlpacaDataFeed",
    "AlpacaExecutionClientConfig",
    "AlpacaExecutionClientFactory",
]

@typing.final
class AlpacaDataClientConfig:
    ...

@typing.final
class AlpacaDataClientFactory:
    r"""
    Factory for creating Alpaca data clients.
    """
    ...

@typing.final
class AlpacaExecutionClientConfig:
    ...

@typing.final
class AlpacaExecutionClientFactory:
    r"""
    Factory for creating Alpaca execution clients.
    """
    ...

@typing.final
class AlpacaDataFeed(enum.Enum):
    Iex = ...
    Sip = ...

