# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import decimal
from nautilus_trader import common
from nautilus_trader import core
from nautilus_trader import data
from nautilus_trader import execution
from nautilus_trader import model
from nautilus_trader import portfolio
from nautilus_trader import risk
from nautilus_trader import trading
import typing
__all__ = [
    "BacktestDataConfig",
    "BacktestEngineConfig",
    "BacktestNode",
    "BacktestResult",
    "BacktestRunConfig",
    "BacktestVenueConfig",
    "FXRolloverInterestModule",
    "InterestRateRecord",
    "PyBacktestEngine",
]

@typing.final
class BacktestDataConfig:
    r"""
    Represents the data configuration for one specific backtest run.
    """
    @property
    def py_data_type(self) -> builtins.str: ...
    @property
    def py_catalog_path(self) -> builtins.str: ...
    @property
    def py_instrument_id(self) -> typing.Optional[model.InstrumentId]: ...
    def __new__(cls, data_type: builtins.str, catalog_path: builtins.str, catalog_fs_protocol: typing.Optional[builtins.str] = None, catalog_fs_storage_options: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, catalog_fs_rust_storage_options: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, instrument_id: typing.Optional[model.InstrumentId] = None, instrument_ids: typing.Optional[typing.Sequence[model.InstrumentId]] = None, start_time: typing.Optional[builtins.int] = None, end_time: typing.Optional[builtins.int] = None, filter_expr: typing.Optional[builtins.str] = None, client_id: typing.Optional[model.ClientId] = None, metadata: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, bar_spec: typing.Optional[model.BarSpecification] = None, bar_types: typing.Optional[typing.Sequence[builtins.str]] = None, optimize_file_loading: typing.Optional[builtins.bool] = None) -> BacktestDataConfig:
        r"""
        Represents the data configuration for one specific backtest run.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BacktestEngineConfig:
    r"""
    Configuration for ``BacktestEngine`` instances.
    """
    @property
    def py_trader_id(self) -> model.TraderId: ...
    @property
    def py_load_state(self) -> builtins.bool: ...
    @property
    def py_save_state(self) -> builtins.bool: ...
    @property
    def py_shutdown_on_error(self) -> builtins.bool: ...
    @property
    def py_bypass_logging(self) -> builtins.bool: ...
    @property
    def py_run_analysis(self) -> builtins.bool: ...
    @property
    def py_timeout_connection(self) -> builtins.float: ...
    @property
    def py_timeout_reconciliation(self) -> builtins.float: ...
    @property
    def py_timeout_portfolio(self) -> builtins.float: ...
    @property
    def py_timeout_disconnection(self) -> builtins.float: ...
    @property
    def py_delay_post_stop(self) -> builtins.float: ...
    @property
    def py_timeout_shutdown(self) -> builtins.float: ...
    @property
    def py_cache(self) -> typing.Optional[common.CacheConfig]: ...
    @property
    def py_msgbus(self) -> typing.Optional[common.MessageBusConfig]: ...
    @property
    def py_data_engine(self) -> typing.Optional[data.DataEngineConfig]: ...
    @property
    def py_risk_engine(self) -> typing.Optional[risk.RiskEngineConfig]: ...
    @property
    def py_exec_engine(self) -> typing.Optional[execution.ExecutionEngineConfig]: ...
    @property
    def py_portfolio(self) -> typing.Optional[portfolio.PortfolioConfig]: ...
    def __new__(cls, trader_id: typing.Optional[model.TraderId] = None, load_state: typing.Optional[builtins.bool] = None, save_state: typing.Optional[builtins.bool] = None, shutdown_on_error: typing.Optional[builtins.bool] = None, bypass_logging: typing.Optional[builtins.bool] = None, run_analysis: typing.Optional[builtins.bool] = None, timeout_connection: typing.Optional[builtins.int] = None, timeout_reconciliation: typing.Optional[builtins.int] = None, timeout_portfolio: typing.Optional[builtins.int] = None, timeout_disconnection: typing.Optional[builtins.int] = None, delay_post_stop: typing.Optional[builtins.int] = None, timeout_shutdown: typing.Optional[builtins.int] = None, logging: typing.Optional[common.LoggerConfig] = None, instance_id: typing.Optional[core.UUID4] = None, cache: typing.Optional[common.CacheConfig] = None, msgbus: typing.Optional[common.MessageBusConfig] = None, data_engine: typing.Optional[data.DataEngineConfig] = None, risk_engine: typing.Optional[risk.RiskEngineConfig] = None, exec_engine: typing.Optional[execution.ExecutionEngineConfig] = None, portfolio: typing.Optional[portfolio.PortfolioConfig] = None) -> BacktestEngineConfig:
        r"""
        Configuration for ``BacktestEngine`` instances.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BacktestNode:
    r"""
    Orchestrates catalog-driven backtests from run configurations.
    
    `BacktestNode` connects the [`ParquetDataCatalog`] with [`BacktestEngine`] to load
    historical data and run backtests. Supports both oneshot and streaming modes.
    """
    def __new__(cls, configs: typing.Sequence[BacktestRunConfig]) -> BacktestNode:
        r"""
        Orchestrates catalog-driven backtests from run configurations.
        
        `BacktestNode` connects the `ParquetDataCatalog` with `BacktestEngine` to load
        historical data and run backtests. Supports both oneshot and streaming modes.
        """
    def build(self) -> None:
        r"""
        Builds backtest engines from the run configurations.
        
        For each config, creates a `BacktestEngine`, adds venues, and loads
        instruments from the catalog.
        
        # Errors
        
        Returns an error if engine creation, venue setup, or instrument loading fails.
        """
    def run(self) -> builtins.list[BacktestResult]:
        r"""
        Runs all configured backtests and returns results.
        
        Automatically calls `build()` if engines have not been created yet.
        For each run config, loads data from the catalog and runs the engine.
        Supports both oneshot (`chunk_size = None`) and streaming modes.
        
        # Errors
        
        Returns an error if building, data loading, or engine execution fails.
        """
    def dispose(self) -> None:
        r"""
        Disposes all engines and releases resources.
        """
    def add_actor_from_config(self, run_config_id: builtins.str, config: common.ImportableActorConfig) -> None: ...
    def add_strategy_from_config(self, run_config_id: builtins.str, config: trading.ImportableStrategyConfig) -> None: ...
    def add_native_strategy(self, run_config_id: builtins.str, type_name: builtins.str, config: typing.Any) -> None:
        r"""
        Adds a compiled-in native Rust strategy to the engine for the given run config.
        
        The type name determines which built-in strategy is constructed.
        All execution happens in Rust; Python is the configuration layer.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BacktestResult:
    r"""
    Results from a completed backtest run.
    """
    @property
    def py_trader_id(self) -> builtins.str: ...
    @property
    def py_machine_id(self) -> builtins.str: ...
    @property
    def py_instance_id(self) -> core.UUID4: ...
    @property
    def py_run_config_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def py_elapsed_time_secs(self) -> builtins.float: ...
    @property
    def py_iterations(self) -> builtins.int: ...
    @property
    def py_total_events(self) -> builtins.int: ...
    @property
    def py_total_orders(self) -> builtins.int: ...
    @property
    def py_total_positions(self) -> builtins.int: ...
    @property
    def py_summary(self) -> builtins.dict[builtins.str, builtins.str]: ...
    @property
    def py_stats_pnls(self) -> builtins.dict[builtins.str, builtins.dict[builtins.str, builtins.float]]: ...
    @property
    def py_stats_returns(self) -> builtins.dict[builtins.str, builtins.float]: ...
    @property
    def py_stats_general(self) -> builtins.dict[builtins.str, builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BacktestRunConfig:
    r"""
    Represents the configuration for one specific backtest run.
    This includes a backtest engine with its actors and strategies, with the external inputs of venues and data.
    """
    @property
    def py_id(self) -> builtins.str: ...
    def __new__(cls, venues: typing.Sequence[BacktestVenueConfig], data: typing.Sequence[BacktestDataConfig], engine: typing.Optional[BacktestEngineConfig] = None, id: typing.Optional[builtins.str] = None, chunk_size: typing.Optional[builtins.int] = None, raise_exception: typing.Optional[builtins.bool] = None, dispose_on_completion: typing.Optional[builtins.bool] = None, start: typing.Optional[builtins.int] = None, end: typing.Optional[builtins.int] = None) -> BacktestRunConfig:
        r"""
        Represents the configuration for one specific backtest run.
        This includes a backtest engine with its actors and strategies, with the external inputs of venues and data.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BacktestVenueConfig:
    r"""
    Represents a venue configuration for one specific backtest engine.
    """
    @property
    def py_name(self) -> builtins.str: ...
    @property
    def py_oms_type(self) -> model.OmsType: ...
    @property
    def py_account_type(self) -> model.AccountType: ...
    @property
    def py_book_type(self) -> model.BookType: ...
    @property
    def py_starting_balances(self) -> builtins.list[builtins.str]: ...
    @property
    def py_bar_execution(self) -> builtins.bool: ...
    @property
    def py_trade_execution(self) -> builtins.bool: ...
    @property
    def py_liquidation_enabled(self) -> builtins.bool: ...
    @property
    def py_liquidation_trigger_ratio(self) -> builtins.float: ...
    @property
    def py_liquidation_cancel_open_orders(self) -> builtins.bool: ...
    def __new__(cls, name: builtins.str, oms_type: model.OmsType, account_type: model.AccountType, book_type: model.BookType, starting_balances: typing.Sequence[builtins.str], routing: typing.Optional[builtins.bool] = None, frozen_account: typing.Optional[builtins.bool] = None, reject_stop_orders: typing.Optional[builtins.bool] = None, support_gtd_orders: typing.Optional[builtins.bool] = None, support_contingent_orders: typing.Optional[builtins.bool] = None, use_position_ids: typing.Optional[builtins.bool] = None, use_random_ids: typing.Optional[builtins.bool] = None, use_reduce_only: typing.Optional[builtins.bool] = None, bar_execution: typing.Optional[builtins.bool] = None, bar_adaptive_high_low_ordering: typing.Optional[builtins.bool] = None, trade_execution: typing.Optional[builtins.bool] = None, use_market_order_acks: typing.Optional[builtins.bool] = None, liquidity_consumption: typing.Optional[builtins.bool] = None, allow_cash_borrowing: typing.Optional[builtins.bool] = None, queue_position: typing.Optional[builtins.bool] = None, oto_trigger_mode: typing.Optional[model.OtoTriggerMode] = None, base_currency: typing.Optional[model.Currency] = None, default_leverage: typing.Optional[decimal.Decimal] = None, leverages: typing.Optional[typing.Mapping[model.InstrumentId, decimal.Decimal]] = None, margin_model: typing.Optional[typing.Any] = None, modules: typing.Optional[typing.Sequence[typing.Any]] = None, fill_model: typing.Optional[typing.Any] = None, latency_model: typing.Optional[typing.Any] = None, fee_model: typing.Optional[typing.Any] = None, price_protection_points: typing.Optional[builtins.int] = None, settlement_prices: typing.Optional[typing.Mapping[model.InstrumentId, builtins.float]] = None, liquidation_enabled: typing.Optional[builtins.bool] = None, liquidation_trigger_ratio: typing.Optional[builtins.float] = None, liquidation_cancel_open_orders: typing.Optional[builtins.bool] = None) -> BacktestVenueConfig:
        r"""
        Represents a venue configuration for one specific backtest engine.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FXRolloverInterestModule:
    r"""
    Simulates FX rollover (swap) interest applied at 5 PM US/Eastern daily.
    
    When holding FX positions overnight, the interest rate differential
    between the two currencies is credited or debited. Wednesday and Friday
    rollovers are tripled (Wednesday for T+2 settlement, Friday for the weekend).
    """
    def __new__(cls, records: typing.Sequence[InterestRateRecord]) -> FXRolloverInterestModule:
        r"""
        Simulates FX rollover (swap) interest applied at 5 PM US/Eastern daily.
        
        When holding FX positions overnight, the interest rate differential
        between the two currencies is credited or debited. Wednesday and Friday
        rollovers are tripled (Wednesday for T+2 settlement, Friday for the weekend).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class InterestRateRecord:
    r"""
    A single interest rate data entry.
    """
    def __new__(cls, location: builtins.str, time: builtins.str, value: builtins.float) -> InterestRateRecord:
        r"""
        A single interest rate data entry.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PyBacktestEngine:
    r"""
    PyO3 wrapper around [`BacktestEngine`].
    
    Exposes the backtest engine to Python as `BacktestEngine`.
    Uses `unsendable` because the inner engine holds `Rc<RefCell<...>>`.
    """
    @property
    def py_trader_id(self) -> model.TraderId:
        r"""
        Returns the trader ID for this engine.
        """
    @property
    def py_machine_id(self) -> builtins.str:
        r"""
        Returns the machine ID for this engine.
        """
    @property
    def py_instance_id(self) -> core.UUID4:
        r"""
        Returns the unique instance ID for this engine.
        """
    @property
    def py_iteration(self) -> builtins.int:
        r"""
        Returns the current iteration count.
        """
    @property
    def py_run_config_id(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the last run config ID, if any.
        """
    @property
    def py_run_id(self) -> typing.Optional[core.UUID4]:
        r"""
        Returns the last run ID, if any.
        """
    @property
    def py_run_started(self) -> typing.Optional[builtins.int]:
        r"""
        Returns when the last run started, in nanoseconds since the UNIX epoch.
        """
    @property
    def py_run_finished(self) -> typing.Optional[builtins.int]:
        r"""
        Returns when the last run finished, in nanoseconds since the UNIX epoch.
        """
    @property
    def py_backtest_start(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the last backtest range start, in nanoseconds since the UNIX epoch.
        """
    @property
    def py_backtest_end(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the last backtest range end, in nanoseconds since the UNIX epoch.
        """
    @property
    def py_cache(self) -> common.PyCache:
        r"""
        Returns the cache shared with the kernel and registered components.
        """
    def add_defi_data(self, data: typing.Sequence[model.DefiData], client_id: typing.Optional[model.ClientId] = None, sort: builtins.bool = ...) -> None:
        r"""
        Adds DeFi data to the engine.
        """
    def __new__(cls, config: BacktestEngineConfig) -> PyBacktestEngine: ...
    def add_venue(self, venue: model.Venue, oms_type: model.OmsType, account_type: model.AccountType, starting_balances: typing.Sequence[model.Money], base_currency: typing.Optional[model.Currency] = None, default_leverage: typing.Optional[decimal.Decimal] = None, leverages: typing.Optional[typing.Mapping[model.InstrumentId, decimal.Decimal]] = None, margin_model: typing.Optional[typing.Any] = None, fill_model: typing.Optional[typing.Any] = None, fee_model: typing.Optional[typing.Any] = None, latency_model: typing.Optional[typing.Any] = None, modules: typing.Optional[typing.Sequence[typing.Any]] = None, book_type: model.BookType = model...., routing: builtins.bool = ..., reject_stop_orders: builtins.bool = ..., support_gtd_orders: builtins.bool = ..., support_contingent_orders: builtins.bool = ..., use_position_ids: builtins.bool = ..., use_random_ids: builtins.bool = ..., use_reduce_only: builtins.bool = ..., use_message_queue: builtins.bool = ..., use_market_order_acks: builtins.bool = ..., bar_execution: builtins.bool = ..., bar_adaptive_high_low_ordering: builtins.bool = ..., trade_execution: builtins.bool = ..., liquidity_consumption: builtins.bool = ..., queue_position: builtins.bool = ..., allow_cash_borrowing: builtins.bool = ..., frozen_account: builtins.bool = ..., oto_trigger_mode: model.OtoTriggerMode = model...., price_protection_points: typing.Optional[builtins.int] = None, settlement_prices: typing.Optional[typing.Mapping[model.InstrumentId, model.Price]] = None, liquidation_enabled: builtins.bool = ..., liquidation_trigger_ratio: typing.Optional[builtins.float] = None, liquidation_cancel_open_orders: builtins.bool = ...) -> None:
        r"""
        Adds a simulated exchange with the given parameters to the engine.
        
        # Liquidation parameters
        
        - `liquidation_enabled` (bool, default `False`): if margin liquidation should be
          triggered when the account's equity falls to or below the maintenance
          margin threshold scaled by `liquidation_trigger_ratio`.
        - `liquidation_trigger_ratio` (float, optional, default `1.0`): the ratio of
          maintenance margin used as the liquidation threshold. A value of `1.0`
          liquidates when equity <= maintenance margin; higher values trigger earlier.
        - `liquidation_cancel_open_orders` (bool, default `True`): if open resting
          orders for the venue should be cancelled before synthetic close-out fills
          are emitted for open positions.
        """
    def change_fill_model(self, venue: model.Venue, fill_model: typing.Any) -> None:
        r"""
        Changes the fill model for a venue.
        """
    def add_data(self, data: typing.Sequence[typing.Any], client_id: typing.Optional[model.ClientId] = None, validate: builtins.bool = ..., sort: builtins.bool = ...) -> None:
        r"""
        Adds data to the engine.
        """
    def add_instrument(self, instrument: typing.Any) -> None:
        r"""
        Adds an instrument to the engine.
        """
    def add_actor_from_config(self, config: common.ImportableActorConfig) -> None:
        r"""
        Adds an actor from an importable config.
        """
    def add_strategy_from_config(self, config: trading.ImportableStrategyConfig) -> None:
        r"""
        Adds a strategy from an importable config.
        """
    def add_native_strategy(self, type_name: builtins.str, config: typing.Any) -> None:
        r"""
        Adds a compiled-in native Rust strategy from its type name and config.
        
        The type name determines which built-in strategy is constructed.
        All execution happens in Rust; Python is the configuration layer.
        """
    def add_native_actor(self, type_name: builtins.str, config: typing.Any) -> None:
        r"""
        Adds a compiled-in native Rust actor from its type name and config.
        
        The type name determines which built-in actor is constructed.
        All execution happens in Rust; Python is the configuration layer.
        """
    def run(self, start: typing.Optional[builtins.int] = None, end: typing.Optional[builtins.int] = None, run_config_id: typing.Optional[builtins.str] = None, streaming: builtins.bool = ...) -> None:
        r"""
        Runs the backtest engine.
        """
    def end(self) -> None:
        r"""
        Ends the backtest run, finalizing results.
        """
    def reset(self) -> None:
        r"""
        Resets the engine state for a new run.
        """
    def dispose(self) -> None:
        r"""
        Disposes of the engine, releasing all resources.
        """
    def get_result(self) -> BacktestResult:
        r"""
        Returns the backtest result from the last run.
        """
    def clear_data(self) -> None:
        r"""
        Clears all data from the engine.
        """
    def clear_actors(self) -> None:
        r"""
        Clears all actors from the engine.
        """
    def clear_strategies(self) -> None:
        r"""
        Clears all strategies from the engine.
        """
    def clear_exec_algorithms(self) -> None:
        r"""
        Clears all execution algorithms from the engine.
        """
    def add_actors_from_configs(self, configs: typing.Sequence[common.ImportableActorConfig]) -> None:
        r"""
        Adds multiple actors from importable configs. Stops at the first error.
        """
    def add_strategies_from_configs(self, configs: typing.Sequence[trading.ImportableStrategyConfig]) -> None:
        r"""
        Adds multiple strategies from importable configs. Stops at the first error.
        """
    def sort_data(self) -> None:
        r"""
        Sorts the engine's internal data stream by timestamp.
        """
    def list_venues(self) -> builtins.list[model.Venue]:
        r"""
        Returns the list of registered venue identifiers.
        """
    def __repr__(self) -> builtins.str: ...

