[package]
name = "nautilus_alpaca"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
finstream = { path = "../../finstream" }
nautilus_common = { path = "../../common" }
nautilus_core = { path = "../../core" }
nautilus_model = { path = "../../model" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
