# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
from nautilus_trader import model
import typing
__all__ = [
    "LighterDataClientConfig",
    "LighterDataClientFactory",
    "LighterEnvironment",
    "LighterExecClientConfig",
    "LighterExecutionClientFactory",
    "py_revoke_lighter_integrator",
]

@typing.final
class LighterDataClientConfig:
    r"""
    Configuration for the Lighter data client.
    """
    def py_new(self, base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[LighterEnvironment], account_index: typing.Optional[builtins.int], api_key_index: typing.Optional[builtins.int], private_key: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], ws_timeout_secs: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], rest_quota_per_min: typing.Optional[builtins.int]) -> LighterDataClientConfig:
        r"""
        Configuration for the Lighter live data client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LighterDataClientFactory:
    r"""
    Factory for creating Lighter data clients.
    """
    def py_new(self) -> LighterDataClientFactory:
        r"""
        Factory for creating Lighter data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class LighterExecClientConfig:
    r"""
    Configuration for the Lighter execution client.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId, account_index: typing.Optional[builtins.int], api_key_index: typing.Optional[builtins.int], private_key: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], environment: typing.Optional[LighterEnvironment], http_timeout_secs: typing.Optional[builtins.int], ws_timeout_secs: typing.Optional[builtins.int], active_markets: typing.Optional[typing.Sequence[builtins.int]], market_order_slippage_bps: typing.Optional[builtins.int], rest_quota_per_min: typing.Optional[builtins.int], sendtx_quota_per_min: typing.Optional[builtins.int]) -> LighterExecClientConfig:
        r"""
        Configuration for the Lighter live execution client.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LighterExecutionClientFactory:
    r"""
    Factory for creating Lighter execution clients.
    """
    def py_new(self) -> LighterExecutionClientFactory:
        r"""
        Factory for creating Lighter execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class LighterEnvironment(enum.Enum):
    r"""
    Lighter API environment.
    """
    Mainnet = ...
    r"""
    Mainnet trading environment.
    """
    Testnet = ...
    r"""
    Testnet environment.
    """

def py_revoke_lighter_integrator(environment: LighterEnvironment) -> typing.Any:
    r"""
    Revoke the Nautilus integrator approval when leaving the adapter.
    
    This cleanup call is not a trading-mode toggle. Live trading through this
    adapter requires the approval; the next execution-client startup records a
    fresh zero-fee approval.
    
    See:
    <https://nautilustrader.io/docs/nightly/integrations/lighter.html#integrator-attribution>.
    
    Reads L2 credentials from `LIGHTER_API_KEY_INDEX`, `LIGHTER_API_SECRET`,
    and `LIGHTER_ACCOUNT_INDEX` (or the `LIGHTER_TESTNET_*` variants).
    
    Returns a status string on the awaitable; raises on failure.
    """

