# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import enum
from nautilus_trader import model
import typing
__all__ = [
    "BybitAccountDetails",
    "BybitAccountType",
    "BybitApiKeyPermissions",
    "BybitCancelType",
    "BybitDataClientConfig",
    "BybitDataClientFactory",
    "BybitEnvironment",
    "BybitExecClientConfig",
    "BybitExecutionClientFactory",
    "BybitFeeRate",
    "BybitHttpClient",
    "BybitMarginAction",
    "BybitMarginBorrowResult",
    "BybitMarginMode",
    "BybitMarginRepayResult",
    "BybitMarginStatusResult",
    "BybitOpenOnly",
    "BybitOrder",
    "BybitOrderCursorList",
    "BybitOrderFilter",
    "BybitOrderSide",
    "BybitOrderStatus",
    "BybitOrderType",
    "BybitPositionIdx",
    "BybitPositionMode",
    "BybitProductType",
    "BybitRawHttpClient",
    "BybitServerTime",
    "BybitStopOrderType",
    "BybitTickerData",
    "BybitTickersParams",
    "BybitTimeInForce",
    "BybitTpSlMode",
    "BybitTriggerDirection",
    "BybitTriggerType",
    "BybitWebSocketClient",
    "BybitWebSocketError",
    "BybitWsAmendOrderParams",
    "BybitWsCancelOrderParams",
    "BybitWsPlaceOrderParams",
    "py_bybit_bar_spec_to_interval",
    "py_bybit_extract_raw_symbol",
    "py_bybit_make_hedge_venue_position_id",
    "py_bybit_product_type_from_symbol",
    "py_bybit_resolve_position_idx",
    "py_get_bybit_http_base_url",
    "py_get_bybit_ws_url_private",
    "py_get_bybit_ws_url_public",
    "py_get_bybit_ws_url_trade",
]

@typing.final
class BybitAccountDetails:
    r"""
    Account details from API key info.
    """
    ...

@typing.final
class BybitApiKeyPermissions:
    r"""
    API key permissions.
    """
    ...

@typing.final
class BybitDataClientConfig:
    r"""
    Configuration for the Bybit live data client.
    """
    def py_new(self, product_types: typing.Optional[typing.Sequence[BybitProductType]], environment: typing.Optional[BybitEnvironment], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws_public: typing.Optional[builtins.str], base_url_ws_private: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], update_instruments_interval_mins: typing.Optional[builtins.int], instrument_status_poll_secs: typing.Optional[builtins.int]) -> BybitDataClientConfig:
        r"""
        Configuration for the Bybit live data client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BybitDataClientFactory:
    r"""
    Factory for creating Bybit data clients.
    """
    def py_new(self) -> BybitDataClientFactory:
        r"""
        Factory for creating Bybit data clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BybitExecClientConfig:
    r"""
    Configuration for the Bybit live execution client.
    """
    def py_new(self, product_types: typing.Optional[typing.Sequence[BybitProductType]], environment: typing.Optional[BybitEnvironment], api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url_http: typing.Optional[builtins.str], base_url_ws_private: typing.Optional[builtins.str], base_url_ws_trade: typing.Optional[builtins.str], proxy_url: typing.Optional[builtins.str], http_timeout_secs: typing.Optional[builtins.int], max_retries: typing.Optional[builtins.int], retry_delay_initial_ms: typing.Optional[builtins.int], retry_delay_max_ms: typing.Optional[builtins.int], heartbeat_interval_secs: typing.Optional[builtins.int], recv_window_ms: typing.Optional[builtins.int], account_id: typing.Optional[model.AccountId], use_spot_position_reports: typing.Optional[builtins.bool], margin_mode: typing.Optional[BybitMarginMode]) -> BybitExecClientConfig:
        r"""
        Configuration for the Bybit live execution client.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BybitExecutionClientFactory:
    r"""
    Factory for creating Bybit execution clients.
    """
    def py_new(self, trader_id: model.TraderId, account_id: model.AccountId) -> BybitExecutionClientFactory:
        r"""
        Factory for creating Bybit execution clients.
        """
    def py_name(self) -> builtins.str: ...

@typing.final
class BybitFeeRate:
    r"""
    Fee rate structure returned by `GET /v5/account/fee-rate`.
    
    # References
    - <https://bybit-exchange.github.io/docs/v5/account/fee-rate>
    """
    ...

@typing.final
class BybitHttpClient:
    r"""
    Provides a HTTP client for connecting to the [Bybit](https://bybit.com) REST API.
    High-level HTTP client that wraps the raw client and provides Nautilus domain types.
    
    This client maintains an instrument cache and uses it to parse venue responses
    into Nautilus domain objects.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], demo: builtins.bool, testnet: builtins.bool, timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, recv_window_ms: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BybitHttpClient:
        r"""
        Provides a HTTP client for connecting to the [Bybit](https://bybit.com) REST API.
        High-level HTTP client that wraps the raw client and provides Nautilus domain types.
        
        This client maintains an instrument cache and uses it to parse venue responses
        into Nautilus domain objects.
        """
    def py_base_url(self) -> builtins.str: ...
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Any existing instrument with the same symbol will be replaced.
        """
    def py_cancel_all_requests(self) -> None: ...
    def py_set_use_spot_position_reports(self, value: builtins.bool) -> None: ...
    def py_set_margin_mode(self, margin_mode: BybitMarginMode) -> typing.Any:
        r"""
        Sets margin mode (requires authentication).
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/account/set-margin-mode>
        """
    def py_get_account_details(self) -> typing.Any:
        r"""
        Fetches API key information including account details (requires authentication).
        
        # Errors
        
        Returns an error if:
        - The request fails.
        - The response cannot be parsed.
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/user/apikey-info>
        """
    def py_set_leverage(self, product_type: BybitProductType, symbol: builtins.str, buy_leverage: builtins.str, sell_leverage: builtins.str) -> typing.Any:
        r"""
        Sets leverage for a symbol (requires authentication).
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/position/leverage>
        """
    def py_switch_mode(self, product_type: BybitProductType, mode: BybitPositionMode, symbol: typing.Optional[builtins.str], coin: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Switches position mode (requires authentication).
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/position/position-mode>
        """
    def py_get_spot_borrow_amount(self, coin: builtins.str) -> typing.Any:
        r"""
        Get the outstanding spot borrow amount for a specific coin.
        
        Returns zero if no borrow exists.
        
        # Parameters
        
        - `coin`: The coin to check (e.g., "BTC", "ETH")
        """
    def py_borrow_spot(self, coin: builtins.str, amount: model.Quantity) -> typing.Any:
        r"""
        Borrows coins for spot margin trading.
        
        This should be called before opening short spot positions.
        
        # Parameters
        
        - `coin`: The coin to repay (e.g., "BTC", "ETH")
        - `amount`: Optional amount to borrow. If None, repays all outstanding borrows.
        """
    def py_repay_spot_borrow(self, coin: builtins.str, amount: typing.Optional[model.Quantity]) -> typing.Any:
        r"""
        Repays spot borrows for a specific coin.
        
        This should be called after closing short spot positions to avoid accruing interest.
        
        # Parameters
        
        - `coin`: The coin to repay (e.g., "BTC", "ETH")
        - `amount`: Optional amount to repay. If None, repays all outstanding borrows.
        """
    def py_request_instruments(self, product_type: BybitProductType, symbol: typing.Optional[builtins.str], base_coin: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Request instruments for a given product type.
        
        When `base_coin` is provided, the request is narrowed to that base coin.
        This is required for `Option`: Bybit's API returns only `BTC` options when
        `baseCoin` is omitted.
        """
    def py_request_instrument_statuses(self, product_type: BybitProductType) -> typing.Any:
        r"""
        Fetches instrument info and returns the current status of each symbol.
        
        Paginates through the instruments endpoint collecting only
        `(InstrumentId, MarketStatusAction)` pairs. This avoids fee-rate
        fetching and full instrument parsing.
        """
    def py_request_tickers(self, params: BybitTickersParams) -> typing.Any:
        r"""
        Request ticker information for market data.
        
        Fetches ticker data from Bybit's `/v5/market/tickers` endpoint and returns
        a unified `BybitTickerData` structure compatible with all product types.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/market/tickers>
        """
    def py_submit_order(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, time_in_force: typing.Optional[model.TimeInForce], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], post_only: typing.Optional[builtins.bool], reduce_only: builtins.bool, is_quote_quantity: builtins.bool, is_leverage: builtins.bool, position_idx: typing.Optional[BybitPositionIdx], bbo_side_type: typing.Optional[builtins.str], bbo_level: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Submit a new order.
        """
    def py_modify_order(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Modify an existing order.
        """
    def py_cancel_order(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancel an order.
        """
    def py_cancel_all_orders(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Cancel all orders for an instrument.
        """
    def py_query_order(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: model.InstrumentId, client_order_id: typing.Optional[model.ClientOrderId], venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Query a single order by client order ID or venue order ID.
        """
    def py_request_trades(self, product_type: BybitProductType, instrument_id: model.InstrumentId, limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request recent trade tick history for a given symbol.
        
        Returns the most recent public trades from Bybit's `/v5/market/recent-trade` endpoint.
        This endpoint only provides recent trades (up to 1000 most recent), typically covering
        only the last few minutes for active markets.
        
        **Note**: For historical trade data with time ranges, use the klines endpoint instead.
        The Bybit public API does not support fetching historical trades by time range.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/market/recent-trade>
        """
    def py_request_funding_rates(self, product_type: BybitProductType, instrument_id: model.InstrumentId, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request funding rate history for a given symbol.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/market/history-fund-rate>
        """
    def py_request_orderbook_snapshot(self, product_type: BybitProductType, instrument_id: model.InstrumentId, limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request an orderbook snapshot for a given symbol.
        
        Bybit limits the amount of levels (depth) for each product type to:
        - Spot: `1..=200` (default: `1`)
        - Linear & Inverse: `1..=500` (default: `25`)
        - Options: `1..=25` (default: `1`)
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/market/orderbook>
        """
    def py_request_bars(self, product_type: BybitProductType, bar_type: model.BarType, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int], timestamp_on_close: builtins.bool) -> typing.Any:
        r"""
        Request bar/kline history for a given symbol.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/market/kline>
        """
    def py_request_fee_rates(self, product_type: BybitProductType, symbol: typing.Optional[builtins.str], base_coin: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Requests trading fee rates for the specified product type and optional filters.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/account/fee-rate>
        """
    def py_request_account_state(self, account_type: BybitAccountType, account_id: model.AccountId) -> typing.Any:
        r"""
        Requests the current account state for the specified account type.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/account/wallet-balance>
        """
    def py_request_order_status_reports(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: typing.Optional[model.InstrumentId], open_only: builtins.bool, start: typing.Optional[datetime.datetime], end: typing.Optional[datetime.datetime], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Request multiple order status reports.
        
        Orders for instruments not currently loaded in cache will be skipped.
        """
    def py_request_fill_reports(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: typing.Optional[model.InstrumentId], start: typing.Optional[builtins.int], end: typing.Optional[builtins.int], limit: typing.Optional[builtins.int]) -> typing.Any:
        r"""
        Fetches execution history (fills) for the account and returns a list of `FillReport`s.
        
        Executions for instruments not currently loaded in cache will be skipped.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/order/execution>
        """
    def py_request_position_status_reports(self, account_id: model.AccountId, product_type: BybitProductType, instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any:
        r"""
        Fetches position information for the account and returns a list of `PositionStatusReport`s.
        
        Positions for instruments not currently loaded in cache will be skipped.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/position>
        """
    def py_request_forward_prices(self, base_coin: builtins.str, instrument_id: typing.Optional[model.InstrumentId]) -> typing.Any:
        r"""
        Request forward prices for option chain ATM determination.
        
        Single-instrument path (1 HTTP call) if `instrument_id` is provided,
        otherwise bulk path via option tickers.
        """

@typing.final
class BybitMarginBorrowResult:
    r"""
    Result from a Bybit borrow operation for strategy consumption.
    """
    def py_new(self, coin: builtins.str, amount: builtins.str, success: builtins.bool, message: builtins.str, ts_event: builtins.int, ts_init: builtins.int) -> BybitMarginBorrowResult:
        r"""
        Result from a Bybit borrow operation for strategy consumption.
        """
    def coin(self) -> builtins.str: ...
    def amount(self) -> builtins.str: ...
    def success(self) -> builtins.bool: ...
    def message(self) -> builtins.str: ...
    def ts_event(self) -> builtins.int: ...
    def ts_init(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BybitMarginRepayResult:
    r"""
    Result from a Bybit repay operation for strategy consumption.
    """
    def py_new(self, coin: builtins.str, amount: typing.Optional[builtins.str], success: builtins.bool, result_status: builtins.str, message: builtins.str, ts_event: builtins.int, ts_init: builtins.int) -> BybitMarginRepayResult:
        r"""
        Result from a Bybit repay operation for strategy consumption.
        """
    def coin(self) -> builtins.str: ...
    def amount(self) -> typing.Optional[builtins.str]: ...
    def success(self) -> builtins.bool: ...
    def result_status(self) -> builtins.str: ...
    def message(self) -> builtins.str: ...
    def ts_event(self) -> builtins.int: ...
    def ts_init(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BybitMarginStatusResult:
    r"""
    Result with current borrowed amount on Bybit.
    """
    def py_new(self, coin: builtins.str, borrow_amount: builtins.str, ts_event: builtins.int, ts_init: builtins.int) -> BybitMarginStatusResult:
        r"""
        Result with current borrowed amount on Bybit.
        """
    def coin(self) -> builtins.str: ...
    def borrow_amount(self) -> builtins.str: ...
    def ts_event(self) -> builtins.int: ...
    def ts_init(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BybitOrder:
    r"""
    Order representation as returned by order-related endpoints.
    
    # References
    - <https://bybit-exchange.github.io/docs/v5/order/order-list>
    """
    ...

@typing.final
class BybitOrderCursorList:
    r"""
    Cursor-paginated list of orders for Python bindings.
    """
    ...

@typing.final
class BybitRawHttpClient:
    r"""
    Raw HTTP client for low-level Bybit API operations.
    
    This client handles request/response operations with the Bybit API,
    returning venue-specific response types. It does not parse to Nautilus domain types.
    """
    def py_new(self, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], base_url: typing.Optional[builtins.str], demo: builtins.bool, testnet: builtins.bool, timeout_secs: builtins.int, max_retries: builtins.int, retry_delay_ms: builtins.int, retry_delay_max_ms: builtins.int, recv_window_ms: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BybitRawHttpClient:
        r"""
        Raw HTTP client for low-level Bybit API operations.
        
        This client handles request/response operations with the Bybit API,
        returning venue-specific response types. It does not parse to Nautilus domain types.
        """
    def py_base_url(self) -> builtins.str:
        r"""
        Returns the base URL used for requests.
        """
    def py_api_key(self) -> typing.Optional[builtins.str]: ...
    def py_recv_window_ms(self) -> builtins.int:
        r"""
        Returns the configured receive window in milliseconds.
        """
    def py_cancel_all_requests(self) -> None:
        r"""
        Cancels all pending HTTP requests.
        """
    def py_get_server_time(self) -> typing.Any:
        r"""
        Fetches the current server time from Bybit.
        
        # Errors
        
        Returns an error if the request fails or the response cannot be parsed.
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/market/time>
        """
    def py_get_open_orders(self, category: BybitProductType, symbol: typing.Optional[builtins.str], base_coin: typing.Optional[builtins.str], settle_coin: typing.Optional[builtins.str], order_id: typing.Optional[builtins.str], order_link_id: typing.Optional[builtins.str], open_only: typing.Optional[BybitOpenOnly], order_filter: typing.Optional[BybitOrderFilter], limit: typing.Optional[builtins.int], cursor: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Fetches open orders (requires authentication).
        
        # References
        
        - <https://bybit-exchange.github.io/docs/v5/order/open-order>
        """

@typing.final
class BybitServerTime:
    r"""
    Response payload returned by `GET /v5/market/time`.
    
    # References
    - <https://bybit-exchange.github.io/docs/v5/market/time>
    """
    ...

@typing.final
class BybitTickerData:
    r"""
    Unified ticker data structure containing common fields across all product types.
    
    This simplified ticker structure is designed to work across SPOT, LINEAR, and OPTION products,
    containing only the most commonly used fields.
    """
    ...

@typing.final
class BybitTickersParams:
    r"""
    Parameters for fetching tickers via HTTP API.
    """
    def py_new(self, category: BybitProductType, symbol: typing.Optional[builtins.str], base_coin: typing.Optional[builtins.str], exp_date: typing.Optional[builtins.str]) -> BybitTickersParams:
        r"""
        Query parameters for `GET /v5/market/tickers`.
        
        # References
        - <https://bybit-exchange.github.io/docs/v5/market/tickers>
        """

@typing.final
class BybitWebSocketClient:
    r"""
    Public/market data WebSocket client for Bybit.
    """
    def py_new_public(self, product_type: BybitProductType, environment: BybitEnvironment, url: typing.Optional[builtins.str], heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BybitWebSocketClient:
        r"""
        Creates a new Bybit public WebSocket client.
        """
    def py_new_private(self, environment: BybitEnvironment, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], url: typing.Optional[builtins.str], heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BybitWebSocketClient:
        r"""
        Creates a new Bybit private WebSocket client.
        
        If `api_key` or `api_secret` are not provided, they will be loaded from
        environment variables based on the environment:
        - Demo: `BYBIT_DEMO_API_KEY`, `BYBIT_DEMO_API_SECRET`
        - Testnet: `BYBIT_TESTNET_API_KEY`, `BYBIT_TESTNET_API_SECRET`
        - Mainnet: `BYBIT_API_KEY`, `BYBIT_API_SECRET`
        """
    def py_new_trade(self, environment: BybitEnvironment, api_key: typing.Optional[builtins.str], api_secret: typing.Optional[builtins.str], url: typing.Optional[builtins.str], heartbeat: builtins.int, proxy_url: typing.Optional[builtins.str]) -> BybitWebSocketClient:
        r"""
        Creates a new Bybit trade WebSocket client for order operations.
        
        If `api_key` or `api_secret` are not provided, they will be loaded from
        environment variables based on the environment:
        - Demo: `BYBIT_DEMO_API_KEY`, `BYBIT_DEMO_API_SECRET`
        - Testnet: `BYBIT_TESTNET_API_KEY`, `BYBIT_TESTNET_API_SECRET`
        - Mainnet: `BYBIT_API_KEY`, `BYBIT_API_SECRET`
        """
    def py_api_key_masked(self) -> typing.Optional[builtins.str]: ...
    def py_is_active(self) -> builtins.bool:
        r"""
        Returns a value indicating whether the client is active.
        """
    def py_is_closed(self) -> builtins.bool:
        r"""
        Returns a value indicating whether the client is closed.
        """
    def py_subscription_count(self) -> builtins.int:
        r"""
        Returns the number of currently registered subscriptions.
        """
    def py_cache_instrument(self, instrument: typing.Any) -> None:
        r"""
        Adds an instrument to the shared instruments cache.
        """
    def py_set_account_id(self, account_id: model.AccountId) -> None:
        r"""
        Sets the account ID for account message parsing.
        """
    def py_set_mm_level(self, mm_level: builtins.int) -> None:
        r"""
        Sets the account market maker level.
        """
    def py_set_bars_timestamp_on_close(self, value: builtins.bool) -> None:
        r"""
        Sets whether bar timestamps use the close time.
        """
    def py_add_option_greeks_sub(self, instrument_id: model.InstrumentId) -> None:
        r"""
        Adds an instrument ID to the option greeks subscription set.
        """
    def py_remove_option_greeks_sub(self, instrument_id: model.InstrumentId) -> None:
        r"""
        Removes an instrument ID from the option greeks subscription set.
        """
    def py_connect(self, loop_: typing.Any, callback: typing.Any) -> typing.Any:
        r"""
        Disconnects the WebSocket client and stops the background task.
        """
    def py_close(self) -> typing.Any: ...
    def py_subscribe(self, topics: typing.Sequence[builtins.str]) -> typing.Any:
        r"""
        Subscribe to the provided topic strings.
        """
    def py_unsubscribe(self, topics: typing.Sequence[builtins.str]) -> typing.Any:
        r"""
        Unsubscribe from the provided topics.
        """
    def py_subscribe_orderbook(self, instrument_id: model.InstrumentId, depth: builtins.int) -> typing.Any:
        r"""
        Subscribes to orderbook updates for a specific instrument.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook>
        """
    def py_unsubscribe_orderbook(self, instrument_id: model.InstrumentId, depth: builtins.int) -> typing.Any:
        r"""
        Unsubscribes from orderbook updates for a specific instrument.
        """
    def py_subscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to public trade updates for a specific instrument.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/public/trade>
        """
    def py_unsubscribe_trades(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from public trade updates for a specific instrument.
        """
    def py_subscribe_ticker(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Subscribes to ticker updates for a specific instrument.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/public/ticker>
        """
    def py_subscribe_option_greeks(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_option_greeks(self, instrument_id: model.InstrumentId) -> typing.Any: ...
    def py_unsubscribe_ticker(self, instrument_id: model.InstrumentId) -> typing.Any:
        r"""
        Unsubscribes from ticker updates for a specific instrument.
        """
    def py_subscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Subscribes to kline/candlestick updates for a specific instrument.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/public/kline>
        """
    def py_unsubscribe_bars(self, bar_type: model.BarType) -> typing.Any:
        r"""
        Unsubscribes from kline/candlestick updates for a specific instrument.
        """
    def py_subscribe_orders(self) -> typing.Any:
        r"""
        Subscribes to order updates.
        
        # Errors
        
        Returns an error if the subscription request fails or if not authenticated.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/private/order>
        """
    def py_unsubscribe_orders(self) -> typing.Any:
        r"""
        Unsubscribes from order updates.
        """
    def py_subscribe_executions(self) -> typing.Any:
        r"""
        Subscribes to execution/fill updates.
        
        # Errors
        
        Returns an error if the subscription request fails or if not authenticated.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/private/execution>
        """
    def py_unsubscribe_executions(self) -> typing.Any:
        r"""
        Unsubscribes from execution/fill updates.
        """
    def py_subscribe_positions(self) -> typing.Any:
        r"""
        Subscribes to position updates.
        
        # Errors
        
        Returns an error if the subscription request fails or if not authenticated.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/private/position>
        """
    def py_unsubscribe_positions(self) -> typing.Any:
        r"""
        Unsubscribes from position updates.
        """
    def py_subscribe_wallet(self) -> typing.Any:
        r"""
        Subscribes to wallet/balance updates.
        
        # Errors
        
        Returns an error if the subscription request fails or if not authenticated.
        
        # References
        
        <https://bybit-exchange.github.io/docs/v5/websocket/private/wallet>
        """
    def py_unsubscribe_wallet(self) -> typing.Any:
        r"""
        Unsubscribes from wallet/balance updates.
        """
    def py_wait_until_active(self, timeout_secs: builtins.float) -> typing.Any:
        r"""
        Waits until the WebSocket client becomes active or times out.
        """
    def py_submit_order(self, product_type: BybitProductType, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, is_quote_quantity: builtins.bool, time_in_force: typing.Optional[model.TimeInForce], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], post_only: typing.Optional[builtins.bool], reduce_only: typing.Optional[builtins.bool], is_leverage: builtins.bool, position_idx: typing.Optional[BybitPositionIdx], bbo_side_type: typing.Optional[builtins.str], bbo_level: typing.Optional[builtins.str]) -> typing.Any:
        r"""
        Submits an order using Nautilus domain objects.
        """
    def py_modify_order(self, product_type: BybitProductType, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price]) -> typing.Any:
        r"""
        Modifies an existing order using Nautilus domain objects.
        """
    def py_cancel_order(self, product_type: BybitProductType, trader_id: model.TraderId, strategy_id: model.StrategyId, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, venue_order_id: typing.Optional[model.VenueOrderId]) -> typing.Any:
        r"""
        Cancels an order via WebSocket, returning the request ID for correlation.
        """
    def py_build_place_order_params(self, product_type: BybitProductType, instrument_id: model.InstrumentId, client_order_id: model.ClientOrderId, order_side: model.OrderSide, order_type: model.OrderType, quantity: model.Quantity, is_quote_quantity: builtins.bool, time_in_force: typing.Optional[model.TimeInForce], price: typing.Optional[model.Price], trigger_price: typing.Optional[model.Price], trigger_type: typing.Optional[model.TriggerType], post_only: typing.Optional[builtins.bool], reduce_only: typing.Optional[builtins.bool], is_leverage: builtins.bool, take_profit: typing.Optional[model.Price], stop_loss: typing.Optional[model.Price], position_idx: typing.Optional[BybitPositionIdx], bbo_side_type: typing.Optional[builtins.str], bbo_level: typing.Optional[builtins.str]) -> BybitWsPlaceOrderParams:
        r"""
        Builds order params for placing an order.
        """
    def py_batch_cancel_orders(self, trader_id: model.TraderId, strategy_id: model.StrategyId, orders: typing.Sequence[BybitWsCancelOrderParams]) -> typing.Any:
        r"""
        Batch cancels multiple orders via WebSocket, returning the request ID for correlation.
        """
    def py_build_amend_order_params(self, product_type: BybitProductType, instrument_id: model.InstrumentId, venue_order_id: typing.Optional[model.VenueOrderId], client_order_id: typing.Optional[model.ClientOrderId], quantity: typing.Optional[model.Quantity], price: typing.Optional[model.Price]) -> BybitWsAmendOrderParams:
        r"""
        Builds order params for amending an order.
        """
    def py_build_cancel_order_params(self, product_type: BybitProductType, instrument_id: model.InstrumentId, venue_order_id: typing.Optional[model.VenueOrderId], client_order_id: typing.Optional[model.ClientOrderId]) -> BybitWsCancelOrderParams:
        r"""
        Builds order params for canceling an order via WebSocket.
        """
    def py_batch_modify_orders(self, trader_id: model.TraderId, strategy_id: model.StrategyId, orders: typing.Sequence[BybitWsAmendOrderParams]) -> typing.Any: ...
    def py_batch_place_orders(self, trader_id: model.TraderId, strategy_id: model.StrategyId, orders: typing.Sequence[BybitWsPlaceOrderParams]) -> typing.Any:
        r"""
        Batch creates multiple orders via WebSocket, returning the request ID for correlation.
        """

@typing.final
class BybitWebSocketError:
    r"""
    Represents an error event surfaced by the WebSocket client.
    """
    def __repr__(self) -> builtins.str: ...
    def code(self) -> builtins.int: ...
    def message(self) -> builtins.str: ...
    def conn_id(self) -> typing.Optional[builtins.str]: ...
    def topic(self) -> typing.Optional[builtins.str]: ...
    def req_id(self) -> typing.Optional[builtins.str]: ...

@typing.final
class BybitWsAmendOrderParams:
    r"""
    Parameters for amending an order via WebSocket.
    """
    def py_new(self, category: BybitProductType, symbol: builtins.str, order_id: typing.Optional[builtins.str], order_link_id: typing.Optional[builtins.str], qty: typing.Optional[builtins.str], price: typing.Optional[builtins.str], trigger_price: typing.Optional[builtins.str], take_profit: typing.Optional[builtins.str], stop_loss: typing.Optional[builtins.str], tp_trigger_by: typing.Optional[builtins.str], sl_trigger_by: typing.Optional[builtins.str], order_iv: typing.Optional[builtins.str]) -> BybitWsAmendOrderParams:
        r"""
        Parameters for amending an order via WebSocket.
        """

@typing.final
class BybitWsCancelOrderParams:
    r"""
    Parameters for canceling an order via WebSocket.
    """
    def py_new(self, category: BybitProductType, symbol: builtins.str, order_id: typing.Optional[builtins.str], order_link_id: typing.Optional[builtins.str]) -> BybitWsCancelOrderParams:
        r"""
        Parameters for canceling an order via WebSocket.
        """

@typing.final
class BybitWsPlaceOrderParams:
    r"""
    Parameters for placing an order via WebSocket.
    """
    def py_new(self, category: BybitProductType, symbol: builtins.str, side: builtins.str, order_type: builtins.str, qty: builtins.str, is_leverage: typing.Optional[builtins.int], market_unit: typing.Optional[builtins.str], price: typing.Optional[builtins.str], time_in_force: typing.Optional[builtins.str], order_link_id: typing.Optional[builtins.str], reduce_only: typing.Optional[builtins.bool], close_on_trigger: typing.Optional[builtins.bool], trigger_price: typing.Optional[builtins.str], trigger_by: typing.Optional[builtins.str], trigger_direction: typing.Optional[builtins.int], tpsl_mode: typing.Optional[builtins.str], take_profit: typing.Optional[builtins.str], stop_loss: typing.Optional[builtins.str], tp_trigger_by: typing.Optional[builtins.str], sl_trigger_by: typing.Optional[builtins.str], sl_trigger_price: typing.Optional[builtins.str], tp_trigger_price: typing.Optional[builtins.str], sl_order_type: typing.Optional[builtins.str], tp_order_type: typing.Optional[builtins.str], sl_limit_price: typing.Optional[builtins.str], tp_limit_price: typing.Optional[builtins.str], order_iv: typing.Optional[builtins.str], mmp: typing.Optional[builtins.bool], position_idx: typing.Optional[BybitPositionIdx], bbo_side_type: typing.Optional[builtins.str], bbo_level: typing.Optional[builtins.str]) -> BybitWsPlaceOrderParams:
        r"""
        Parameters for placing an order via WebSocket.
        """

@typing.final
class BybitAccountType(enum.Enum):
    r"""
    Account type enumeration.
    """
    Unified = ...

    def py_new(self, value: typing.Any) -> BybitAccountType:
        r"""
        Account type enumeration.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitAccountType: ...

@typing.final
class BybitCancelType(enum.Enum):
    r"""
    Order cancel reason values as returned by Bybit.
    """
    CancelByUser = ...
    CancelByReduceOnly = ...
    CancelByPrepareLackOfMargin = ...
    CancelByPrepareOrderFilter = ...
    CancelByPrepareOrderMarginCheckFailed = ...
    CancelByPrepareOrderCommission = ...
    CancelByPrepareOrderRms = ...
    CancelByPrepareOrderOther = ...
    CancelByRiskLimit = ...
    CancelOnDisconnect = ...
    CancelByStopOrdersExceeded = ...
    CancelByPzMarketClose = ...
    CancelByMarginCheckFailed = ...
    CancelByPzTakeover = ...
    CancelByAdmin = ...
    CancelByTpSlTsClear = ...
    CancelByAmendNotModified = ...
    CancelByPzCancel = ...
    CancelByCrossSelfMatch = ...
    CancelBySelfMatchPrevention = ...
    Other = ...

@typing.final
class BybitEnvironment(enum.Enum):
    r"""
    Environments supported by the Bybit API stack.
    """
    Mainnet = ...
    r"""
    Live trading environment.
    """
    Demo = ...
    r"""
    Demo (paper trading) environment.
    """
    Testnet = ...
    r"""
    Testnet environment for spot/derivatives.
    """

    def py_new(self, value: typing.Any) -> BybitEnvironment:
        r"""
        Environments supported by the Bybit API stack.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitEnvironment: ...

@typing.final
class BybitMarginAction(enum.Enum):
    r"""
    Margin actions for spot margin trading operations.
    """
    Borrow = ...
    r"""
    Borrow funds for margin trading.
    """
    Repay = ...
    r"""
    Repay borrowed funds.
    """
    GetBorrowAmount = ...
    r"""
    Query current borrowed amount.
    """

    def py_new(self, value: typing.Any) -> BybitMarginAction:
        r"""
        Margin actions for spot margin trading operations.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitMarginAction: ...

@typing.final
class BybitMarginMode(enum.Enum):
    r"""
    Margin mode used by Bybit when switching risk profiles.
    """
    IsolatedMargin = ...
    RegularMargin = ...
    PortfolioMargin = ...

    def py_new(self, value: typing.Any) -> BybitMarginMode:
        r"""
        Margin mode used by Bybit when switching risk profiles.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitMarginMode: ...

@typing.final
class BybitOpenOnly(enum.Enum):
    r"""
    Filter for open orders query.
    
    Used with `GET /v5/order/realtime` to filter order status.
    """
    OpenOnly = ...
    r"""
    Query open status orders only (New, PartiallyFilled).
    """
    ClosedRecent = ...
    r"""
    Query up to 500 recent closed orders (cancelled, rejected, filled).
    """

@typing.final
class BybitOrderFilter(enum.Enum):
    r"""
    Order filter for querying specific order types.
    
    Used with `GET /v5/order/realtime` to filter by order category.
    """
    Order = ...
    r"""
    Active orders (default).
    """
    StopOrder = ...
    r"""
    Conditional orders (futures and spot).
    """
    TpslOrder = ...
    r"""
    Spot take-profit/stop-loss orders.
    """
    OcoOrder = ...
    r"""
    Spot one-cancels-other orders.
    """
    BidirectionalTpslOrder = ...
    r"""
    Spot bidirectional TP/SL orders.
    """

@typing.final
class BybitOrderSide(enum.Enum):
    r"""
    Order side enumeration.
    """
    Unknown = ...
    Buy = ...
    Sell = ...

@typing.final
class BybitOrderStatus(enum.Enum):
    r"""
    Order status values returned by Bybit.
    """
    Created = ...
    New = ...
    Rejected = ...
    PartiallyFilled = ...
    PartiallyFilledCanceled = ...
    Filled = ...
    Canceled = ...
    Untriggered = ...
    Triggered = ...
    Deactivated = ...

@typing.final
class BybitOrderType(enum.Enum):
    r"""
    Venue order type enumeration.
    """
    Market = ...
    Limit = ...
    Unknown = ...

@typing.final
class BybitPositionIdx(enum.Enum):
    r"""
    Position index values used for hedge mode payloads.
    """
    OneWay = ...
    r"""
    One-way mode position identifier.
    """
    BuyHedge = ...
    r"""
    Buy side of a hedge-mode position.
    """
    SellHedge = ...
    r"""
    Sell side of a hedge-mode position.
    """

    def py_new(self, value: typing.Any) -> BybitPositionIdx:
        r"""
        Position index values used for hedge mode payloads.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitPositionIdx: ...

@typing.final
class BybitPositionMode(enum.Enum):
    r"""
    Position mode as returned by the v5 API.
    """
    MergedSingle = ...
    r"""
    Merged single position mode.
    """
    BothSides = ...
    r"""
    Dual-side hedged position mode.
    """

    def py_new(self, value: typing.Any) -> BybitPositionMode:
        r"""
        Position mode as returned by the v5 API.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.int: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitPositionMode: ...

@typing.final
class BybitProductType(enum.Enum):
    r"""
    Product categories supported by the v5 API.
    """
    Spot = ...
    Linear = ...
    Inverse = ...
    Option = ...

    def py_new(self, value: typing.Any) -> BybitProductType:
        r"""
        Product categories supported by the v5 API.
        """
    def __hash__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def name(self) -> builtins.str: ...
    def value(self) -> builtins.str: ...
    def variants(self) -> builtins.list[builtins.str]: ...
    def py_from_str(self, data: typing.Any) -> BybitProductType: ...

@typing.final
class BybitStopOrderType(enum.Enum):
    r"""
    Stop order type classification.
    """
    None = ...
    Unknown = ...
    TakeProfit = ...
    StopLoss = ...
    TrailingStop = ...
    Stop = ...
    PartialTakeProfit = ...
    PartialStopLoss = ...
    TpslOrder = ...
    OcoOrder = ...
    MmRateClose = ...
    BidirectionalTpslOrder = ...

@typing.final
class BybitTimeInForce(enum.Enum):
    r"""
    Time-in-force enumeration.
    """
    Gtc = ...
    Ioc = ...
    Fok = ...
    PostOnly = ...

@typing.final
class BybitTpSlMode(enum.Enum):
    r"""
    Take-profit/stop-loss mode for derivatives orders.
    """
    Full = ...
    Partial = ...
    Unknown = ...

@typing.final
class BybitTriggerDirection(enum.Enum):
    r"""
    Trigger direction integers used by the API.
    """
    None = ...
    RisesTo = ...
    FallsTo = ...

@typing.final
class BybitTriggerType(enum.Enum):
    r"""
    Trigger type configuration.
    """
    None = ...
    LastPrice = ...
    IndexPrice = ...
    MarkPrice = ...

def py_bybit_bar_spec_to_interval(aggregation: builtins.int, step: builtins.int) -> builtins.str:
    r"""
    Converts a Nautilus bar aggregation and step to a Bybit kline interval string.
    
    # Errors
    
    Returns an error if the aggregation type or step is not supported by Bybit.
    """

def py_bybit_extract_raw_symbol(symbol: builtins.str) -> builtins.str:
    r"""
    Extracts the raw symbol from a Bybit symbol by removing the product type suffix.
    
    # Examples
    - `"ETHUSDT-LINEAR"` → `"ETHUSDT"`
    - `"BTCUSDT-SPOT"` → `"BTCUSDT"`
    - `"ETHUSDT"` → `"ETHUSDT"` (no suffix)
    """

def py_bybit_make_hedge_venue_position_id(instrument_id: model.InstrumentId, position_idx: typing.Optional[BybitPositionIdx]) -> typing.Optional[model.PositionId]:
    r"""
    Constructs a venue position ID only for hedge-mode Bybit position indexes.
    """

def py_bybit_product_type_from_symbol(symbol: builtins.str) -> BybitProductType:
    r"""
    Extracts the product type from a Bybit symbol.
    
    # Examples
    - `"ETHUSDT-LINEAR"` → `BybitProductType.LINEAR`
    - `"BTCUSDT-SPOT"` → `BybitProductType.SPOT`
    - `"BTCUSD-INVERSE"` → `BybitProductType.INVERSE`
    - `"ETH-26JUN26-16000-P-OPTION"` → `BybitProductType.OPTION`
    
    # Errors
    
    Returns an error if the symbol does not contain a valid Bybit product type suffix.
    """

def py_bybit_resolve_position_idx(position_mode: typing.Optional[BybitPositionMode], order_side: model.OrderSide, is_reduce_only: builtins.bool, manual_override: typing.Optional[BybitPositionIdx]) -> typing.Optional[BybitPositionIdx]:
    r"""
    Resolves the Bybit `positionIdx` for an outgoing order.
    
    Returns `None` when no position mode is configured. Otherwise returns the
    hedge-mode index for the position being affected (long or short), accounting
    for `is_reduce_only`. A `manual_override` always wins.
    """

def py_get_bybit_http_base_url(environment: BybitEnvironment) -> builtins.str:
    r"""
    Gets the Bybit HTTP base URL for the given environment.
    """

def py_get_bybit_ws_url_private(environment: BybitEnvironment) -> builtins.str:
    r"""
    Gets the Bybit WebSocket URL for private data (account/order management).
    """

def py_get_bybit_ws_url_public(product_type: BybitProductType, environment: BybitEnvironment) -> builtins.str:
    r"""
    Gets the Bybit WebSocket URL for public data (market data).
    """

def py_get_bybit_ws_url_trade(environment: BybitEnvironment) -> builtins.str:
    r"""
    Gets the Bybit WebSocket URL for trade operations (order placement/modification).
    """

