# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from nautilus_trader import model
import typing
__all__ = [
    "AvgLoser",
    "AvgWinner",
    "CAGR",
    "CalmarRatio",
    "Expectancy",
    "LongRatio",
    "MaxDrawdown",
    "MaxLoser",
    "MaxWinner",
    "MinLoser",
    "MinWinner",
    "PortfolioAnalyzer",
    "ProfitFactor",
    "ReturnsAverage",
    "ReturnsAverageLoss",
    "ReturnsAverageWin",
    "ReturnsVolatility",
    "RiskReturnRatio",
    "SharpeRatio",
    "SortinoRatio",
    "WinRate",
]

@typing.final
class AvgLoser:
    def py_new(self) -> AvgLoser: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class AvgWinner:
    def py_new(self) -> AvgWinner: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class CAGR:
    r"""
    Calculates the Compound Annual Growth Rate (CAGR) for returns.
    
    CAGR represents the mean annual growth rate of an investment over a specified period,
    assuming the profits were reinvested at the end of each period.
    
    Formula: CAGR = (Ending Value / Beginning Value)^(Period/Days) - 1
    
    For returns: CAGR = ((1 + Total Return)^(Period/Days)) - 1
    """
    def py_new(self, period: typing.Optional[builtins.int]) -> CAGR:
        r"""
        Calculates the Compound Annual Growth Rate (CAGR) for returns.
        
        CAGR represents the mean annual growth rate of an investment over a specified period,
        assuming the profits were reinvested at the end of each period.
        
        Formula: CAGR = (Ending Value / Beginning Value)^(Period/Days) - 1
        
        For returns: CAGR = ((1 + Total Return)^(Period/Days)) - 1
        """
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class CalmarRatio:
    r"""
    Calculates the Calmar Ratio for returns.
    
    The Calmar Ratio is a function of the fund's average compounded annual rate
    of return versus its maximum drawdown. The higher the Calmar ratio, the better
    it performed on a risk-adjusted basis during the given time frame.
    
    Formula: Calmar Ratio = CAGR / |Max Drawdown|
    
    Reference: Young, T. W. (1991). "Calmar Ratio: A Smoother Tool". Futures, 20(1).
    """
    def py_new(self, period: typing.Optional[builtins.int]) -> CalmarRatio:
        r"""
        Calculates the Calmar Ratio for returns.
        
        The Calmar Ratio is a function of the fund's average compounded annual rate
        of return versus its maximum drawdown. The higher the Calmar ratio, the better
        it performed on a risk-adjusted basis during the given time frame.
        
        Formula: Calmar Ratio = CAGR / |Max Drawdown|
        
        Reference: Young, T. W. (1991). "Calmar Ratio: A Smoother Tool". Futures, 20(1).
        """
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Expectancy:
    r"""
    Calculates the expectancy of a trading strategy based on realized PnLs.
    
    Expectancy is defined as: `(Average Win × Win Rate) + (Average Loss × Loss Rate)`
    This metric provides insight into the expected profitability per trade and helps
    evaluate the overall edge of a trading strategy.
    
    A positive expectancy indicates a profitable system over time, while a negative
    expectancy suggests losses.
    
    # References
    
    - Tharp, V. K. (1998). *Trade Your Way to Financial Freedom*. McGraw-Hill.
    - Elder, A. (1993). *Trading for a Living*. John Wiley & Sons.
    - Vince, R. (1992). *The Mathematics of Money Management*. John Wiley & Sons.
    """
    def py_new(self) -> Expectancy: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class LongRatio:
    def py_new(self, precision: typing.Optional[builtins.int]) -> LongRatio: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_positions(self, positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...

@typing.final
class MaxDrawdown:
    r"""
    Calculates the Maximum Drawdown for returns.
    
    Maximum Drawdown is the maximum observed loss from a peak to a trough,
    before a new peak is attained. It is an indicator of downside risk over
    a specified time period.
    
    Formula: Max((Peak - Trough) / Peak) for all peak-trough sequences
    """
    def py_new(self) -> MaxDrawdown:
        r"""
        Calculates the Maximum Drawdown for returns.
        
        Maximum Drawdown is the maximum observed loss from a peak to a trough,
        before a new peak is attained. It is an indicator of downside risk over
        a specified time period.
        
        Formula: Max((Peak - Trough) / Peak) for all peak-trough sequences
        """
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MaxLoser:
    def py_new(self) -> MaxLoser: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class MaxWinner:
    def py_new(self) -> MaxWinner: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class MinLoser:
    def py_new(self) -> MinLoser: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class MinWinner:
    def py_new(self) -> MinWinner: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class PortfolioAnalyzer:
    r"""
    Analyzes portfolio performance and calculates various statistics.
    
    The `PortfolioAnalyzer` tracks account balances, positions, and realized PnLs
    to provide portfolio analysis including returns, PnL calculations,
    and customizable statistics.
    """
    def py_new(self) -> PortfolioAnalyzer:
        r"""
        Analyzes portfolio performance and calculates various statistics.
        
        The `PortfolioAnalyzer` tracks account balances, positions, and realized PnLs
        to provide portfolio analysis including returns, PnL calculations,
        and customizable statistics.
        """
    def __repr__(self) -> builtins.str: ...
    def py_currencies(self) -> builtins.list[model.Currency]:
        r"""
        Returns all tracked currencies.
        """
    def py_get_performance_stats_returns(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        Calculates total PnL including unrealized PnL if provided.
        """
    def py_get_performance_stats_position_returns(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        Gets all position-return-based performance statistics.
        """
    def py_get_performance_stats_portfolio_returns(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        Gets all portfolio-return-based performance statistics.
        """
    def py_get_performance_stats_pnls(self, currency: typing.Optional[model.Currency], unrealized_pnl: typing.Optional[model.Money]) -> builtins.dict[builtins.str, builtins.float]: ...
    def py_get_performance_stats_general(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        Gets general portfolio statistics.
        """
    def py_add_position_return(self, timestamp: builtins.int, value: builtins.float) -> None:
        r"""
        Records a position return at a specific timestamp.
        """
    def py_add_return(self, timestamp: builtins.int, value: builtins.float) -> None:
        r"""
        Records a return at a specific timestamp.
        
        This is a backward-compatible alias for `Self.add_position_return`.
        """
    def py_reset(self) -> None:
        r"""
        Resets all analysis data to initial state.
        """
    def py_register_statistic(self, statistic: typing.Any) -> None:
        r"""
        Registers a new portfolio statistic for calculation.
        """
    def py_deregister_statistic(self, statistic: typing.Any) -> None:
        r"""
        Removes a specific statistic from calculation.
        """
    def py_deregister_statistics(self) -> None:
        r"""
        Removes all registered statistics.
        """
    def py_add_positions(self, positions: typing.Sequence[typing.Any]) -> None:
        r"""
        Adds new positions for analysis.
        """
    def py_add_trade(self, position_id: model.PositionId, realized_pnl: model.Money) -> None:
        r"""
        Records a trade's PnL.
        """
    def py_statistic(self, name: builtins.str) -> typing.Optional[builtins.str]:
        r"""
        Retrieves a specific statistic by name.
        """
    def py_returns(self) -> typing.Any:
        r"""
        Returns the primary calculated returns.
        
        This returns portfolio returns when available, otherwise it falls back
        to position returns for backward compatibility.
        """
    def py_position_returns(self) -> typing.Any:
        r"""
        Returns the per-position calculated returns.
        """
    def py_portfolio_returns(self) -> typing.Any:
        r"""
        Returns the portfolio calculated returns.
        """
    def py_realized_pnls(self, currency: typing.Optional[model.Currency]) -> typing.Any:
        r"""
        Retrieves realized PnLs for a specific currency.
        
        Returns `None` if no PnLs exist, or if multiple currencies exist
        without an explicit currency specified.
        """
    def py_total_pnl(self, currency: typing.Optional[model.Currency], unrealized_pnl: typing.Optional[model.Money]) -> builtins.float: ...
    def py_total_pnl_percentage(self, currency: typing.Optional[model.Currency], unrealized_pnl: typing.Optional[model.Money]) -> builtins.float: ...
    def py_get_stats_pnls_formatted(self, currency: typing.Optional[model.Currency], unrealized_pnl: typing.Optional[model.Money]) -> builtins.list[builtins.str]:
        r"""
        Gets formatted PnL statistics as strings.
        """
    def py_get_stats_returns_formatted(self) -> builtins.list[builtins.str]:
        r"""
        Gets formatted return statistics as strings.
        """
    def py_get_stats_position_returns_formatted(self) -> builtins.list[builtins.str]:
        r"""
        Gets formatted position-return statistics as strings.
        """
    def py_get_stats_portfolio_returns_formatted(self) -> builtins.list[builtins.str]:
        r"""
        Gets formatted portfolio-return statistics as strings.
        """
    def py_get_stats_general_formatted(self) -> builtins.list[builtins.str]:
        r"""
        Gets formatted general statistics as strings.
        """

@typing.final
class ProfitFactor:
    r"""
    Calculates the profit factor based on portfolio returns.
    
    Profit factor is defined as the ratio of gross profits to gross losses:
    `Sum(Positive Returns) / Abs(Sum(Negative Returns))`
    
    A profit factor greater than 1.0 indicates a profitable strategy, while
    a factor less than 1.0 indicates losses exceed gains.
    
    Generally:
    - 1.0-1.5: Modest profitability
    - 1.5-2.0: Good profitability
    - > 2.0: Excellent profitability
    
    # References
    
    - Tharp, V. K. (1998). *Trade Your Way to Financial Freedom*. McGraw-Hill.
    - Kaufman, P. J. (2013). *Trading Systems and Methods* (5th ed.). Wiley.
    """
    def py_new(self) -> ProfitFactor:
        r"""
        Calculates the profit factor based on portfolio returns.
        
        Profit factor is defined as the ratio of gross profits to gross losses:
        `Sum(Positive Returns) / Abs(Sum(Negative Returns))`
        
        A profit factor greater than 1.0 indicates a profitable strategy, while
        a factor less than 1.0 indicates losses exceed gains.
        
        Generally:
        - 1.0-1.5: Modest profitability
        - 1.5-2.0: Good profitability
        - > 2.0: Excellent profitability
        
        # References
        
        - Tharp, V. K. (1998). *Trade Your Way to Financial Freedom*. McGraw-Hill.
        - Kaufman, P. J. (2013). *Trading Systems and Methods* (5th ed.). Wiley.
        """
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class ReturnsAverage:
    def py_new(self) -> ReturnsAverage: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class ReturnsAverageLoss:
    def py_new(self) -> ReturnsAverageLoss: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class ReturnsAverageWin:
    def py_new(self) -> ReturnsAverageWin: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class ReturnsVolatility:
    r"""
    Calculates the annualized volatility (standard deviation) of portfolio returns.
    
    Volatility is calculated as the standard deviation of returns, annualized by
    multiplying the daily standard deviation by the square root of the period:
    `Standard Deviation * sqrt(period)`
    
    Uses Bessel's correction (ddof=1) for sample standard deviation.
    This provides a measure of the portfolio's risk or uncertainty of returns.
    
    # References
    
    - CFA Institute Level I Curriculum: Quantitative Methods
    - Hull, J. C. (2018). *Options, Futures, and Other Derivatives* (10th ed.). Pearson.
    - Fabozzi, F. J., et al. (2002). *The Handbook of Financial Instruments*. Wiley.
    """
    def py_new(self, period: typing.Optional[builtins.int]) -> ReturnsVolatility:
        r"""
        Calculates the annualized volatility (standard deviation) of portfolio returns.
        
        Volatility is calculated as the standard deviation of returns, annualized by
        multiplying the daily standard deviation by the square root of the period:
        `Standard Deviation * sqrt(period)`
        
        Uses Bessel's correction (ddof=1) for sample standard deviation.
        This provides a measure of the portfolio's risk or uncertainty of returns.
        
        # References
        
        - CFA Institute Level I Curriculum: Quantitative Methods
        - Hull, J. C. (2018). *Options, Futures, and Other Derivatives* (10th ed.). Pearson.
        - Fabozzi, F. J., et al. (2002). *The Handbook of Financial Instruments*. Wiley.
        """
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class RiskReturnRatio:
    r"""
    Calculates the risk-return ratio (mean/std) for portfolio returns.
    
    This is a non-annualized ratio of mean return to standard deviation.
    For an annualized version, use `SharpeRatio`.
    
    Downsamples high-frequency returns to daily bins before calculation
    for consistency with other ratio-based statistics.
    """
    def py_new(self) -> RiskReturnRatio:
        r"""
        Calculates the risk-return ratio (mean/std) for portfolio returns.
        
        This is a non-annualized ratio of mean return to standard deviation.
        For an annualized version, use `SharpeRatio`.
        
        Downsamples high-frequency returns to daily bins before calculation
        for consistency with other ratio-based statistics.
        """
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class SharpeRatio:
    r"""
    Calculates the Sharpe ratio for portfolio returns.
    
    The Sharpe ratio measures risk-adjusted return and is calculated as:
    `(Mean Return - Risk-free Rate) / Standard Deviation of Returns * sqrt(period)`
    
    This implementation assumes a risk-free rate of 0 and annualizes the ratio
    using the square root of the specified period (default: 252 trading days).
    
    # References
    
    - Sharpe, W. F. (1966). "Mutual Fund Performance". *Journal of Business*, 39(1), 119-138.
    - Sharpe, W. F. (1994). "The Sharpe Ratio". *Journal of Portfolio Management*, 21(1), 49-58.
    - CFA Institute Investment Foundations, 3rd Edition
    """
    def py_new(self, period: typing.Optional[builtins.int]) -> SharpeRatio:
        r"""
        Calculates the Sharpe ratio for portfolio returns.
        
        The Sharpe ratio measures risk-adjusted return and is calculated as:
        `(Mean Return - Risk-free Rate) / Standard Deviation of Returns * sqrt(period)`
        
        This implementation assumes a risk-free rate of 0 and annualizes the ratio
        using the square root of the specified period (default: 252 trading days).
        
        # References
        
        - Sharpe, W. F. (1966). "Mutual Fund Performance". *Journal of Business*, 39(1), 119-138.
        - Sharpe, W. F. (1994). "The Sharpe Ratio". *Journal of Portfolio Management*, 21(1), 49-58.
        - CFA Institute Investment Foundations, 3rd Edition
        """
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class SortinoRatio:
    r"""
    Calculates the Sortino ratio for portfolio returns.
    
    The Sortino ratio is a variation of the Sharpe ratio that only penalizes downside
    volatility, making it more appropriate for strategies with asymmetric return distributions.
    
    Formula: `Mean Return / Downside Deviation * sqrt(period)`
    
    Where downside deviation is calculated as:
    `sqrt(sum(negative_returns^2) / total_observations)`
    
    Note: Uses total observations count (not just negative returns) as per Sortino's methodology.
    
    # References
    
    - Sortino, F. A., & van der Meer, R. (1991). "Downside Risk". *Journal of Portfolio Management*, 17(4), 27-31.
    - Sortino, F. A., & Price, L. N. (1994). "Performance Measurement in a Downside Risk Framework".
      *Journal of Investing*, 3(3), 59-64.
    """
    def py_new(self, period: typing.Optional[builtins.int]) -> SortinoRatio:
        r"""
        Calculates the Sortino ratio for portfolio returns.
        
        The Sortino ratio is a variation of the Sharpe ratio that only penalizes downside
        volatility, making it more appropriate for strategies with asymmetric return distributions.
        
        Formula: `Mean Return / Downside Deviation * sqrt(period)`
        
        Where downside deviation is calculated as:
        `sqrt(sum(negative_returns^2) / total_observations)`
        
        Note: Uses total observations count (not just negative returns) as per Sortino's methodology.
        
        # References
        
        - Sortino, F. A., & van der Meer, R. (1991). "Downside Risk". *Journal of Portfolio Management*, 17(4), 27-31.
        - Sortino, F. A., & Price, L. N. (1994). "Performance Measurement in a Downside Risk Framework".
          *Journal of Investing*, 3(3), 59-64.
        """
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_returns(self, raw_returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_realized_pnls(self, _realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

@typing.final
class WinRate:
    r"""
    Calculates the win rate of a trading strategy based on realized PnLs.
    
    Win rate is the percentage of profitable trades out of total trades:
    `Count(Trades with PnL > 0) / Total Trades`
    
    Returns a value between 0.0 and 1.0, where 1.0 represents 100% winning trades.
    
    Note: While a high win rate is desirable, it should be considered alongside
    average win/loss sizes and profit factor for complete system evaluation.
    
    # References
    
    - Standard trading performance metric across the industry
    - Tharp, V. K. (1998). *Trade Your Way to Financial Freedom*. McGraw-Hill.
    - Kaufman, P. J. (2013). *Trading Systems and Methods* (5th ed.). Wiley.
    """
    def py_new(self) -> WinRate: ...
    def __repr__(self) -> builtins.str: ...
    def py_name(self) -> builtins.str: ...
    def py_calculate_from_realized_pnls(self, realized_pnls: typing.Sequence[builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_returns(self, _returns: typing.Mapping[builtins.int, builtins.float]) -> typing.Optional[builtins.float]: ...
    def py_calculate_from_positions(self, _positions: typing.Sequence[typing.Any]) -> typing.Optional[builtins.float]: ...

