# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from nautilus_trader import model
import typing
__all__ = [
    "DataEngineConfig",
    "PyOptionChainManager",
]

@typing.final
class DataEngineConfig:
    r"""
    Configuration for `DataEngine` instances.
    """
    def py_new(self, time_bars_build_with_no_updates: typing.Optional[builtins.bool], time_bars_timestamp_on_close: typing.Optional[builtins.bool], time_bars_skip_first_non_full_bar: typing.Optional[builtins.bool], time_bars_interval_type: typing.Optional[typing.Any], time_bars_build_delay: typing.Optional[builtins.int], time_bars_origin_offset: typing.Optional[typing.Mapping[model.BarAggregation, builtins.int]], validate_data_sequence: typing.Optional[builtins.bool], buffer_deltas: typing.Optional[builtins.bool], emit_quotes_from_book: typing.Optional[builtins.bool], emit_quotes_from_book_depths: typing.Optional[builtins.bool], external_clients: typing.Optional[typing.Sequence[model.ClientId]], debug: typing.Optional[builtins.bool], disable_historical_cache: typing.Optional[builtins.bool]) -> DataEngineConfig:
        r"""
        Configuration for `DataEngine` instances.
        """
    def py_time_bars_build_with_no_updates(self) -> builtins.bool: ...
    def py_time_bars_timestamp_on_close(self) -> builtins.bool: ...
    def py_time_bars_skip_first_non_full_bar(self) -> builtins.bool: ...
    def py_time_bars_interval_type(self) -> model.BarIntervalType: ...
    def py_time_bars_build_delay(self) -> builtins.int: ...
    def py_validate_data_sequence(self) -> builtins.bool: ...
    def py_buffer_deltas(self) -> builtins.bool: ...
    def py_emit_quotes_from_book(self) -> builtins.bool: ...
    def py_emit_quotes_from_book_depths(self) -> builtins.bool: ...
    def py_disable_historical_cache(self) -> builtins.bool: ...
    def py_debug(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class PyOptionChainManager:
    r"""
    Python-facing option chain manager that wraps [`OptionChainAggregator`] and
    [`AtmTracker`].
    
    The Cython `DataEngine` creates one instance per subscribed option series.
    It feeds incoming market data (quotes, greeks) through the `handle_*`
    methods and periodically calls `snapshot()` to publish `OptionChainSlice`
    objects to the message bus.
    
    ATM price is always derived from the exchange-provided forward price
    embedded in each option greeks/ticker update.
    """
    def py_new(self, series_id: model.OptionSeriesId, strike_range: model.PyStrikeRange, instruments: typing.Mapping[model.InstrumentId, tuple[model.Price, builtins.int]], snapshot_interval_ms: typing.Optional[builtins.int], initial_atm_price: typing.Optional[model.Price]) -> PyOptionChainManager:
        r"""
        Creates a new option chain manager.
        """
    def py_handle_quote(self, quote: typing.Any) -> builtins.bool:
        r"""
        Feeds a quote tick to the aggregator.
        
        Returns `True` if the manager just bootstrapped (first ATM price arrived
        and the active instrument set was computed for the first time).
        """
    def py_handle_greeks(self, greeks_obj: typing.Any) -> builtins.bool:
        r"""
        Feeds option greeks to the aggregator.
        
        Returns `True` if the manager just bootstrapped (ATM price derived from
        the greeks' `underlying_price`).
        """
    def py_snapshot(self, ts_ns: builtins.int) -> typing.Optional[model.OptionChainSlice]:
        r"""
        Creates a point-in-time snapshot from accumulated buffers.
        
        Returns `None` if no data has been accumulated yet (both buffers empty).
        """
    def py_check_rebalance(self, ts_ns: builtins.int) -> typing.Optional[tuple[builtins.list[model.InstrumentId], builtins.list[model.InstrumentId]]]:
        r"""
        Checks whether instruments should be rebalanced around the current ATM.
        
        Returns `None` when no rebalancing is needed.
        Returns `(added_ids, removed_ids)` when the active set should change.
        The caller is responsible for subscribing/unsubscribing instruments.
        """
    def py_active_instrument_ids(self) -> builtins.list[model.InstrumentId]:
        r"""
        Returns the currently active instrument IDs (the subset being tracked).
        """
    def py_all_instrument_ids(self) -> builtins.list[model.InstrumentId]:
        r"""
        Returns all instrument IDs in the full catalog.
        """
    def py_add_instrument(self, instrument_id: model.InstrumentId, strike: model.Price, kind: builtins.int) -> builtins.bool:
        r"""
        Adds a newly discovered instrument to the series.
        
        Returns `True` if the instrument was newly inserted.
        """
    def py_remove_instrument(self, instrument_id: model.InstrumentId) -> builtins.bool:
        r"""
        Removes an instrument from the catalog.
        
        Returns `True` if the catalog is now empty.
        """
    def py_series_id(self) -> model.OptionSeriesId: ...
    def py_bootstrapped(self) -> builtins.bool: ...
    def py_raw_mode(self) -> builtins.bool: ...
    def py_atm_price(self) -> typing.Optional[model.Price]: ...
    def __repr__(self) -> builtins.str: ...

