# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from nautilus_trader import infrastructure
from nautilus_trader import model
import typing
__all__ = [
    "BlockchainDataClientConfig",
    "BlockchainDataClientFactory",
    "BlockchainExecutionClientFactory",
    "DexPoolFilters",
    "py_load_pool_snapshot",
]

@typing.final
class BlockchainDataClientConfig:
    r"""
    Configuration for blockchain data clients.
    """
    def py_new(self, chain: nautilus_trader.model.Chain, dex_ids: typing.Sequence[nautilus_trader.model.DexType], http_rpc_url: builtins.str, rpc_requests_per_second: typing.Optional[builtins.int], multicall_calls_per_rpc_request: typing.Optional[builtins.int], wss_rpc_url: typing.Optional[builtins.str], use_hypersync_for_live_data: builtins.bool, from_block: typing.Optional[builtins.int], pool_filters: typing.Optional[DexPoolFilters], postgres_cache_database_config: typing.Optional[nautilus_trader.infrastructure.PostgresConnectOptions], proxy_url: typing.Optional[builtins.str]) -> BlockchainDataClientConfig:
        r"""
        Configuration for blockchain data clients.
        """
    def chain(self) -> nautilus_trader.model.Chain:
        r"""
        Returns the chain configuration.
        """
    def http_rpc_url(self) -> builtins.str:
        r"""
        Returns the HTTP RPC URL.
        """
    def wss_rpc_url(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the WebSocket RPC URL.
        """
    def rpc_requests_per_second(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the RPC requests per second limit.
        """
    def use_hypersync_for_live_data(self) -> builtins.bool:
        r"""
        Returns whether to use HyperSync for live data.
        """
    def from_block(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the starting block for sync.
        """
    def proxy_url(self) -> typing.Optional[builtins.str]:
        r"""
        Returns the optional proxy URL for HTTP and WebSocket transports.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns a string representation of the configuration.
        """

@typing.final
class BlockchainDataClientFactory:
    r"""
    Factory for creating blockchain data clients.
    
    This factory creates `BlockchainDataClient` instances configured for different blockchain networks
    (Ethereum, Arbitrum, Base, Polygon) with appropriate RPC and HyperSync configurations.
    """
    def py_new(self) -> BlockchainDataClientFactory:
        r"""
        Factory for creating blockchain data clients.
        
        This factory creates `BlockchainDataClient` instances configured for different blockchain networks
        (Ethereum, Arbitrum, Base, Polygon) with appropriate RPC and HyperSync configurations.
        """
    def name(self) -> builtins.str:
        r"""
        Returns the factory name.
        """
    def config_type(self) -> builtins.str:
        r"""
        Returns the configuration type.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns a string representation of the factory.
        """

@typing.final
class BlockchainExecutionClientFactory:
    r"""
    Factory for creating blockchain execution clients.
    """
    ...

@typing.final
class DexPoolFilters:
    r"""
    Defines filtering criteria for the DEX pool universe that the data client will operate on.
    """
    def py_new(self, remove_pools_with_empty_erc20_fields: typing.Optional[builtins.bool]) -> DexPoolFilters:
        r"""
        Defines filtering criteria for the DEX pool universe that the data client will operate on.
        """

def py_load_pool_snapshot(pg_config: nautilus_trader.infrastructure.PostgresConnectOptions, chain_id: builtins.int, pool_address: builtins.str, before_block: typing.Optional[builtins.int], require_valid: builtins.bool) -> typing.Optional[nautilus_trader.model.PoolSnapshot]:
    r"""
    Loads the latest pool snapshot from the Postgres cache for backtest replay.
    
    Connects to the cache database and reconstructs the most recent snapshot for the pool,
    including its full position and tick state, so a pool profiler can initialize before
    historical swaps and liquidity updates are replayed. When `before_block` is set, only
    snapshots at or before that block are considered, so the snapshot aligns with the replay
    start. When `require_valid` is `true`, only snapshots validated against on-chain state are
    returned. Returns `None` when no matching snapshot exists in the cache.
    
    # Errors
    
    Returns a `PyErr` if `pool_address` is not a valid pool identifier, or if the database
    connection or query fails.
    """

